ToucanToco/weaverbird

- README.md
- package.json
- yarn.lock
A new `build-doc` script target was added to `package.json`.
[Typedoc](https://typedoc.org/) is used to generate the documentation in the `dist/docs` directory.
> [doc] use TypeDoc to generate project documentation

- .circleci/config.yml
- README.md
- package.json
- rollup.config.js
- src/components/Step.vue
- tsconfig.json
- yarn.lock
Use rollup to generate a nice ES module bundle, importable by other projects using compatible ES6-compliant module bundlers.
In the parent project, `vue` must be added as dependency. It's not included in the `vue-query-builder` bundle.
The `yarn build-bundle --watch`, in combination with `yarn link`, enables convenient development across projects.
> Build :: rollup bundle

- .storybook/bundle.ts
- .storybook/rollup.config.js
- README.md
- package.json
- src/components/DomainSelector.vue
- src/components/Pipeline.vue
- src/components/Step.vue
- src/main.ts
- stories/index.js
- yarn.lock
So we can benefit from type checking inside vue components.
Docs to learn how to use these decorators and class syntax:
- https://vuejs.org/v2/guide/typescript.html
- https://github.com/vuejs/vue-class-component
- https://github.com/kaorun343/vue-property-decorator
Note: storybook now uses a specific bundle, also built with the same rollup configuration.
It's therefore needed to export any component to showcase in `.storybook/bundle.ts`.
> tech :: Convert vue components to TypeScript

- doc/steps.md
- src/lib/steps.ts
- src/lib/translators/base.ts
- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
Translation of a `replace` step in Mongo aggregation pipeline steps.
The `replace` step aims to replace value in a column, and write the resulting column inplace or in a new column.
Closes [issue #61](https://github.com/ToucanToco/vue-query-builder/issues/61)
> Feature :: 'replace' step translation in mongo

- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
This PR aims to replace $project by $addFields whenever possible.
When projecting a given key in a $project in a Mongo aggregation pipeline, you must specify that you project all other keys if you do not want to lose them. Therefore you would need to manipulate metadata to keep track of available columns, and it would generate a lot of noisy code (imagine that you need to add a new column and to keep 20 other ones, you will have a $project with 21 keys, of which 20 just saying `<key>: 1`...)
$addFields is less verbose, and can be used not only to add a new key but also to modify a key inplace while keeping all other columns. Indeed, specifying an existing field name in an $addFields operation causes the original field to be replaced, while every other columns remain. See [Mongo …
> Fix :: use $addFields instead of $project in rename and newcolumn steps

- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
Complete filter step implementation to support every basic operator among:
- 'eq' (equal to)
- 'ne' (not equal to)
- 'gt' (greater than)
- 'gte' (greater than or equal)
- 'lt' (less than)
- 'lte' (less than or equal)
- 'in' (in
- 'nin' (not in)
Related to issue https://github.com/ToucanToco/vue-query-builder/issues/63
But does not support complex filtering with (potentially nested) logical conditions
> Improve :: `filter` step translation to Mongo

- doc/steps.md
- src/lib/steps.ts
- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
Restrict AggFunctionStep interface to only support basic aggregation functions and improve transformAggregate to support every basic aggregation function among:
- sum
- avg
- count
- min
- max
Related to issue https://github.com/ToucanToco/vue-query-builder/issues/30
But dos not support more complex aggregations such as count_distinct
> Improve :: `aggregate` step mongo

- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
First we made the test case more coherent to give more sense to the query.
Then we managed 2 cases that were not supported:
- We do not want to merge two Mongo steps with common keys
- We do not want to merge two $project steps or two $addFields steps if the second step includes a reference to a key that was declared (created or modified) in the first step.
Closes https://github.com/ToucanToco/vue-query-builder/issues/76
> Fix :: simplify mongo pipeline

- doc/steps.md
- src/lib/steps.ts
- src/lib/translators/base.ts
- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
Support translation of a `sort` step in Mongo Aggregation Pipeline. Sort can be expressed on one or several columns; for any column, sorting order can be either "asc" or "desc".
Closes https://github.com/ToucanToco/vue-query-builder/issues/70
> Feature :: `sort` step mongo

- doc/steps.md
- src/lib/steps.ts
- src/lib/translators/base.ts
- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
Return top N rows, by group if `groups` is specified, else over full dataset.
```javascript
{
name: 'top',
groups: ['foo']
value: 'bar',
sort: 'desc' // or 'asc'
limit: 10
}
```
Closes https://github.com/ToucanToco/vue-query-builder/issues/66
> Feature :: Top step translation to mongo

- src/lib/steps.ts
- src/lib/translators/base.ts
- src/lib/translators/mongo.ts
make step types readonly both at compile time and run time.
This will avoid side-effects during transformation callbacks.
Closes #100
> feature :: readonly steps

- src/lib/matcher.ts
- src/lib/translators/base.ts
Since we chose the 'discriminated union' approach, when adding a new
step type, we had to add a new `case` condition to the giant `switch`
statement of the `translate` method. The idea was to let TypeScript check
at compile time that we didn't forget to handle a step type but in our
case, this is painful because the `case` code is always the same _and_
because the compile-time check is already enforced by the `implements
StepMatcher` condition on the `BaseTranslator` class.
I could not find a typescript way to remove the need of `case` so I just
decided to cheat and expclitly cast to a valid callback type.
Closes #98.
> [translator] force callback type cast

- src/lib/steps.ts
- src/lib/translators/base.ts
- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
Adopt the following conventions:
- step types should be ordered alphabtically in `PipelineStep` definition,
- step transform callbacks should be ordered alphabetically in `BaseTranslator`.
- prefix internal and intermediate mongo fields with `_vqb`
Closes https://github.com/ToucanToco/vue-query-builder/issues/107
> conventions :: adopt coding conventions

- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
We did not keep track of the _vqbAppArray and was source of error when the query is executed.
Also, we combined inclusion and exclusion of columns in a project, which is forbidden if exclusion does not concern the special _id key.
Related to https://github.com/ToucanToco/vue-query-builder/issues/68
> Fix ::  percentage step translation to mongo

- doc/steps.md
- src/lib/steps.ts
- src/lib/translators/base.ts
- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
Those steps return row(s) matching the maximum (for `argmax`) or minimum (for `argmin`) value in a given `column`, by group if `groups` is specified.
```javascript
{
name: 'argmin';
column: 'value'; // column in which to search for max value
groups: Array<string>; // optional
}
```
Closes https://github.com/ToucanToco/vue-query-builder/issues/65
> Feature:: 'argmax' and 'argmin' steps to mongo

- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
Do not allow mix of inclusions ("\<column\>: <any expr != 0>") and exclusions ("\<column\>: 0") when trying to merge $project steps, as it source of error in Mongo
Closes #114
> Fix :: simplifyMongoPipeline

- doc/steps.md
- src/lib/steps.ts
- src/lib/translators/base.ts
- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
Pivot rows into columns around a given `index` (expressed as a combination of column(s)).
Values to be used as new column names are found in the column `column_to_pivot`.
Values to populate new columns are found in the column `value_column`.
The function used to aggregate data (when several rows are found by index group) must be
among `sum`, `avg`, `count`, `min` or `max`.
```javascript
{
name: 'pivot',
index: ['column_1', 'column_2'],
column_to_pivot: 'column_3',
value_column: 'column_4',
agg_function: 'sum',
}
```
Closes https://github.com/ToucanToco/vue-query-builder/issues/64
> Feature:: 'pivot' step translation to mongo

- src/lib/translators/mongo.ts
Use lodash to reimplement `fromKeys` and introduce `columnMap` helper.
`columnMap` transforms a list of colun names into a map `col` → `$col`
which is a frequent pattern in steps such as `$group` or `$project`.
For instance:
```javascript
columnMap(['col1', 'col2', col3'])
```
will generate
```javascript
{col1: '$col1', col2: '$col2', col3: '$col3'}
```
Also provide a `$$` function helper that is simply a shortcut for
`$${col}`.
Related to #122
> feature :: lodash mongo utils

- rollup.config.js
`mathjs` is packaged in a way that makes `rollup-plugin-commonjs` unable
to identify which symbols should be exported, hence the following warning
we get at bundling time:
```
parse is not exported by node_modules/mathjs/index.js
331:         return ({
332:             $addFields: (_a = {},
333:                 _a[step.new_column] = buildMongoFormulaTree(math.parse(step.formula)),
^
334:                 _a),
335:         });
```
Therefore, `mathjs.parse` will end up being `undefined`.
To solve this problem, we can give the following hint to `rollup`:
```javascript
commonjs({
namedExports: { 'node_modules/mathjs/index.js': ['parse'] },
}),
```
and `rollup` will do the necessary to export the symbol.
> [rollup] make sure `mathjs.parse` is exported

- package.json
- src/lib/translators/mongo.ts
- make sure we use `const` if identifier is not reassigned (and fix the
two corresponding errors in `mongo.ts`)
- allow `console.warn` and `console.error`
Closes #128
> [eslint] set prefer-const and no-console rules

- playground/App.vue
- src/components/DomainSelector.vue
- src/components/Pipeline.vue
- src/components/Step.vue
- src/store/mutations.ts
This type should provide easy entry points to describe mutation callback
types. For instance, instead of writing:
```typescript
@Mutation setDomains!: (payload: Pick<VQBState, 'domains'>) => void;
```
you can now write:
```typescript
@Mutation setDomains!: MutationCallbacks['setDomains'];
```
> [store] introduce MutationCallbacks type

- playground/tsconfig.json
We only need to transpile `server.ts`, not all typescript modules found
in the directory.
> [playground] narrow transpilation to the bare minimum

- src/components/ActionMenu.vue
- src/components/DataViewer.vue
- src/components/FormRenameStep.vue
- src/store/mutations.ts
- src/styles/DataViewer.scss
- src/styles/_variables.scss
- tests/unit/action-menu.spec.ts
- tests/unit/form-rename-step.spec.ts
That PR create the Action Menu component that position itself according to which header we have clicked on. For the moment, only "Rename Column" is active and permit to open its form in order to create this step.
I open an issue for missing tests: #157 and that PR closes #32
> Feature :: Action Menu on DataViewer's header cells

- src/components/DeleteConfirmationModal.vue
- src/components/Step.vue
- src/styles/DeleteConfirmationModal.scss
- src/styles/_variables.scss
- tests/unit/step.spec.ts
This PR includes:
- The definition of a new DeleteConfirmationModal.vue component
- The rendering of this new component from Step.vue
- The logics of cancellation/validation of a step removal
Closes https://github.com/ToucanToco/vue-query-builder/issues/140
> Feature :: Ask for confirmation before deleting a step

- src/components/Vqb.vue
- src/store/backend-plugin.ts
- tests/unit/plugins.spec.ts
* Fix index computations in VQ component saveStep()
* Stop watching for the setPipeline mutation in backend-plugin (at init we already watch for the setDomain mutation, and afterwards we already watch at selectStep mutation)
> Fix :: pipeline and dataviewer update

- .circleci/config.yml
in order to avoid extreme slowness when running tests on the CI.
cf. https://discuss.circleci.com/t/yarn-tests-and-timeout/30741/2
and https://jestjs.io/docs/en/troubleshooting#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server
> [circleci] run jest in a single thread

- src/components/FormRenameStep.vue
- src/mixins/FormMixin.vue
- tests/unit/form-rename-step.spec.ts
Return an error if trying to rename a column with an already used column name.
Closes https://github.com/ToucanToco/vue-query-builder/issues/162
> [Rename step] :: error if newname corresponds to an existing column name

- package.json
- src/components/ActionMenu.vue
- src/components/formlib.ts
- tests/unit/widget-input-text.spec.ts
- yarn.lock
This will allow correct parsing of `xxx as Type` expressions.
Since parser claims to support only typescript version > 3.1, update
typescript version.
Fix errors raised consequently.
> [eslint] use tslint parser

- rollup.config.js
rollup bundling fixes the `__dirname` value to the entry point's dirname
rather than the actual module one. This could probably be fixed with a specific
plugin or by playing with the plugin order but I chose to implement a custom
`packageDir()` function that simply goes up in the directory hierarchy until
reaching the directory where `package.json` lies.
> [storybook] fix rollup config

- src/assets/schemas/delete-column-step__schema.json
- src/components/ActionMenu.vue
- src/components/DeleteColumnStepForm.vue
- src/components/Vqb.vue
- src/store/mutations.ts
- tests/unit/action-menu.spec.ts
- tests/unit/delete-column-step-form.spec.ts
- tests/unit/karma-test-suite.ts
- tests/unit/vqb.spec.ts
We now can delete a column from the action menu available on click on a column header.
When clicking on "Delete column" it directly deletes it and create the corresponding step in the pipeline (no need to go through a form).
The step can be edited via a form asking for a change of column to be deleted.
While the step API is built to allow the deletion of several columns at once, at this stage we manage the UI to delete only 1 column at once.
> Feature :: UI "Delete column" step

- tests/context.html
Injection slots are supposed to be `%CLIENT_CONFIG%` and `%MAPPINGS%`,
not `% CLIENT_CONFIG %` and `% MAPPINGS %` otherwise substitution is not
done correclty.
This fixes:
- the syntax error message in chrome console on `%`
- the catpured logs that didn't show in the console: \o/
> [karma] fix injection slots in context.html

- src/components/Vqb.vue
- src/components/formlib.ts
- src/components/stepforms/DeleteColumnStepForm.vue
- src/components/stepforms/FillnaStepForm.vue
- src/components/stepforms/RenameStepForm.vue
- src/components/stepforms/WidgetAutocomplete.vue
- src/components/stepforms/WidgetInputText.vue
- src/components/stepforms/index.ts
- tests/unit/delete-column-step-form.spec.ts
- tests/unit/fillna-step-form.spec.ts
- tests/unit/rename-step-form.spec.ts
- tests/unit/vqb.spec.ts
- tests/unit/widget-autocomplete.spec.ts
- tests/unit/widget-input-text.spec.ts
The directory is `src/components/stepforms` and its `index.ts` must
import all form components so that they registered automatically in the
`STEPFORM_REGISTRY`.
Note that we therefore still have to import `stepforms/` manually once at
some point.
> [forms] move step forms in a specific directory

- package.json
When we've changed our test runner, passing from `jest` to `karma`, we've also delegated coverage to `istanbul` and it handles in another way the file where the report lies.
> Fix :: Codecov report generation

- src/components/ActionMenu.vue
- src/components/Vqb.vue
- tests/unit/action-menu.spec.ts
- tests/unit/vqb.spec.ts
When a step edition form is already open and that we click on another operation, we want to keep the edition mode open, with the new form instantiated.
Before this PR, there was a trivial toggle of the edition mode which was based on the hypothesis that the edition mode was off before clicking on any operation, which is not reasonable. When the edition mode was already on it led us to click twice before opening the correct form: the first time to close the existing form, the second one to open the new form. Bad experience that is now improved !
> Feature :: Avoid bad toggling of step edition mode

- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
Before this commit, `simplifyMongoPipeline` would output a `[null]`
mongo pipeline if fed with an empty one. This is of course incorrect and
is caused by the following statements at the beginning of the function:
```typescript
const outputSteps: MongoStep[] = [];
let lastStep: MongoStep = mongoSteps[0];
outputSteps.push(lastStep);
```
This commit doesn't change this specific logic but instead explicitly
tests for an empty input pipeline and return another empty one in that
case.
> [translator] fix handling of empty mongo pipelines

- src/lib/matcher.ts
- src/lib/steps.ts
- src/lib/translators/base.ts
- src/lib/translators/mongo.ts
Step type definitions have no good reason to be readonly. In fact,
it is actually a pain to have steps being readonly in step forms since
we can't use the step types directly on a data attribute without wrapping
them with a specific `Writable` type that removes the `readonly` modiifier.
What we actually want is to make steps readonly during the translation process,
so just declare transform step function parameters as such and everything is
fine.
> [steps] make step type definitons writable

- src/assets/schemas/aggregate-step__schema.json
- src/components/ActionToolbar.vue
- src/components/DataViewer.vue
- src/components/Vqb.vue
- src/components/stepforms/AggregateStepForm.vue
- src/components/stepforms/WidgetAggregation.vue
- src/components/stepforms/WidgetList.vue
- src/components/stepforms/WidgetMultiselect.vue
- src/components/stepforms/index.ts
- src/lib/steps.ts
- src/store/mutations.ts
- src/styles/ResizablePanels.scss
- src/styles/_variables.scss
- tests/unit/action-toolbar.spec.ts
- tests/unit/aggregate-step-form.spec.ts
- tests/unit/karma-test-suite.ts
- tests/unit/store.spec.ts
- tests/unit/vqb.spec.ts
- tests/unit/widget-aggregation.spec.ts
- tests/unit/widget-list.spec.ts
- tests/unit/widget-multiselect.spec.ts
Introduce a complete UI for creating aggregations including:
- A new "WidgetMultiselect" component to manage the selction of multiple columns at once
- A new "WidgetList" component to manage repeatable form inputs
The Aggregate step form can be opened via the "Aggregate" button of the action toolbar.
Closes https://github.com/ToucanToco/vue-query-builder/issues/193
Closes https://github.com/ToucanToco/vue-query-builder/issues/194
Closes https://github.com/ToucanToco/vue-query-builder/issues/195
> PR :: UI Aggregate Step

- tests/unit/domain-step-form.spec.ts
Remove a forgotter .only left inside `domain-step-form.spec.ts` file.
> fix :: remove forgotten .only in domain step form tests

- src/components/stepforms/StepFormButtonbar.vue
- src/styles/_variables.scss
> UI :: Form Buttons Improvements

- src/styles/DataViewer.scss
improve :: active header caret icon
Before
Now
> improve :: active header caret icon

- src/components/Pipeline.vue
- src/styles/Pipeline.scss
- tests/unit/pipeline.spec.ts
Handle "empty" pipeline (when it only contains a `domain` step) with a clear message to tell the user to start using the table.
UI
> Feature :: Empty Pipeline

- src/components/stepforms/WidgetAutocomplete.vue
- src/components/stepforms/WidgetMultiselect.vue
- src/styles/_variables.scss
- grey background is now removed
- its color is darker
- the input label is darker as well
- add the same style for the placeholder when the multiselect input is clicked
- a bit of CSS cleaning, it's quite messy for the form style => we will need a refactoring soon.
> Polishing :: input form contrast improvement

- src/components/ActionMenu.vue
- src/components/ActionToolbar.vue
- src/components/ActionToolbarButton.vue
- src/components/DataViewer.vue
- src/components/Vqb.vue
- src/components/constants.ts
- src/components/stepforms/StepForm.vue
- tests/unit/action-menu.spec.ts
- tests/unit/action-toolbar.spec.ts
- tests/unit/vqb.spec.ts
In order to avoid writting special case for each steps. To do so, we now open form base on their names. The default case is defined in all forms and properties that we want to link to `selectedColumns` has already the logic to update itself when the getters was modified, I just add the fact is also done at the mounted cycle too.
> Feature :: Generic way to open forms

- src/components/stepforms/AggregateStepForm.vue
The stepSelectedColumn getter and setter functions were designed to manage some interactions with the table but had side effects.
We prefer no interaction rather than bad. I think that this interaction matter deserves a specific PR. In the meantime, forms work very well (or even better) without them !
**Exemple of issue:**
Context:
- An aggregate step has already been created in the pipeline and we want to modify it.
- A column which is not in the group by (`on`) parameter of the aggregate step form, is focused in the dataset
When clicking on edit: the focused column gets added to `editedStep.on` on opening.
When clicking on cancel: it does not cancel the undesired change (editedStep.on has been muted and cancel has the same effect as submit => there may be an issue to tackle in our …
> Fix :: Remove stepSelectedColumn getter and setter in AggregateStepForm

- src/components/stepforms/StepForm.vue
A bug was introduced leading to potentially override an input that listen on selectedColumn when editing a step. To fix that, we remove the `immediate: true` on the watcher and handle the edition case in mounted cycle.
> Fix :: Ignore current selectedColumns when editing a step

- src/components/stepforms/ColumnPicker.vue
This has no impact feature-wise but fixing names is always a good
idea and it will help debugging in Vue-developer-tools
> [column-picker] fix default export name

- playground/app.js
- src/components/DataViewer.vue
- src/lib/dataset/index.ts
- src/lib/dataset/mongo.ts
- src/main.ts
- src/store/getters.ts
- src/styles/DataViewer.scss
- src/styles/_variables.scss
- tests/unit/data-viewer.spec.ts
- tests/unit/dataset.spec.ts
- tsconfig.json
In order to eventually implement `cast` step and improve the steps suggestions in our ActionToolbar, we implement a function that guess type of columns according a nb of first rows. Of course, others backend can provide us the types directly but if it's not the case, we've got this little alternative.
That closes #237 
Now
> Feature :: Infer type of DataSetColumn

- src/components/stepforms/RenameStepForm.vue
- tests/unit/rename-step-form.spec.ts
Do not change the column focus if validation fails on submit.
Before that PR, if an already existing column name was trying to be set as new column name, the validation failed as expected but the mutation setSelectedColumn was executed, so that it also changed the value of the columnPicker field (column to rename), which was not desired.
> Fix :: rename step submit function

- src/lib/dataset/mongo.ts
- tests/unit/dataset.spec.ts
Before that PR, when in a column there were numbers of mixed types between integer and float, we would not infer any type. But as floats can include integers, we are better off inferring a float type in such cases.
> Infer types :: Infer float type when a column has a mix of integers and floats

- src/components/stepforms/WidgetAggregation.vue
- tests/unit/widget-aggregation.spec.ts
The previous code worked but in a roundabout way:
- `value` was set as `undefined` because no default was defined for this prop
- We copied the `value` prop in the `aggregation` data
- We watched a change in `value` to emit `aggregation` (weird already :))
- As such, `value` only changed once, at created (when switching from `undefined` to `defaultAggregation`)
- We therefore emitted `aggregation` at this first and only watched change
- At this stage, any subsequent change in `aggregation` impacted the parent only by reference and not by way of the watcher
So we propose here to clean the code to make it lighter:
- we set a valid default value for `value` prop directly through it decorator and not from a getter called at created
- we watch `aggregation` data rather than the `value` prop
> Fix WidgetAggregation :: Watch 'aggregation' data rather than 'value' prop

- src/components/ActionToolbar.vue
- src/components/SearchBar.vue
- src/components/constants.ts
- src/components/stepforms/WidgetAutocomplete.vue
- tests/unit/action-toolbar.spec.ts
- tests/unit/karma-test-suite.ts
- tests/unit/search-bar.spec.ts
So now we get the first step  of the search bar :
Wow it's amazing isn't it ?
- The search bar use the vue `multiselect` widget to display the results. 
- For now it's not displaying the operations grouped by category but with multiselect it's going to be simplier that we thought.  
- you can use your keyboard as well to navigate. 
- There are few css improvement for this specific multiselect.
> Feature :: search bar new branch and finalization

- src/lib/helpers.ts
Renamed `issStringBoolean` to `isBooleanString`.
This fix should have been included in the 'replace step' PR directly, my bad.
> [helpers] better helper function name for isBooleanString

- playground/app.js
- src/store/backend-plugin.ts
- src/store/state.ts
- tests/unit/plugins.spec.ts
`pagesize` will set the number of elements that should be displayed on
a single page of the dataviewer. Since there is no real pagination for now,
this is a just a simple limit
> [store] introduce a `pagesize` state property

- package.json
- playground/app.js
- playground/server.js
- src/components/Pagination.vue
- src/components/Vqb.vue
- src/lib/dataset/index.ts
- src/lib/dataset/pagination.ts
- src/store/backend-plugin.ts
- src/store/getters.ts
- src/store/mutations.ts
- src/store/state.ts
- src/typings/vuejs-paginate/index.d.ts
- tests/unit/dataset.spec.ts
- tests/unit/pagination-component.spec.ts
- tests/unit/pagination.spec.ts
- tests/unit/paginations.spec.ts
- tests/unit/plugins.spec.ts
- tests/unit/store.spec.ts
- yarn.lock
Add extra information to state to monitor current pagination context and wrap [vuejs-paginate](https://www.npmjs.com/package/vuejs-paginate)  to build a visual navigation bar
**NOTE** this PR should be merged into https://github.com/ToucanToco/vue-query-builder/pull/263
> [pagination] provide a simple pagination component

- src/components/stepforms/PivotStepForm.vue
- tests/unit/pivot-step-form.spec.ts
When a column is selected before opening the step form, we want to
mutate editedStep.column_to_pivot which was not the case before.
> Fix Pivot Step :: Add a custom stepSelectedColumn getter and setter

- src/components/stepforms/PercentageStepForm.vue
- tests/unit/percentage-step-form.spec.ts
When a column is selected before opening the step form, we want to
mutate editedStep.column which was not the case before.
> Fix Percentage Step :: Add a custom stepSelectedColumn getter and setter

- src/components/stepforms/FillnaStepForm.vue
- src/components/stepforms/FilterStepForm.vue
- src/components/stepforms/ReplaceStepForm.vue
- src/lib/dataset/index.ts
- src/store/getters.ts
- tests/unit/store.spec.ts
`columnTypes` is the `columnName` → `columnType` map for the current dataset.
This will avoid lines as below to proliferate:
```
const type = this.columnHeaders.filter(h => h.name === this.editedStep.search_column)[0].type;
```
since we can now use:
```
const type = this.columnTypes[this.editedStep.search_column];
```
> [getters] introduce the columnTypes getter

- src/components/SearchBar.vue
- src/components/constants.ts
- tests/unit/search-bar.spec.ts
Improvement of search bar, now it's organized by categories.
Vue multiselect doesn't allow you to customize a lot the group options so I try to do something not too ugly with it :
~~I put the label "wip" but if you're ok with this PR we can merge it for the V1 of VQB~~
=> After discussion it will be ok for the V1
@vdestraitt  Edit new version after your feedbacks :
> Feature :: search bar with categories

- src/components/ActionToolbar.vue
- src/components/SearchBar.vue
- src/components/constants.ts
- tests/unit/search-bar.spec.ts
Make formula step accessible from compute widget and from search bar
Therefore we get rid of the widget '+ column' which was less
intuitive and took some unnecessary space in the toolbar.
At the same time, we propose an enhancement of the SEARCH_BAR
constant definition to reflect its dependancy on the
ACTION_CATEGORIES constant definition
> Make formula step accessible from compute widget

- playground/app.js
- src/components/Pagination.vue
- src/lib/dataset/pagination.ts
- tests/unit/pagination-component.spec.ts
- tests/unit/pagination.spec.ts
add a counter to pagination component with three informations :
- page current min row => first row number which is displayed in the current page
- page current max row => last row number which is displayed in the current page
- row total rows 
At the last page `page current max row` is hidden.
> Feature :: pagination counter (clean branch)

- src/components/stepforms/widgets/Autocomplete.vue
- src/components/stepforms/widgets/FilterSimpleCondition.vue
- src/components/stepforms/widgets/InputText.vue
- tests/unit/autocomplete-widget.spec.ts
- tests/unit/filter-simple-condition-widget.spec.ts
- tests/unit/input-text-widget.spec.ts
- Do not render an empty label element in html of Autocomplete and InputText components to avoid alignment issues
- Make the autocomplete menu width to fit to the longest label size
- Change non intuitive labels for filter operators: "(not) be among" => "(not) be one of"
> Fix : Filter step US

- playground/app.js
- playground/dist/index.html
- playground/server.js
- src/lib/backend-response.ts
- src/store/backend-plugin.ts
- src/store/getters.ts
- src/store/mutations.ts
- src/store/state.ts
- tests/unit/pagination-component.spec.ts
- tests/unit/plugins.spec.ts
- tests/unit/store.spec.ts
**Before:** when a backend error occurred nothing happens. The user had no feedback or debug message.
**Now:** we catch backend error and store the last error message in the vuex store.
To do so, we introduce a new backend response format call `BackendResponse` and implemented in `lib/backend-response.ts`. 
**Before:** There was two possible backend responses: 
- list of string --> from `listCollection`
- Dataset --> from `executePipeline`
**Now:** All backend responses have the same "meta" format. It must be a object with two fields uncompatible fields:
- `data` can be of type `DataSet` (from `executePipeline`) or list of string (from `executePipeline`)
- `error` must be of type `ErrorResponse`
If the response has field `'error'` we now commit in the store a new state properties: …
> Feature :: catch backend error

- src/styles/Steps.scss
It was just a flex issue, the height of each steps was resized depends to screen size height. 
Quick win by using the `flex-shrink: 0;` proprety on step container.
closes https://github.com/ToucanToco/vue-query-builder/issues/285
Now we get a scrollbar :
> FIX :: allow scroll to pipeline steps  

- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
The _id column is useless and can be quite overwhelming in the data viewer ! So we propose to explicitly not project it.
> Do not project the _id column generated automatically by mongo

- src/components/stepforms/PercentageStepForm.vue
When selecting a column in the "group by" field it changed the
focus of column, and consequently changed the value of the "value
column" field (`ColumnPicker` component)
To avoid that we just removed the interaction on the "group by"
field.
We will have to wait to scope interactions better in the futur to
get this interaction back
> Do not create conflicting interactions between form fields

- playground/app.js
- playground/server.js
In order to have a logical count when returning data after changes in the pipeline, we have to `facetize` our query in order to keep count of our query and then skip/limit it in order to return only a part of the data.
> Fix :: pagination total count

- src/components/DataViewer.vue
- src/store/backend-plugin.ts
- src/store/mutations.ts
- src/store/state.ts
- tests/unit/data-viewer.spec.ts
- tests/unit/store.spec.ts
new state `isLoading` and mutations `setLoading` to display the data viewer loader.
The loader spinner in action :
closes #23
> Feature :: dataviewer loader spinner

- LICENSE
- package.json
Note: the npm package is called `visual-query-builder` cause the `vue-query-builder` was already taken. We could use a scope decorator but you have to pay enterprise plan in order to do so, for the moment is unecessary.
> Tech :: Preparation for NPM Registry

- src/components/DataViewer.vue
- src/styles/DataViewer.scss
The purpose to let it always visible is to show the user that he can open a menu on it. Proposition for #301
> Enhancement :: Always Display Caret in cell header

- src/components/stepforms/AggregateStepForm.vue
- src/components/stepforms/ArgmaxStepForm.vue
- src/components/stepforms/ArgminStepForm.vue
- src/components/stepforms/ColumnPicker.vue
- src/components/stepforms/DeleteColumnStepForm.vue
- src/components/stepforms/DuplicateColumnStepForm.vue
- src/components/stepforms/FillnaStepForm.vue
- src/components/stepforms/FilterStepForm.vue
- src/components/stepforms/FormulaStepForm.vue
- src/components/stepforms/PercentageStepForm.vue
- src/components/stepforms/PivotStepForm.vue
- src/components/stepforms/RenameStepForm.vue
- src/components/stepforms/ReplaceStepForm.vue
- src/components/stepforms/SelectColumnStepForm.vue
- src/components/stepforms/SortStepForm.vue
- src/components/stepforms/TopStepForm.vue
- src/components/stepforms/UnpivotStepForm.vue
- src/components/stepforms/schemas/filter.ts
- src/components/stepforms/widgets/Aggregation.vue
- src/components/stepforms/widgets/Autocomplete.vue
- src/components/stepforms/widgets/FilterSimpleCondition.vue
- src/components/stepforms/widgets/FormWidget.vue
- src/components/stepforms/widgets/InputText.vue
- src/components/stepforms/widgets/List.vue
- src/components/stepforms/widgets/Multiselect.vue
- src/components/stepforms/widgets/Replace.vue
- src/components/stepforms/widgets/SortColumn.vue
- tests/unit/filter-step-form.spec.ts
- tests/unit/form-widget.spec.ts
To avoid many modifications into each form step we use the mixins : `formWidget`. This mixins compute, the field message error and classError by matching right error with `dataPath` props pass by its step form parent component.
For `filterStepForm` we needed to change his schema to remove in and and conditions operator (for the moment) otherwise there was too many errors to display.
closes #181
> Feature :: Improve display error message

- src/components/domutil.ts
closes this issue : https://github.com/ToucanToco/vue-query-builder/issues/303
now when the popover is out of screen :
> Fix :: change offset computing method to get the good align right position

- package.json
- tsconfig.json
- yarn.lock
The `typedoc` documentation doesn't build anymore, mainly because of type errors in mocha and lodash.
This is fixed by updating lodash types package and ignoring the mocha one since it's broken.
> fix tsdoc generation

- src/styles/DataViewer.scss
There was a display issue on FF due to the css property `border-collapse: collapse;` on dataviewer table, HTML element `td` borders were hidden. It was due to a old known bug (not fixed) with border-collapse in Firefox.
To fix it we replace border-collapse with `border-spacing: 0;` and change a bit of css to reproduce the same border style in Firefox and all browsers.
before (FF) : 
Now (FF) :
> FIX :: Firefox didn't display dataviewer td border

- doc/steps.md
- src/components/stepforms/ReplaceStepForm.vue
- src/components/stepforms/schemas/index.ts
- src/components/stepforms/schemas/replace.ts
- src/lib/steps.ts
- src/lib/translators/mongo.ts
- tests/unit/labeller.spec.ts
- tests/unit/mongo.spec.ts
- tests/unit/replace-step-form.spec.ts
Remove the optional new_column parameter
If needing to replace values in a new column, the user can first
duplicate the column, and then apply the replacement in the new
column.
Closes https://github.com/ToucanToco/vue-query-builder/issues/296
> Simplify replace step

- src/styles/DataViewer.scss
with background-clip: padding-box property hack it resolves the hidden border issue due to border collapse on FF. It was due to  the combination of `border-collapse: collapse` and a background-color on `td` element, it's actually a old known bug on FF (not so easy to find this trick...).
Now on FF it's the same display as in Chrome:
> Fix :: Firefox hack for dataviewer border display

- CHANGELOG.md
- src/components/stepforms/UnpivotStepForm.vue
- src/lib/helpers.ts
- tests/unit/helpers.spec.ts
- tests/unit/unpivot-step-form.spec.ts
Do not require to specify the value_column_name or category_column_name.
The meaning of those parameters was not clear.
We can enforce a name to make the UX more straightforward, and if needed the user can apply a rename step.
Closes https://github.com/ToucanToco/vue-query-builder/issues/304
> Simplify unpivot step

- CHANGELOG.md
- src/components/stepforms/TopStepForm.vue
The `rank_on` parameter was not properly initialized.
Closes https://github.com/ToucanToco/vue-query-builder/issues/283
> Fix :: Top step initialization

- CHANGELOG.md
- src/components/stepforms/ArgmaxStepForm.vue
- src/components/stepforms/ArgminStepForm.vue
In `argmax`:
Bad labelling for `column` parameter ("min" instead of "max).
In `argmax` and `argmin`:
When choosing a column in the `groups` parameter, it selected the corresponding column, which in turn changed the value of the `column` parameter
Fixed bad initialization (when a column was selected before opening
the step form, the value of the ColumnPicker component was properly
initialized but editedStep was not)
> Fix labelling and bad interaction

- rollup.config.js
We don't need `terser` in development mode.
With `terser`, on my laptop:
- first build takes 40sec,
- subsequent builds in watch mode take 22sec,
Without `terser`, on my laptop:
- first build takes 19sec,
- subsequent builds in watch mode take 4sec
> [rollup] only use terser() in production mode

- CHANGELOG.md
- src/components/stepforms/widgets/List.vue
- tests/unit/list-widget.spec.ts
When a new field is added in the `List` widget, make sure to make
a (deep) copy of the default item otherwise we might just have several
items using references to the same object in memory.
closes #329
> [filter] fix shared references between conditions

- src/components/stepforms/FilterStepForm.vue
- src/components/stepforms/widgets/List.vue
- src/styles/_variables.scss
- tests/unit/filter-step-form.spec.ts
- Fix the input width size issue by adding the border-box: box-sizing property to all element inside the classname `.data-viewer` and `.query-builder`scope.
- Add a label separator `and` between conditions with a specific style to have a better visual UI understanding : now when we add a condition we get an extra margin-left on all widget-list item.
results :
> feature :: add a separator label to filters form and fix form input wrong sizing

- CHANGELOG.md
- src/lib/templating.ts
- src/store/backend-plugin.ts
- tests/unit/templating.spec.ts
Instead of outputting `'42'`, the interpolator will now output `42` if the corresponding
column type is `integer`. Similarly, it will output `true` instead of `'true'` if
it is a boolean, and so on.
closes #343'
> [templating] autocast output values

- CHANGELOG.md
- src/components/ActionMenu.vue
- src/components/ActionToolbarButton.vue
Fix the closing issue on widget popover menu on click on column header menu by adding a capture event on click listener.
Closes https://github.com/ToucanToco/vue-query-builder/issues/346
> FIX :: add capture catching on click listener to fix closing popover widget

- CHANGELOG.md
- src/components/ActionToolbarButton.vue
- tests/unit/action-toolbar-button.spec.ts
If a column is selected before clicking on lowercase or uppercase
operations, the step is applied directly without opening the form
Closes https://github.com/ToucanToco/vue-query-builder/issues/341
> Make lowercase and uppercase steps more straightforward

- CHANGELOG.md
- doc/steps.md
- src/components/ActionToolbarButton.vue
- src/components/constants.ts
- src/components/stepforms/ColumnPicker.vue
- src/components/stepforms/ConcatenateStepForm.vue
- src/components/stepforms/index.ts
- src/components/stepforms/schemas/concatenate.ts
- src/components/stepforms/schemas/index.ts
- src/components/stepforms/widgets/List.vue
- src/lib/labeller.ts
- src/lib/steps.ts
- src/lib/templating.ts
- src/lib/translators/base.ts
- src/lib/translators/mongo.ts
- tests/unit/action-toolbar-button.spec.ts
- tests/unit/action-toolbar.spec.ts
- tests/unit/column-picker.spec.ts
- tests/unit/concatenate-step-form.spec.ts
- tests/unit/labeller.spec.ts
- tests/unit/mongo.spec.ts
- tests/unit/templating.spec.ts
Introduce a `concatenate` step translated into mongo.
Allows concatenating several columns using a separator of the user's choice.
Closes https://github.com/ToucanToco/vue-query-builder/issues/340
> Feature :: concatenate step

- CHANGELOG.md
- doc/steps.md
- src/components/constants.ts
- src/components/stepforms/SplitStepForm.vue
- src/components/stepforms/index.ts
- src/components/stepforms/schemas/index.ts
- src/components/stepforms/schemas/split.ts
- src/lib/labeller.ts
- src/lib/steps.ts
- src/lib/templating.ts
- src/lib/translators/base.ts
- src/lib/translators/mongo.ts
- tests/unit/action-toolbar-button.spec.ts
- tests/unit/labeller.spec.ts
- tests/unit/mongo.spec.ts
- tests/unit/split-step-form.spec.ts
- tests/unit/templating.spec.ts
Introduce a `split` step translated into mongo.
Allows splitting a text column based on a delimiter. 
Closes https://github.com/ToucanToco/vue-query-builder/issues/339
> Feature :: split step

- src/components/stepforms/ColumnPicker.vue
- tests/unit/column-picker.spec.ts
- tests/unit/concatenate-step-form.spec.ts
Before this commit, when a concatenate step was edited, its "column"
fields were reset with the current selected column in the dataset
viewer.
This was because the `value` property sent by the `List` component to
the `ColumnPicker` which contains the edited step's column names was not
taken into account by the `ColumnPicker`. Instead, it was introspecting
an `initialColumn` property that was never passed in this case and
actually never used elsewhere…
This commit gets rid of the `initialColumn` property and uses `value`
instead.
Closes #366
> [concatenate] fix bad state sync on edition

- src/components/stepforms/StepForm.vue
- src/lib/steps.ts
The `Writable` type is not necessary anymore since steps are now
marked ad `Readonly` in the transformation functions.
> remove unused Writable type

- src/components/stepforms/StepForm.vue
Step form validator used to get built at component initialization. When editing a step, the _updateDataset runs to get the dataset resulting from executing the pipeline until the step just before the one being edited. But as this function is asynchronous, sometimes (quite frequently) the validator got built before the column names were updated, then yielding an unexpected "columnNameAlreadyUsed" error when trying to save a step again.
Example: use a duplicate step, name the new column "new", then edit the step, and just save it again. The quoted error would randomly occur.
This PR proposes to build the validator at submit to solve this issue.
> Fix :: step forms validator built too soon with obsolete column names

- README.md
- playground/mongo-server.js
[mongodb-prebuilt](https://github.com/winfinit/mongodb-prebuilt) uses
[mongodb-download](https://github.com/mongodb-js/mongodb-download) internally
to download mongodb binaries. Unfortunately, the URLs on
https://fastdl.mongodb.org used for these binaries have changed and
`mongodb-download` doesn't seem up-to-date, cf.
https://github.com/mongodb-js/mongodb-download/issues/36 and
https://github.com/mongodb-js/mongodb-prebuilt/issues/59
To bypass this issue, you can manually specify the download URL by setting the
`MONGODB_DL_URI` environment variable. For instance, you can use
the following command line:
`MONGODB_DL_URI=https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-4.0.13.tgz node playground/server.js --automongo`
or …
> [playground] circumvent mongodb-download out-of-date URLs

- yarn.lock
Indeed, their dependencies (or dependencies of depedencies) leads to an old version of "serialize-javascript" with moderate severity issue
> Fix :: serialize-javascript dependencies issue

- CHANGELOG.md
- README.md
- jest.config.js
- playground/app.js
- src/store/backend-plugin.ts
- src/store/getters.ts
- src/store/mutations.ts
- src/store/state.ts
- tests/unit/store.spec.ts
- yarn.lock
This PR introduces two new mutations:
- `logBackendError` to add a backend error to the logbook
- `resetErrorMessages` to empty the logbook
The former `setBackendError` mutation is removed.
Therefore, rather than having a single error message in the store, keep
track of all of them until the `resetBackendErrors` is called.
This is needed because otherwise the backend-plugin would reset a
previous error once a pipeline execution was successful. Since we
sometimes peform several pipeline executions in a row (e.g. if 2
mutations trigger a pipeline execution consecutively).
> keep history of error messages

- src/components/stepforms/widgets/MultiInputText.vue
- tests/unit/multi-input-text-widget.spec.ts
Multiselect dropdown enhancement to improve filter simple condition display.
Before the dropdown multiselect tag was pushing the content below : 
Now it's positionned in absolute with a scrollbar and max-height : 
It also contains other form improvement like better height size and change the old ugly arrow by a font awesome one :
> Filter simple condition form :: Visual improvement

- CHANGELOG.md
- src/lib/templating.ts
- tests/unit/mongo.spec.ts
- tests/unit/templating.spec.ts
```javascript
{
name: 'aggregate',
on: ['column1', '<%= foo %>'],
aggregations: [
{
aggfunction: 'avg',
column: '<%= foo %>',
newcolumn: '<%= egg %>',
},
],
}
```
with the context `{foo: 'bar'}` will generate:
```javascript
{
name: 'aggregate',
on: ['column1', 'bar'],
aggregations: [
{
aggfunction: 'avg',
column: 'bar'
newcolumn: '<%= egg %>',
},
],
}
```
closes #411
> make aggregation column parameters templatable

- src/components/constants.ts
- tests/unit/action-toolbar.spec.ts
This proposal comes from an interesting user feedback: we should order widgets in accordance with best practices in terms of transformations order.
In best case scenarios, we want the user to filter, then aggregate in order to perform additional computations on a data subset as small as possible.
> Reorder aggregate widget

- src/components/stepforms/widgets/Autocomplete.vue
- src/styles/DataViewer.scss
All in the title ⬆️ 
** Form multiselect add ellipsis **
before :
after :
** Dataset wrong height **
before :
Now:
> Fix :: add form input text ellipsis and wrong height dataset cells

- CHANGELOG.md
- docs/_docs/tech/steps.md
- docs/_docs/user-interface/filter.md
- src/components/stepforms/schemas/filter.ts
- src/components/stepforms/widgets/FilterSimpleCondition.vue
- src/lib/labeller.ts
- src/lib/steps.ts
- src/lib/translators/mongo.ts
- tests/unit/filter-step-form.spec.ts
- tests/unit/labeller.spec.ts
- tests/unit/mongo.spec.ts
This commit introduces two new filter operators:
- `matches` to test a value against a regexp
- `notmatches` to make sure a value doesn't match a regexp
This is translated directly to the `$regex` operator in mongo.
UI wise, we chose to add two new operatoers in the operator dropdown and
use the standard input widget for the user to type its regexp.
Current known limitations:
- it is not possible to use regexp with `in` / `nin` operators
- it is not possible to use flags (such as `i` to ignore case) but this
can be circumvented most of the time by adding a column with a
normalized value (e.g. lowercased) before testing the regexp.
closes #415
> add basic support for regexp in filter steps

- src/components/stepforms/widgets/MultiInputText.vue
- src/styles/DataViewer.scss
everything is explained in this F**** long title  ⬆️ 
Before in tucana :
Now you get the right font icon arrow:
> Fix :: remove css cursor pointer on data viewer cells / add fallback fontAwesome declaration

- .storybook/bundle.ts
- .storybook/preview-head.html
- package.json
- src/components/stepforms/ConditionsEditor/ConditionForm.vue
- src/components/stepforms/ConditionsEditor/ConditionsEditor.vue
- src/components/stepforms/ConditionsEditor/ConditionsGroup.vue
- src/lib/steps.ts
- stories/conditions-editor.js
- stories/index.js
- tests/unit/condition-form.spec.ts
- tests/unit/conditions-group.spec.ts
- yarn.lock
A new component to edit condition filter trees:
This recursive component accepts a slot to define the tree leave's form.
Here is the default case, with a simple input:
And a more advanced case with a three properties-object:
We intentionally removed the ability to create more than one level of nesting, to avoid unnecessary complexity. 
On the type-level, it defines a generic type: `AbstractConditionTree<T>` where T is the resulting type of the elements defined in the slot.
This component will then be used to enhance the FilterStep capabilities.
> Condition editor component

- package.json
- yarn.lock
This dependency comes from a time where we tried to make
karma work. Jest handles coverage natively, let's remove
this!
> [pkg] remove rollup-plugin-istanbul

- src/components/stepforms/widgets/List.vue
- src/components/stepforms/widgets/MultiInputText.vue
This PR fix an overflow issue when there is more than one row of tag into multiselect.
before : 
Now it's cropped to display only one line and we show everything on click:
This PR fix also another css visual issue a background color on filter step :
Now :
> Multiselect tags overflow issue

- playground/app.js
- src/components/DataTypesMenu.vue
- src/components/DataViewer.vue
- src/components/PipelineSelector.vue
- src/components/QueryBuilder.vue
- src/components/Vqb.vue
- src/store/actions.ts
- src/store/backend-plugin.ts
- src/store/getters.ts
- src/store/index.ts
- src/store/mutations.ts
- src/store/state.ts
- tests/unit/action-menu.spec.ts
- tests/unit/action-toolbar-button.spec.ts
- tests/unit/data-viewer.spec.ts
- tests/unit/pipeline-selector.spec.ts
- tests/unit/plugins.spec.ts
- tests/unit/query-builder.spec.ts
- tests/unit/store.spec.ts
- tests/unit/utils.ts
Add a component to choose which pipeline is currently displayed.
Introduce the possibility that no pipeline can be selected.
All the available pipelines are listed:
And changing the selected pipeline displays the newly selected pipeline at its last step:
Update: empty state when no pipeline is selected:
(To reproduce it, change the initial `currentPipelineName` in the playground's to `undefined`)
> Pipeline selector and no pipeline state

- src/components/stepforms/widgets/List.vue
- tests/unit/list-widget.spec.ts
As we remove and update element by their index in v-for, values are well updated but the dom does not render the right elements.
To fix that, we add unique ids but they can't be random cause it could lead to call `updateChildValue`, reinstantiating items because `children` computed properties will compute a new id as values change.
> Fix :: WidgetList item deletion

- CHANGELOG.md
- src/components/stepforms/FormulaStepForm.vue
- src/lib/translators/mongo.ts
- src/typings/mathjs/index.d.ts
- tests/unit/mongo.spec.ts
[mongo translator] :: allow to escape column name in FormulaStep with "[" and "]"
Before parsing the formula into a tree by mathjs, we replace all "[...]" by valid pseudo ("valid" for mathjs) and then re-put it back after building the mongo formula.
closes #295
> [mongo translator] :: allow to escape column name in FormulaStep with "[" and "]"

- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
Previously, we expected a map of domains to collections for the mongo
translator. This supposed that we already know all the available
domains and their correspondong collections. This is however not always
the case, e.g. if domains needs asynchronous loading.
I decided to replace it by a function, which cover the previous
case easily, and provide more possibilities.
> Map domains to collection with a translator method

- playground/server.js
`playground/default-dataset.csv` does not exist anymore,
the default dataset should be `playground/datastore/sales.csv`
> fix default dataset in playground

- src/components/stepforms/TopStepForm.vue
When setting a group, the setter `stepSelectedColumn` was called that set rank_on value to the last group added.
> Fix :: Top groups

- src/components/stepforms/widgets/JoinColumns.vue
- tests/unit/join-columns.spec.ts
- tests/unit/join-step-form.spec.ts
Previously, the initial prop was copied once at component's creation.
The component's internal state was hen modified by the component.
A watcher on the internal state propagated this changes upwards.
This approach had flaws:
- the component holds an internal state, but shouldn't (the source of
truth should be the form complete value object)
- if the form's value is modified outside the component, the
modification will never appear in the component
- additional deep watchers are added, which are quite useless
I restored the usual way of passing down props to components, and emit
up events to communicate changes requests.
Same logic than #457
> Change how changes are propagated from JoinColumns widget

- src/store/mutations.ts
- tests/unit/store.spec.ts
When navigating in or modifying the pipeline, the pagination needs
to be reset to avoid inconsistencies.
e.g consider a pipeline with 4 steps and a dataset on page 3. If the last step
is a filter step and the user removes it, the page `3` does not have the same
meaning. The only consistent behaviour is to go back to page 1 with the new
dataset.
> reset pagination after some mutations

- docs/_docs/tech/steps.md
The FilterStep format presented in the doc was outdated, from before we
support multiple conditions.
I also added a more complex example showcasing the nesting of logical
operators.
See https://github.com/ToucanToco/weaverbird/blob/master/src/lib/steps.ts#L156 for actual FilterStep type definition
> Update FilterStep technical doc

- src/components/stepforms/schemas/aggregate.ts
- src/components/stepforms/widgets/Aggregation.vue
- src/lib/labeller.ts
- src/lib/steps.ts
In Mongo these operators are called "$first" and "$and" so the translation process is the same as "sum" or "avg". Consequently, we do not need to update Mongo translator.
Before:
Now:
> Aggregation Step (a.k.a "groupby"): add "first" and "last" aggFunction

- codecov.yml
As long as the patch coverage is 100%, it's fine!
This could happen when covered lines are deleted, making the relative importance of uncovered lines raise.
> Authorize small drops of total coverage

- CHANGELOG.md
- src/components/stepforms/SortStepForm.vue
- src/components/stepforms/widgets/SortColumn.vue
- tests/unit/sort-step-form.spec.ts
Before this PR, at creation of the sort step form component, editedStep was
always overwritten with a default value.
We only want to suggest a default value when the step has never been edited yet
> sort step :: fix initialisation

- CHANGELOG.md
- src/components/stepforms/ColumnPicker.vue
- tests/unit/column-picker.spec.ts
- tests/unit/concatenate-step-form.spec.ts
- tests/unit/dateextract-step-form.spec.ts
Fix columnPicker to prevent the mutation of the props, as described in issue #462
Thanks to @davinov for this fix
> Fix columnPicker to prevent the mutation of the props

- CHANGELOG.md
- src/components/stepforms/widgets/Checkbox.vue
- tests/unit/checkbox-widget.spec.ts
Does not mutate the state of checkbox inside the component itself. The component listen only his prop "value" to update his template.
This means that parent of checkbox should "give back" to checkbox any emitted value to take into account the new value. For example, a v-model would do perfectly the job.
related to #462
NB: There is (for now) only one checkbox in weaverbird: in the unpivot step :)
> Fix checkbox props propagation

- CHANGELOG.md
- src/components/stepforms/AggregateStepForm.vue
- tests/unit/aggregate-step-form.spec.ts
Before: if performing an aggregation on one of the id columns the result pipeline result would display only one of the two expected columns
After: the aggregation is rename into {column-name}-{aggregation-name}
Before: (`st` column is aggregated to be counted, but `st` is also an `id` column of the aggregation)
After:
> Prevent column override when aggregating on an exiting column

- src/components/FilterEditor.vue
- src/components/stepforms/FilterStepForm.vue
- src/components/stepforms/widgets/FilterSimpleCondition.vue
- tests/unit/filter-simple-condition-widget.spec.ts
- Filter editor :: add missing error prop
It was broken when added the new component FilterEditor here #493
- Filter editor :: add columnNames prop
Add columnNames prop to permit to pass a list of column names from a dataset outside weaverbird
- Fix a CSS style not apply
> Filter editor :: fix missing error prop + add columnNames props

- CHANGELOG.md
- src/components/ActionMenu.vue
- src/components/ActionToolbarButton.vue
- src/components/DataTypesMenu.vue
- src/components/DataViewer.vue
- src/components/Popover.vue
- tests/unit/action-menu.spec.ts
- tests/unit/action-toolbar-button.spec.ts
- tests/unit/data-types-menu.spec.ts
- tests/unit/data-viewer.spec.ts
- tests/unit/popover.spec.ts
**Before**: to open the popover you set active props to “true” (and to close, you set active to “false”)
This is an issue, because the component is alway mounted. As popover is used twice (action menu and datatype menu) in column menu this may cause severe performance issue.
**Now**: to open the popover you use v-if (to not mount the component when not visible) or v-show (if you are ok to mount the component when not visible)
Notes:
- The v-if or v-show cannot be use directly on the popober.It should be set on a safe html parent. This parent is used to set its position.
- Update interface of all components that uses popover:
- `DataTypesMenu` (inside `DataViewer`)
- `ActionMenu`  (inside `DataViewer`)
- `ActionToolbarButton` (inside `ActionToolbar`)
> Improve Popover interface

- CHANGELOG.md
- src/components/ListUniqueValues.vue
- src/lib/dataset/helpers.ts
- tests/unit/dataset.spec.ts
- tests/unit/list-unique-values.spec.ts
In state, unique values of a column can be of any type. Thus, in ListUnqiueValues we must be careful to stringify them any time it is necessary. For search, for display and for v-for key.
> Fix: column unique values are of any type

- src/components/Popover.vue
- tests/unit/action-menu.spec.ts
- tests/unit/data-types-menu.spec.ts
- tests/unit/popover.spec.ts
Before:
- the positioning is done when popover is mounted
- as the content is generaly hidden when pover is mounted, we compute the position without the good dimension of the content (the with is 0, because content does not exists)
Now:
- the positioning computation happens when the "visible" props becomes "true". It waits the content to appear before computing position.
Before:
After:
> Fix popover position

- src/components/stepforms/widgets/MultiInputText.vue
Variable button was overdrawn by the multiselect focused input.
Isolating it in a separate context allow the (x) button to appear normally
> Isolate multiselect in z-index rendering

- CHANGELOG.md
- playground/app.js
- src/components/ActionMenu.vue
- src/components/Popover.vue
- tests/unit/action-menu.spec.ts
- tests/unit/popover.spec.ts
Remove immediate watch on "visible" prop and handle the behaviour at mounted and destroy
Before: if popover is destroyed when visible is true, the slot content is never remove from DOM because destroyPositioning has not been called
Now: at popover destroy, the slot content is cleaned from DOM
> Fix popover mount

- src/components/Popover.vue
As we make the element travel througth the DOM, we cannot compute again the parent elements after the first "setupPosition". Thus, we need to compute and register popover parent at mount
> Fix popover parents registration

- CHANGELOG.md
- playground/app.js
- playground/dist/index.html
- src/lib/backend-response.ts
- src/store/backend-plugin.ts
- src/store/getters.ts
- src/store/mutations.ts
- src/store/state.ts
- tests/unit/plugins.spec.ts
- tests/unit/store.spec.ts
When backendErrors was displayed we cannot display data as well.
This refactoring allow to use warnings messages when data is displayed.
Logic:
* Update/Add interfaces ( BackendError or BackendWarning )
* Renamed old variables to fit messages
* Remove unused reset mutation
* Update log mutation to replace data when a new query is made ( empty array to reset messages if no messages provided. )
* Fix tests
* Add playground example based on dataset rows count
> BackendMessages :: Allow to display warnings even if data is displayed

- src/components/stepforms/StepFormHeader.vue
> Fix back button style

- CHANGELOG.md
- package.json
- src/components/ActionToolbar.vue
- src/components/Popover.vue
- tests/unit/popover.spec.ts
- add an "handleEvent" method added to listener and then removed when destroy positioning.
- remove v-if: the element is removed at mount. It is then added to body when setup positioning.
- add a `.stop` propogation event modifier on action toolbar
> Fix popover position (again)

- CHANGELOG.md
- src/components/DataTypesMenu.vue
- tests/unit/data-types-menu.spec.ts
If a column datatype is not a string, now the date conversion is deactivated. After several user feedback, I believe that this improves a bit the UX while avoiding impossible conversions that yield mongo errors difficult to understand for the users.
> DataTypesMenu :: Deactivate date conversion option for non string columns

- .github/workflows/npm-publish.yml
- README.md
I suggest a simple GitHub workflow that will publish the package each time a release is created in GitHub.
> Publish to npm automatically

- src/components/Popover.vue
This robustify the following behaviour: a click inside popover should not close the popover
closes #542
> Popover click does not propagate to window

- CHANGELOG.md
- package.json
- src/components/SearchBar.vue
- src/components/stepforms/widgets/Autocomplete.vue
- src/components/stepforms/widgets/MultiInputText.vue
- src/components/stepforms/widgets/Multiselect.vue
Force the `vue-multiselect` component to open bellow.
This is a desirable behavior because no space is reserved above the widget.
Before (bad user experience):
After (more space is used below the widget):
> fix(multiselect): force the multiselect to open bellow

- src/components/stepforms/schemas/filter.ts
- tests/unit/filter-step-form.spec.ts
Removed minLength on filter input to allow empty or undefined value.
Empty input won't raise error anymore.
> fix: allow to filter with empty or undefined value

- src/lib/helpers.ts
- tests/unit/filter-step-form.spec.ts
Keep null as null even with integer type (due to cast null values became 0)
> fix: keep `null` value filter for numeric columns

- CHANGELOG.md
- src/components/Pagination.vue
- tests/unit/pagination-component.spec.ts
Pagination never displayed on last page of multiple pages dataset due to wrong condition.
We need to display pagination for every dataset that have more than one page.
> fix(pagination): always display pagination for multiple pages dataset

- CHANGELOG.md
- src/components/stepforms/widgets/FilterSimpleCondition.vue
- src/lib/helpers.ts
- tests/unit/filter-simple-condition-widget.spec.ts
- tests/unit/helpers.spec.ts
**Before:**  when changing operator with filter condition widget, value was reset to fit new type.
**After:** when changing operator with filter condition widget, value is reset only if its type don't match new type. Else keep previous value as selected one.
> fix(filters): keep value if typeof match on operator change

- CHANGELOG.md
- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
- tests/unit/mongo4.spec.ts
We merged addFields.
It causes issue if we try to use another added column as variable ( she won't exist as she is added at the same time).
We need to degroup add fields.
> fix: remove grouping of addFields steps in mongo query

- src/components/FilterEditor.vue
- src/components/stepforms/widgets/FilterSimpleCondition.vue
- src/components/stepforms/widgets/InputText.vue
- src/components/stepforms/widgets/MultiInputText.vue
- src/components/stepforms/widgets/VariableInput/VariableInput.vue
- src/components/stepforms/widgets/VariableInput/extract-variable-identifier.ts
- src/lib/variables.ts
- src/store/mutations.ts
- src/store/state.ts
- tests/unit/store.spec.ts
From now availableVariables and variableDelimiters (used in variableInput) can only be passed as props to widget.
It may be useful to use them in every widget and in QueryBuilder globally.
In prevision: added two mutations to populate state properties: `availableVariables` and `variableDelimiters`
> feat: allow to use availableVariables and variablesDelimiters from store

- src/components/ConditionsEditor/ConditionsGroup.vue
#599 created a duplicate icon:
> fix: remove duplicate delete row icon

- src/components/stepforms/AppendStepForm.vue
- src/components/stepforms/widgets/Multiselect.vue
- tests/unit/append-step-form.spec.ts
This PR makes the `Multiselect` component use the `option[label]` as label, when option is an object and label is defined.
> fix(multiselect): display the custom label

- src/components/DataViewer.vue
- tests/unit/data-viewer.spec.ts
This PR hides the column menus when the columns headers changes.
They are redefined each time a dataset is (re)loaded.
> fix(data-viewer): contextual menus now hide on dataset change

- CHANGELOG.md
- src/components/stepforms/EvolutionStepForm.vue
- src/lib/templating.ts
- tests/unit/templating.spec.ts
This PR extends our support for templating in several steps.
The main motivation was first to ensure that we do support templating in `templating.ts` for parameters for which we provide a UI to manage variables in the step forms components.
> Add templating support in various steps

- CHANGELOG.md
- docs/_docs/tech/custom-code-editor.md
- playground/app.js
- src/components/code-editor.ts
- src/components/stepforms/widgets/CodeEditorWidget.vue
- src/main.ts
- tests/unit/code-editor-widget.spec.ts
- tests/unit/set-code-editor.spec.ts
Add `setAvailableCodeEditors`, a new method, to provide custom configs associated to a lang key.
CodeEditorWidget can now take a lang param.
It will use the custom config if available otherwise it will use the default one
> feat(codeEditor): use a specific config in a codeEditorWidget

- src/components/stepforms/widgets/MultiInputText.vue
- src/components/stepforms/widgets/MultiVariableInput.vue
- src/components/stepforms/widgets/Multiselect.vue
- src/components/stepforms/widgets/VariableInput.vue
- src/components/stepforms/widgets/VariableInputs/AdvancedVariableModal.vue
- src/components/stepforms/widgets/VariableInputs/VariableInputBase.vue
- src/components/stepforms/widgets/VariableInputs/VariableTag.vue
- stories/variable.js
- tests/unit/advanced-variable-modal.spec.ts
- tests/unit/multi-input-text-widget.spec.ts
- tests/unit/multi-variable-input.spec.ts
- tests/unit/multiselect-widget.spec.ts
- tests/unit/variable-input-base.spec.ts
- tests/unit/variable-input.spec.ts
- tests/unit/variable-tag.spec.ts
Update advanced variable by clicking on a tag
Disable save when value is not updated in advanced variable modal
Replace advanced variable value rather than toggle it in multiVariableInput
Reset selected advanced variable to edit when saving or closing the advanced variable modal
> feat(advanced-variable): update an advanced variable

- src/components/DataViewer.vue
- tests/unit/data-viewer.spec.ts
Due to previous fix, we closed the action menu in any cases including when loading all values we should verify if the headers as change or if the current selected column is being modified ( don't close the action menu in this case ).
Before:
After:
> fix(load-all-values): keep action menu open

- playground/app.js
- src/lib/templating.ts
- src/main.ts
- src/store/state.ts
- tests/unit/templating.spec.ts
This was a not-so-good idea:
- same mechanism wasn't implement in hosts apps => created incoherences
between queries in the weaverbird preview, and what was actually
converted after in the host app
- column types can change during the pipeline => depending on the step
you come from, the interpolated pipeline is not always the same
Solution for this problem is to implement carefully the interpolator
function so that types are kept if a variable is declared alone in its
string. Such implem has landed in Tucana (main weaverbird host app for
now), so the auto-casting is not relevant anymore.
> fix: remove autocast in templating

- docs/_docs/tech/steps.md
- src/components/stepforms/FillnaStepForm.vue
- src/components/stepforms/schemas/fillna.ts
- src/lib/labeller.ts
- src/lib/steps.ts
- src/lib/translators/mongo.ts
- tests/unit/fillna-step-form.spec.ts
- tests/unit/labeller.spec.ts
- tests/unit/mongo.spec.ts
- tests/unit/templating.spec.ts
Before this PR, we updated the `column` parameter to support array of strings as well as a simple string (to fill null values in several columns at once).
But at this end, we target to keep only a `columns` (in the plural) parameter which can only be a list of strings creates a mandatory `columns` parameter for the new, preferred configuration, while still supporting retrocompatibility with the deprecated `column` parameter.
> fillna: change retrocompatibility implementation

- CHANGELOG.md
- src/components/stepforms/widgets/VariableInputs/VariableChooser.vue
- tests/unit/variable-chooser.spec.ts
Display a tooltip when hovering an option in variable chooser:
> feat(variable-chooser): display a tooltip with value when hovering a variable

- package.json
- playground/app.js
- src/components/convert-if-then-else-to-human-format.ts
- src/components/stepforms/FormulaStepForm.vue
- src/components/stepforms/IfThenElseStepForm.vue
- src/components/stepforms/schemas/formula.ts
- src/components/stepforms/schemas/ifthenelse.ts
- src/components/stepforms/widgets/IfThenElseWidget.vue
- src/lib/helpers.ts
- src/lib/steps.ts
- src/lib/templating.ts
- src/lib/translators/base.ts
- src/lib/translators/index.ts
- src/lib/translators/mongo.ts
- src/store/mutations.ts
- src/typings/mathjs/index.d.ts
- tests/unit/formula-step-form.spec.ts
- tests/unit/mongo.spec.ts
- yarn.lock
The formula and f/then/else steps accept Formulas that are parsed by Math.js and translated into the targeted query language.
However, as it were unaware of variables, the translation failed, trying to interpret the delimiters as if they were operators.
To avoid that, this PR make translators aware of variable delimiters so they can safely treat their content as a unique identifiers.
Also, the interpolated type of variables can be numbers, and not always strings. Hence, the formula parser must accept and understand other types than strings (only number for now), and treat the result as a standard value.
The playground variables have been updated to provide relevant examples.
Note: in formulas, identifier like `aaa` are considered to be column names. To keep a string as it is, it must be …
> Fix formulas with variables

- src/components/stepforms/widgets/MultiVariableInput.vue
This PR sets the multiple variable input z-index.
Before:
After:
> fix: set the multivariableinput z-index

- src/components/stepforms/widgets/MultiInputText.vue
- src/components/stepforms/widgets/MultiVariableInput.vue
Due to https://github.com/ToucanToco/weaverbird/pull/655 to fix overlapped input in filter condition, we created a bug.
Now in other step, as multi variable has a z-index 1. The dropdown are overlapped by the next input.
To fix it, we need to add a z-index only on the **active** multiinputtext ( added a z-index to variable toggler to display button even when multiinputtext is active).
Before:
After:
> fix(multiinput-text): display dropdown without be overlapped by next input

- src/directives/resizable/ResizableTable.ts
**What did you wizard :mage_woman: : ?**
It sorted the columns options to verify if columns are still the same or if we need to rerender the resizable table directive.
The thing is that we don't need to roll it :rofl: . So i sorted the columns in the ui (oupsssi).
Did a quick fix to avoid columns to get crazy.
Before:
After:
> fix(resizable-directive): should not sort the columns options

- CHANGELOG.md
- src/components/stepforms/schemas/pivot.ts
- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
- tests/unit/pivot-step-form.spec.ts
Before this PR, users were forced to specify at least 1 column in the index parameter, which is actually not expected in frequent cases, but lead users to create first a temporary column with the same value in all rows to be able to apply the step afterwards.
After this PR, we accept empty index.
> pivot step: allow empty index

- server/tests/steps/test_rename.py
- server/tests/test_pipeline_executor.py
- server/weaverbird/pipeline.py
- server/weaverbird/steps/__init__.py
- server/weaverbird/steps/rename.py
Add rename step in pandas backend.
:information_source:  I only implemented the new syntax (`toRename`), not the legacy one (`oldname` / `newname`).
> feat(server): rename step

- server/playground.py
- server/poetry.lock
- server/pyproject.toml
- server/tests/test_pipeline_executor.py
- server/weaverbird/pipeline_executor.py
I noticed that letting Flask serializing dataframes isn't good: we find NaN in the resulting JSON, which is invalid.
Letting pandas do the work prevents such a thing.
> test(server): ensure json df serialization is done by pandas

- .github/workflows/docker-playground.yml
Some PRs are failing because branches named with `/` cannot be used as docker image tags.
> build(server): sanitize branch name for image tagging

- .github/workflows/docker-playground.yml
- README.md
Let's publish the master branch container, so it's always easy for anyone to test the weaverbird playground locally.
> build(playground): build master branch for easy testing

- server/tests/steps/test_convert.py
- server/weaverbird/pipeline.py
- server/weaverbird/steps/__init__.py
- server/weaverbird/steps/convert.py
- src/lib/translators/pandas.ts
:warning: pandas cast can slightly differ from mongo's cast. For example, any string evaluates to `true` in mongo, whereas in pandas an empty string evaluates to `false`. I chose to keep pandas's cast for simplicity / performance (and because those are edge cases).
> feat(server): add convert step

- server/tests/steps/test_percentage.py
- server/weaverbird/steps/percentage.py
We had a weird error when using a pivot step : 
```
File "/home/fred/tctc/weaverbird/server/weaverbird/steps/percentage.py", line 20, in default_ts_created
return v or f'{values["column"]}_PCT'
KeyError: 'column'
```
this error is solved by using a fallback for `new_column_name` without a validator, the way I did in some other steps
> fix(server): fix percentage step

- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
We were not using the `$literal` operator to force mongo to interpret the string as text, which can cause issues to literal write labels such as '$label' interpreted as a field by mongo otherwise.
> text step: fix mongo translation and add test

- .github/workflows/ci-server.yml
the github action used to install poetry during CI is deprecated. this PR replaces it with a new one
> Replace the github action that install poetry

- CHANGELOG.md
- package.json
- src/components/stepforms/widgets/Checkbox.vue
On hover, a checkbox check appear at opacity 100%
So when we uncheck a checkbox and stay on hover, that makes us think that it's already checked.
Take a loot at the video to better understand.
Before:
After:
> chore(widget-checkbox): improve design on hover

- CHANGELOG.md
- src/lib/templating.ts
- src/store/state.ts
- tests/unit/plugins.spec.ts
- tests/unit/templating.spec.ts
For now when we use an array variable:
```[ <%= my_awesome_array %>, <%= my_awesome_string %> ]```
in an array (for step filer, $in, $nin for example ), we got:
```[ [ 'first_value',  'second_value'], 'other_value' ]```
while we want to flat this variable array:
```[ 'first_value',  'second_value', 'other_value' ]```
We need to flatmap array variables only. See exampleInterpolateFunc.
The logic will be reproduce in any projects needed
> feat(variables): allow to flatmap array variable when contained in an other array

- CHANGELOG.md
- src/components/ActionMenu.vue
- src/components/ActionToolbar.vue
- src/components/ActionToolbarButton.vue
- src/components/DataViewer.vue
- src/components/SearchBar.vue
- src/store/getters.ts
- tests/unit/action-toolbar-button.spec.ts
- tests/unit/action-toolbar.spec.ts
- tests/unit/search-bar.spec.ts
- tests/unit/store.spec.ts
Depending on the current translator:
| pandas | mongo40|
|--|--|
| ![Screenshot from 2020-11-20 11-00-14](https://user-images.githubusercontent.com/932583/99787690-59c59180-2b20-11eb-8432-90392aa0143b.png) | ![Screenshot from 2020-11-20 11-00-10](https://user-images.githubusercontent.com/932583/99787691-5a5e2800-2b20-11eb-9ea3-9a329d3cc7e9.png) |
| ![Screenshot from 2020-11-20 10-59-43](https://user-images.githubusercontent.com/932583/99787736-6813ad80-2b20-11eb-8b46-c0c5a11307a5.png) | ![Screenshot from 2020-11-20 10-59-46](https://user-images.githubusercontent.com/932583/99787734-677b1700-2b20-11eb-9890-fd3a2c7bed2d.png)  |
| ![Screenshot from 2020-11-20 10-19-43](https://user-images.githubusercontent.com/932583/99787816-824d8b80-2b20-11eb-98fe-a9798fc3032c.png)| ![Screenshot from …
> Hide unsupported steps from actions toolbar and menu

- README.md
- docs/_docs/tech/ui-components.md
The "UI components" is currently unreachable from the nav of the project website.
Probably the most interesting page of this website for someone who want to start using this project/contributing to it :grimacing:
> docs: missing slash is breaking a link on project website nav

- src/lib/backend.ts
- src/lib/dataset/helpers.ts
- src/store/actions.ts
- tests/unit/store.spec.ts
This will avoid the horrible "pipeline is empty" when instantiating the component.
> fix(front): updateDataset can reset the preview to an empty state when pipeline is empty

- src/components/stepforms/FillnaStepForm.vue
- src/components/stepforms/schemas/fillna.ts
- tests/unit/fillna-step-form.spec.ts
In previous PR: https://github.com/ToucanToco/weaverbird/pull/648,
We setted the column default value in filterStep equal to 
```
['']
```
So it displayed the value in multiselect as a selected column (because we considered that column was always a string so we included it into an array ).
We need to use undefined as default
Also added a minItems validation to schema and tests to validate that columns has at least one item selected
Before:
After:
> fix(fillna-step): use undefined as column default and add error when columns length is < 1

- package.json
- sonar-project.properties
- src/components/DataViewer.vue
- src/lib/dataset/index.ts
- src/lib/helpers.ts
- tests/unit/data-viewer.spec.ts
Sometimes the backend sends `long` as a dataset column type. It should be handled as an integer.
More context https://toucantoco.slack.com/archives/CSB3AEZPB/p1606816746228100
> fix(helpers): handle "long" as number

- src/components/ConditionsEditor/ConditionsEditor.vue
- src/components/ConditionsEditor/ConditionsGroup.vue
- src/components/FilterEditor.vue
- src/components/stepforms/widgets/FilterSimpleCondition.vue
When creating a condition or a group in filter step, there is a short time where condition is undefined (it's updated by default of FilterEditor on init ). Under this short time we don't want the undefined value to be casted.
> fix(filter-condition): dont cast undefined value when add group or condition

- src/components/stepforms/FilterStepForm.vue
- src/components/stepforms/IfThenElseStepForm.vue
- src/components/stepforms/widgets/IfThenElseWidget.vue
- tests/unit/.eslintrc.js
- tests/unit/filter-step-form.spec.ts
- tests/unit/ifthenelse-step-form.spec.ts
- tests/unit/ifthenelse-widget.spec.ts
Following the change of FilterStep, which now takes columnTypes as props, we now need to propagate this prop from the step form components to the FilterEditor widgets.
Note that in the IfThenElse step, there is an intermediate widget, between the step form and the FilterEditor.
> fix(front): column types in filter step and ifthenelse step

- CHANGELOG.md
- package.json
- sonar-project.properties
- src/components/ConditionsEditor/ConditionsEditor.vue
@alice-sevin je pense que c'était un oubli dans https://github.com/ToucanToco/weaverbird/pull/777 mais `defaultValue` n'était pas passée de `ConditionsEditor` à son fils `ConditionsGroup`, du coup lorsqu'on cliquait sur `Add condition` ou `Add group`, `ConditionsGroup#defaultValue` était `undefined` et ça cassait `castFilterStepTreeValue`
> fix(conditions-editor): pass the default value to ConditionsGroup

- CHANGELOG.md
- package.json
- sonar-project.properties
- src/components/ConditionsEditor/ConditionsEditor.vue
- src/components/ConditionsEditor/ConditionsGroup.vue
- stories/filter-editor.js
- tests/unit/conditions-editor.spec.ts
- tests/unit/conditions-group.spec.ts
There was some places that were missed both in https://github.com/ToucanToco/weaverbird/pull/786 and https://github.com/ToucanToco/weaverbird/pull/777 where `defaultValue` was not passed as prop
This caused some bug in Tucana's alerts, which was using the filter editor (crash when clicking on `add group` then `add condition`)
I passed the default value everywhere, updated the tests accordingly, and made it a required prop so that we don't make the same mistake again
> fix: pass default value everywhere

- src/store/actions.ts
Sorry to have broken it in the first place :/
Too bad we can't ignore a complete catch block
> test(front): fix coverage of an excluded catch block

- CHANGELOG.md
- src/components/DataViewer.vue
- src/styles/utils/v-tooltip.scss
- tests/unit/data-viewer.spec.ts
The tooltip is selectable for easy copy/paste
> feat(front): add a tooltip for each column name

- src/components/QueryBuilder.vue
The `selectCurrentDomain` and `selectStep` both request an update of the preview.
To avoid asking twice the work to the server, keep only the first one.
> fix(front): preview request only once when changing domain

- CHANGELOG.md
- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
This is what happen when you skip reading the docs before using an operator :stuck_out_tongue: 
I've tested this against my local mongo (4.4) to be sure it works (should be the same with 4.2).
> fix(mongo): fix usage of $regexMatch

- src/components/stepforms/widgets/IfThenElseWidget.vue
Fix a css bug that was preventing multiselect dropdowns inside the ifThenElse Widget to use their expected z-index because they were wrapped into another z-index context.
I insist that this issue was only affecting dropdowns inside the ifThenElse Widget, not any of the other one like the filter step widget for example.
Before :
After :
> fix(if then else widget): remove z-index context on dropdowns

- CHANGELOG.md
- src/store/getters.ts
- tests/unit/statistics-step-form.spec.ts
- tests/unit/store.spec.ts
This PR prevent the computed active step index to end up out of bound (meaning above the pipeline length).
Side note : I'm not a fan of having a specific `selectedStepIndex` value associated with a specific meaning, here `-1 <=> pipeline.length - 1`. It seems better to me to have `selectedStepIndex` explicitly set to `pipeline.length - 1` when necessary i.e. when loading/selecting pipelines. Fortunately it's not this big of a deal :wink:
> fix(getters): bound active step index to pipeline size

- CHANGELOG.md
- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
$nin doesn't exist in https://docs.mongodb.com/manual/meta/aggregation-quick-reference/#array-expression-operators
> fix(mongo): "not in" (`nin`) in if/then/else conditions

- .github/workflows/ci-server.yml
- server/pyproject.toml
- server/tests/test_utils.py
- server/weaverbird/utils/cleaning.py
This util had issues with input like:
```foo, foo, foo_1```
which gave:
```foo, foo_1, foo_1```
(which also contains duplicates :/)
and now gives:
```foo, foo_2, foo_1```
:ok_hand: 
**EDIT** I removed the caching of poetry's virtualenv because it caused issues :shrug: It adds maybe 1 minute duration in the python CI, but it's still the fastest of all our github checks, so imo it's not a problem (and also I'm lazy to find how to fix it properly).
> fix(server): fix util rename_duplicated_columns

- CHANGELOG.md
- src/components/DataTypesMenu.vue
- src/components/stepforms/ToDateStepForm.vue
- src/lib/translators/mongo4.ts
- tests/unit/data-types-menu.spec.ts
- tests/unit/mongo.spec.ts
- tests/unit/todate-step-form.spec.ts
Before this PR, we were unable to cast from a date to an integer or from an integer to a date, although this was expected by users, in particular to be able to perform some arithmetics on timestamps.
After this PR, a user can cast n integer to a date or vice versa via the interface.
> feat(convert step): support cast from string to integer and vice versa

- src/components/DataViewer.vue
- stories/data-viewer.js
- tests/unit/data-viewer.spec.ts
Also prevent to have "No data available" below the spinner while loading
> feat(front): add text and center loading spinner

- CHANGELOG.md
- src/store/getters.ts
- tests/unit/store.spec.ts
We want to display:
- first pipelines
- then domains.
Each category must be sorted alphabetically
> feat(front): order of combinable tables in selector

- src/components/stepforms/ToDateStepForm.vue
- src/lib/translators/mongo4.ts
- tests/unit/mongo.spec.ts
Transform string as year "2019" to a date based on first day of the month and first month of the year: 01/01/2019
:information_source: The column should always be cast as string to enable concat to work
Before:
After:
> fix(to date step): enable to transform a year string to a date

- src/components/ListUniqueValues.vue
- src/components/stepforms/widgets/Checkbox.vue
- tests/unit/checkbox-widget.spec.ts
- tests/unit/list-unique-values.spec.ts
For now, we got sometimes an issue with checkboxes (not display correctly) and very long label, it's very weird in unique values.
We also add a title on hover to be able to see the label entirely if cropped.
These options are disabled on other checkboxes but could be reimplemented in some cases if needed
Before:
After:
> feat(unique-values): display checkboxes and label correctly

- server/weaverbird/conditions.py
- src/components/ConditionsEditor/ConditionsGroup.vue
- src/components/FilterEditor.vue
- src/components/stepforms/convert-filter-step-tree.ts
- src/components/stepforms/schemas/filter.ts
- src/components/stepforms/widgets/FilterSimpleCondition.vue
- src/components/stepforms/widgets/InputDate.vue
- src/lib/helpers.ts
- src/store/state.ts
- tests/unit/filter-simple-condition-widget.spec.ts
- tests/unit/helpers.spec.ts
- tests/unit/input-date-widget.spec.ts
This PR:
* adds feature flags to weaverbird
* when the feature flag QUERYBUILDER_ESJSON is enabled:
* filter on a date field use a input date
* the pipeline will contain real dates objects, and no longer string
> filter on a date column now allows to use a date input.

- CHANGELOG.md
- src/components/stepforms/FromDateStepForm.vue
- src/components/stepforms/ToDateStepForm.vue
- src/lib/translators/index.ts
- src/lib/translators/pandas-no_joins.ts
- tests/unit/translator.spec.ts
Add a temporary `pandas-no_joins` translator that's exactly like the Pandas one without support for the join & append steps, so we can release the improved live data feature, that does not have support for those yet, now !
> feat(pandas): add no joins translator

- server/tests/test_pipeline_executor.py
- server/weaverbird/pipeline_executor.py
feat(structured exceptions): the exceptions thrown now has a field 'details'. It is a dict that will be returned as-is up to the front end. it MUST contains only json serializable objects.
cf. https://github.com/ToucanToco/laputa/pull/4265
> Better structured exceptions

- server/pyproject.toml
- server/tests/steps/test_date_extract.py
- server/tests/utils.py
- server/weaverbird/steps/date_extract.py
The pandas translator part of https://github.com/ToucanToco/weaverbird/pull/852 has missed a retro-compatibility case: when the new column name is not indicated, we should generate one automatically.
This case was correctly tested in the mongo implementation: https://github.com/ToucanToco/weaverbird/pull/852/files#diff-fadebd5a5aec933e0a42af86569ef7ff7858207165d4153572cfdf600d5972d6R2468
> fix(date-extract): keep retrocompatibily without new_column_name

- src/components/ConditionsEditor/ConditionsGroup.vue
> fix(conditions): display row corectly with long labels

- src/components/Pipeline.vue
- src/components/Step.vue
- src/lib/backend.ts
- src/store/actions.ts
- src/store/getters.ts
- src/styles/_variables.scss
- tests/unit/step.spec.ts
- tests/unit/store.spec.ts
Display errors directly in step.
( errors are going to be filtered from Tucana side, we still return step errors for now ).
Tucana will also return an error in index case (another PR to come, this one need to be merged first)
Before:
After:
Need to review: https://github.com/ToucanToco/weaverbird/pull/864 first
> feat(pipeline): display more readable errors

- server/tests/test_pipeline.py
- server/tests/test_pipeline_executor.py
- server/weaverbird/pipeline.py
- server/weaverbird/pipeline_executor.py
- server/weaverbird/steps/base.py
What has been done in https://github.com/ToucanToco/weaverbird/pull/865 is not enough (because parent models dict()'s options are always forwarded to children models), so let's enforce `exclude_none=True`.
This PR also contains a revert of PR #868, because this PR breaks the API and should not be included in weaverbird 0.3.4. This PR will be recreated afterwards, with version 0.4.0.
> feat(back): no more None values in step.dict()

- src/lib/variables.ts
- tests/unit/variables.spec.ts
Seems that we shouldn't use the -1 length in this case, work for all cases including new tests for malformatted variables (without spaces or some spaces only)
> fix(variables): retrieve variable identifier from malformatted variables

- src/components/stepforms/widgets/FilterSimpleCondition.vue
- src/components/stepforms/widgets/InputDate.vue
- src/lib/helpers.ts
- tests/unit/filter-simple-condition-widget.spec.ts
- tests/unit/helpers.spec.ts
Case 1: changing operator.
Add a case for date input to keep date for matches operator (otherwise date should be a string to match the keepCurrentValueIfCompatibleType logic (which apply a default value if type is not the same than default value one ).
Ex: we choose an eq operator, we change to ne operator (default value of ne oprator is '', and we have a date selected, we compare a date to a string so we reapply '' but we want to keep the date).
So we add a case for date with method keepCurrentValueIfCompatibleDate when column type is date
Case 2: changing column type
We need to reverify operator in this case too because we may don't want to keep old value.
Before:
After:
> fix(filter-condition): update value when changing widget

- src/components/stepforms/widgets/InputDate.vue
- src/lib/helpers.ts
- tests/unit/filter-simple-condition-widget.spec.ts
- tests/unit/helpers.spec.ts
- tests/unit/input-date-widget.spec.ts
Will disable logic to apply a default date in date input of  https://github.com/ToucanToco/weaverbird/pull/875 (if date is empty it will not validate the step as in other inputs :tada: )
Before:
After:
> fix(input-date): enable to use variables

- src/components/stepforms/FromDateStepForm.vue
- src/components/stepforms/ToDateStepForm.vue
- tests/unit/fromdate-step-form.spec.ts
- tests/unit/todate-step-form.spec.ts
Issue: We used a computed to define selected format (this computed was updated when changing value of custom format input (not only selected format in dropdown). 
We also automatically hide the custom format input if the format was present in the dropdown.
Resolve:
Remove computed property and use method to set selected format (custom format input update won't impact dropdown anymore)
Display custom format input when selected format is 'custom' 
:information_source: Made it on both steps (from and to) because logic is the same for the two steps
Before:
After:
> fix(date-step-form): always display custom input format when custom format is selected

- src/components/stepforms/FromDateStepForm.vue
- src/components/stepforms/ToDateStepForm.vue
- tests/unit/fromdate-step-form.spec.ts
- tests/unit/todate-step-form.spec.ts
> fix(date-step-form): display custom format input with empty field

- src/components/Pipeline.vue
- src/components/Step.vue
- src/store/actions.ts
- src/store/mutations.ts
- src/styles/_variables.scss
- tests/unit/pipeline.spec.ts
- tests/unit/step.spec.ts
- tests/unit/store.spec.ts
Remove trash icon on pipeline step to use a multiple delete logic.
Changed logic:
* Before, user could click on all pipeline step to select it => now, he can only select the right rectangle, the dot is used for delete toggle only (hovering the rectangle will applyt he dot hover style)
* Before, when user deleted a step, the next step was directly selected (can be in the middle of the pipeline) =>  now, we always select the last step because we can't know where the steps as been deleted
Before:
After:
> feat(pipeline): delete multiple steps at once

- .storybook/bundle.ts
- package.json
- src/components/Pipeline.vue
- src/components/Step.vue
- src/store/actions.ts
- src/styles/_variables.scss
- stories/filter-editor.js
- stories/step.js
- tests/unit/pipeline.spec.ts
- tests/unit/step.spec.ts
- tests/unit/store.spec.ts
- yarn.lock
Before: Plop nothing!
After:
Important: We don't want user to reorder this steps while deleting mode is active (we retrieve steps to delete based on indexes). So we added a disabled mode on actions when deleting steps
> feat(pipeline): enable to reorder steps using drag and drop

- src/components/Popover.vue
This z-index is needed in order to display the popovers in the embed.
> fix(popover): put z-index: 2 to popover

- src/components/Pipeline.vue
- src/lib/clipboard.ts
- src/lib/steps.ts
- src/store/actions.ts
- src/store/mutations.ts
- tests/unit/lib/clipboard.spec.ts
- tests/unit/pipeline.spec.ts
- tests/unit/store.spec.ts
Select some steps with delete steps tool logics will provide a list of steps.
When user use ctrl+c, we copy the steps content as string and add a parser (to make sure retrieved date come from weaverbird).
Then user can ctrl + v to another (or current) pipeline to add copied steps to it
Not working on all networks check https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
> feat(pipeline): copy/paste steps with clipboard

- src/components/stepforms/schemas/filter.ts
- src/components/stepforms/schemas/ifthenelse.ts
In case of 'is null' or 'is not null' condition, we remove the value field and set value to 'null'. It seems that Pandas delete 'null' value field from properties.
So when you come back to edit step, you can't validate because value field is required.
We should not required 'value' field
> fix(filter-condition): enable to have undefined value

- CHANGELOG.md
- src/components/stepforms/widgets/VariableInputs/VariableChooser.vue
- tests/unit/variable-chooser.spec.ts
Before, tooltip & value where different (June 8 midnight vs June 7 22hours) : 
After, tooltip & value are consistent :
> fix(variable chooser): always display date in UTC

- CHANGELOG.md
- src/components/stepforms/widgets/CodeEditorWidget.vue
There is some new css code in our other repository that override the height: 300px of the code editor, we should move it to the container and keep a 100% height logic to be similar on both repository (behaviour is the same that before)
Before:
(You can see that height: 300% is override byt height: 100%)
After:
(No impact on custom step because it was 300px height too, same behaviour than before :ok_hand: )
> fix(code-editor): move fixed height to container

- CHANGELOG.md
- src/components/ActionToolbar.vue
- src/components/DataViewer.vue
- src/components/Pipeline.vue
- src/store/getters.ts
- tests/unit/action-toolbar.spec.ts
- tests/unit/data-viewer.spec.ts
- tests/unit/pipeline.spec.ts
- tests/unit/store.spec.ts
In case where we use a translator without supported steps (except domain that is not launch by actions buttons, we should disabled the interface buttons to avoid using unsupported steps).
1. Add a getter to retrieve supported steps (exsiting one was only for unsupported steps)
2. Hide toggle menu button and prevent using action in data viewer header cells (css) (disabled type changing 'ABC', '123' icons click)
3. Hide action toolbar
4. Hide pipeline tips
Before:
After:
> feat(translators): hide actions from interface if no steps are supported

- server/tests/steps/test_date_extract.py
- server/weaverbird/steps/date_extract.py
Cast them to int64, so we don't have problems when exporting to json.
> fix: prevent uint32 in date extract results

- src/components/Step.vue
Change step's drag handle icon to something more similar to the intended design.
Before : 
After :
> fix(step): change drag & drop grip icon

- server/tests/steps/test_formula.py
- server/weaverbird/formula.py
The `formula` step of the python package could lead to `Infinity` in the resulting dataframe (after a division by 0).
`Infinity` does not have a json representation so it was sent as "null" to the frontend, which was misleading (dropna or fillna didn't work on these values).
Now, we replace these values by regular `np.nan`.
> fix(formula): avoid Infinity in resulting dataframe

- CHANGELOG.md
- src/components/Pipeline.vue
Following #928 
Before, pressing backspace went editing a input trigger the current step deletion modal : 
After, it's only triggered when not input field are focused :
> fix(pipeline): enable delete shortcut only when no other input is focused

- CHANGELOG.md
- src/components/ActionMenu.vue
- src/components/ActionToolbarSearch.vue
Due to overflow hidden, the search was not display correctly. But as search height by default is going over the popover, we need to fix it with important (added dynamically to DOM by multiselect plugin, force it by css using !important).
Before:
After:
After FF:
> fix(search): display search correctly

- src/components/DataViewer.vue
- src/directives/resizable/ResizableTable.ts
- tests/unit/resizable.spec.ts
Add an option to v-resizable table to display a certain amount of chars
Add another option to inform about the current chars displayed in col (can't be calculated due to white space no-wrap) that will cropp label
Add another option to target label in DOM
Adapt width of col based on max chars to display (retrieve pixel size for current chars and add missingwidth to fit the missing chars).
Adapt css to fit the new behaviour.
Tests:
We can't really tests DOM events (width with jest so we just test that function is correctly called)
Before:
After (more characters display (20 at max)):
> feat(resizable): adapt col width to fit max char per col option

- .storybook/bundle.ts
- src/components/Calendar.vue
- src/components/RangeCalendar.vue
- src/lib/dates.ts
- stories/calendar.js
- stories/range-calendar.js
- tests/unit/calendar.spec.ts
- tests/unit/range-calendar.spec.ts
Add a new range-calendar component to select a range between two dates display on two calendar one for start one for end
To have same behaviour that range in v-calendar we use v-calendar attributes to highlight dates between start and end in the calendars
Also added an availableDates logic to disable dates that are not able to be selected due to range side (start, end)
Design:
Usage:
> feat(range-calendar): add a new range calendar component

- .github/workflows/ci-server.yml
- server/README.md
- server/tests/backends/sql_translator/test_snowflake_translator_steps.py
* Use only password from Github actions secrets in Snowflake's e2e tests. 
* Add doc about it. in Readme.md
> ci: use only snowflake password from en variables

- server/pyproject.toml
- server/tests/steps/sql_translator/test_aggregate.py
- server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
Fix this issue: 
```(AggregateStep(name='aggregate', on=['LOCATION', 'SEX_NUMERIC'], aggregations=[Aggregation(new_columns=['SEX_NUMERIC_count distinct'], agg_function='count distinct', columns=['SEX_NUMERIC'])], keep_original_granularity=False), 9, 001003 (42000): 019e6383-0200-aa6b-0000-2f19006dd256: SQL compilation error: syntax error line 1 at position 1,048 unexpected 'distinct'. syntax error line 1 at position 1,066 unexpected ','. syntax error line 1 at position 1,080 unexpected 'FROM'. syntax error line 1 at position 1,131 unexpected ')'.)```
-> Aggregated columns were renamed based on the agg function name. 
count distinct has a whitespace hence, it generated invalid queries like: 
```AGGREGATE_STEP_2 AS (SELECT COUNT(DISTINCT SEX_NUMERIC) AS SEX_NUMERIC_count distinct, LOCATION, …
```
> fix: fix white space in agg column names

- .storybook/bundle.ts
- src/components/stepforms/widgets/DateComponents/RelativeDateForm.vue
- src/lib/dates.ts
- stories/dates/relative-date-form.js
- tests/unit/relative-date-form-widget.spec.ts
Add a new component to create a relative date from a quantity and a duration.
Design:
Usage:
> feat(relative-date-form): add new component

- src/lib/translators/index.ts
- src/lib/translators/snowflake.ts
- tests/unit/translator.spec.ts
As of now, we we were using the pandas-no joins frontend translator for SQL VQB. 
With this PR it's over!
> chore: register snowflake translator & available steps

- CHANGELOG.md
- src/components/Popover.vue
- tests/unit/action-menu.spec.ts
- tests/unit/data-types-menu.spec.ts
The popover is using a simple `.popover` class.
This name is so generic that collision have been reported by customers using Weaverbird via Toucan Embeds.
Let's avoid that.
> refactor(popover): prefix css class to avoid collision

- server/weaverbird/backends/sql_translator/metadata.py
- server/weaverbird/backends/sql_translator/steps/join.py
Fix issue on metadata management for join step.
The issue was that within the join step a column was aliased but this alias was not made available to the selection query. 
So for now, each time we alias a column with a step, we have to make sure to rename the column with its alias before building the selection query.
> fix(join): fix join step

- Dockerfile
Fixes https://github.com/ToucanToco/weaverbird/issues/1035
Tested:
```
docker build -t peanutbutter:latest .
docker run --rm --name peanutbutter -p 3000:3000 peanutbutter
```
```
yarn run v1.22.5
$ /weaverbird/node_modules/.bin/concurrently 'yarn start' 'cd server; FLASK_APP=playground FLASK_RUN_HOST=0.0.0.0 FLASK_RUN_PORT=5000 poetry run flask run'
[0] $ node playground/server.js
[0] [HPM] Proxy created: /pandas-backend  -> http://localhost:5000
[0] [HPM] Proxy rewrite rule created: "^/pandas-backend" ~> ""
[0] (node:52) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
[0] (Use `node --trace-warnings ...` to show where the warning was created)
[0] (node:52) Warning: Accessing non-existent property 'findOne' of module exports inside circular …
```
> install via make target installs weaverbird

- server/tests/backends/fixtures/append/simple.json
- server/tests/steps/sql_translator/test_append.py
- server/tests/steps/sql_translator/utils/test_query_transformation.py
- server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
To have the same behavior as the Pandas append step, we need to use UNION ALL keyword in Snowflake instead of just Union.
> fix(sql append): use union all in append step

- server/pyproject.toml
Bump to 0.7.6 for two fixes:
- UNION ALL in SQL append Step instead of UNION
- TOP N without group by keeps granularity.
> chore(backend version): bump to 0.7.6

- server/tests/backends/fixtures/substring/simple.json
- server/tests/steps/sql_translator/test_substring.py
- server/weaverbird/backends/sql_translator/steps/__init__.py
- server/weaverbird/backends/sql_translator/steps/substring.py
- src/lib/translators/snowflake.ts
- VQB snowflake substring step
> feat(vqb): added substring step

- CHANGELOG.md
- src/components/DataViewerCell.vue
- src/components/stepforms/widgets/VariableInputs/VariableListOption.vue
- tests/unit/data-viewer-cell.spec.ts
- tests/unit/variable-list-option.spec.ts
instead UTC or ISO (json) ones,
as we now overload the default Date.toString
beforehand to globaly control how dates are
displayed inside Toucan Toco
> fix(dates): use default toString

- server/pyproject.toml
- fix on aggregate group by + keep granularity
- fix on top keep granularity
- fix on rank keep granularity
> chore(bump): from 0.7.8 to 0.7.9

- server/pyproject.toml
- Snowflake VQB  :
- fix columns metadatas problems
- fix the keeping of granularity on aggregate step
- writing unittests for keep-granularity option
- fix collision on snowflake fixtures test when creating table names (allowing multiple tests instances running at the same time)
> chore(bump): from 0.7.9 to 0.8.0

- server/tests/backends/fixtures/evolution/abs_nogroups.json
- server/tests/backends/fixtures/evolution/perc_groups.json
- server/tests/backends/fixtures/evolution/perc_nogroups.json
- server/tests/steps/sql_translator/test_evolution.py
- server/weaverbird/backends/sql_translator/steps/__init__.py
- server/weaverbird/backends/sql_translator/steps/evolution.py
- src/lib/translators/snowflake.ts
* Add SQL Evolution Step
Implementation pattern: 
- Join the input query to itself on left Date = right Date + 1 Year/Month/Week
- Compute Evol in Abs or %  
- Use `DATEADD` to compute evolution from a provided timestamp column
https://user-images.githubusercontent.com/71276735/134045097-05b18fb9-fce4-49e7-8371-d3e94566e246.mp4
> feat(sql evolution): add evolution step & unit tests

- server/tests/backends/sql_translator/test_snowflake_translator_steps.py
- Because we were having too much tables when somebody was skipping/interrupting tests
- Too much residuals tables with unused datasets
- Added a kind of job to delete all old tables with more than 24h of creation
- Automatically catch the keyboard interrupt and try to kill all tables created
> feat(vqb): kill residuals tables + job to kill all old tables

- server/tests/steps/sql_translator/test_pivot.py
- server/weaverbird/backends/sql_translator/steps/pivot.py
When using SQL's `Pivot` step, we need to preselect columns from columns to keep, value column & pivot column to avoid keeping them in the transformation.
> fix(sql pivot): clean selected cols

- server/pyproject.toml
- server/tests/backends/fixtures/pivot/columns_cleaning.json
- server/tests/steps/sql_translator/test_pivot.py
- server/tests/steps/sql_translator/utils/test_query_transformation.py
- server/weaverbird/backends/sql_translator/steps/pivot.py
- server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
In SQL `Pivot` step we might have values with `-`, ` `, or starting with a number in value column to pass as column names.
This PR cleans such illegal characters.
> fix(sql pivot): handle pivot with illegal characters in value

- src/components/stepforms/widgets/DateComponents/CustomVariableList.vue
- src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
- stories/dates/date-range-input.js
- tests/unit/custom-variable-list.spec.ts
- tests/unit/date-range-input.spec.ts
Add a new prop enableRelativeDate to date range input
I false, it will hide the tabs 'Fixed'/'Dynamic' and use Fixed tab as default tab
Add specific label to custom variable list custom button if enableRelativeDate is false
> feat(front): make date-range input fixed/relative tabs hideable

- src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
- tests/unit/date-range-input.spec.ts
Before: we used range calendar component (two calendar next to each other)
After: we use a single calendar with isRange prop to true
> feat(date-range-input): replace range-calendar with unique calendar using a range

- .storybook/rollup.config.js
The storybook rollup config is based on the weaverbird config. So the extract option of postCss was kept at the launch of storybook which prevented the reload of the css when there was a change in a component.
So we override the postCss config by removing the extract option when we launch storybook.
> chore(build): storybook reload css

- src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
- src/lib/dates.ts
- tests/unit/date-range-input.spec.ts
A really gorgeous button to reset the selection to `undefined` (therefore the default value)
> feat(ui): reset button for DateRangeInput TCTC-1097

- src/components/DatePicker/Calendar.vue
- src/components/DatePicker/CustomGranularityCalendar.vue
- src/components/stepforms/widgets/DateComponents/TabbedRangeCalendars.vue
- src/lib/dates.ts
- stories/dates/date-range-input.js
- tests/unit/calendar.spec.ts
- tests/unit/custom-granularity-calendar.spec.ts
- tests/unit/lib/dates.spec.ts
- tests/unit/tabbed-range-calendars.spec.ts
In the "Fixed" tab of the Date Range Calendar, when switching between tabs, with bounds configured, the selected range could end up out of bounds because : 
- on "larger than day" granularity we allow selection of any period that completely OR partially without configured bounds
- bounds where not taken into account when retrieving the appropriate value when arriving on a new calendar
This led to : 
- a wrong range being displayed as selected
- and no range appearing as selected at all in the case of the "day" calendar
This PR fix that.
Make end calendars clamp the selected range to bounds before determining their corresponding value
and emit the end result back which is guaranteed to not be completely out of bound.
First tried to do this on their common parent `TabbedRangeCalendar` but …
> fix(range calendar): clamp selection to bounds when switching granularity TCTC-1031

- rollup.config.js
- src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
- src/components/stepforms/widgets/DateComponents/RelativeDateForm.vue
- src/components/stepforms/widgets/DateComponents/RelativeDateRangeForm.vue
- src/lib/dates.ts
- tests/unit/lib/dates.spec.ts
- tests/unit/new-date-input.spec.ts
- tests/unit/relative-date-form-widget.spec.ts
- tests/unit/relative-date-range-form-widget.spec.ts
In the Relative Date Range component, let the user choose is a relative range starts or end with the chosen base date or, in other words, if the specified duration goes "after" or "before".
Before : 
After : 
Notice that now we display "years" instead of "years ago" in the duration field, this required changes in DateRangeForm.
To complete those change, I also tried to improve the selected value label, so instead of :
it will display : 
and with the same base date, quantity & duration but using the "after" operator, it will show :
No changes required on `transformRelativeDateRangeToDateRange` or `transformRelativeDateObjectToDate` that seems to already handle both positive and negative range quantities.
> feat(relative date range): add before/after field in form

- src/components/DatePicker/CustomGranularityCalendar.vue
- tests/unit/custom-granularity-calendar.spec.ts
When we switch between granulrity tabs of calendars we want to retrieve options that fit the current selected option.
Day calendar is already ok because it has a from property, just needed to update navStart in customgranulrity calendar on granulrity watcher
Before:
After:
> fix(custom-granularity-calendar): update navigation based on selected option when switching between tabs TCTC-1031

- src/components/stepforms/widgets/DateComponents/RelativeDateRangeForm.vue
- src/lib/dates.ts
- tests/unit/lib/dates.spec.ts
- tests/unit/relative-date-range-form-widget.spec.ts
While doing UAT, we noticed that the "before" & "after" operator suggested that the base date was **excluded** from the resulting range while it was indeed **included**.
In further discussion, we discovered that there is indeed 4 possible operators for defining relative date range with our simplified form : 
Two of them being "inclusive" (until & from) and the two other being "exclusive" (before & after) : 
So operator names where not in tune with the underlying behavior. This PR fix that.
We'll see later if we implement the two other operators or choose those two instead of current ones.
> fix(relative date range form): use the right operator names TCTC-1182

- .storybook/.babelrc
This repairs the storybook build command, that were failing upon reading and trying to transpile the bundle of components produced by rollup.
With this, we should be able to deploy the storybook again.
> build(storybook): avoid babeling storybok bundle

- CHANGELOG.md
- src/components/DatePicker/transform-value-to-date-or-range.ts
- src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
- src/components/stepforms/widgets/DateComponents/RelativeDateRangeForm.vue
- src/lib/dates.ts
- stories/dates/date-range-input.js
- tests/unit/date-range-input.spec.ts
- tests/unit/lib/dates.spec.ts
- tests/unit/relative-date-range-form-widget.spec.ts
- tests/unit/transform-value-to-date-or-range.spec.ts
Following lessons learned in https://github.com/ToucanToco/weaverbird/pull/1173
Refactor our `RelativeDateRange` type to explicitly include an "operator" instead of deducing it from quantity's sign.
> refactor(relative date range): use a proper "operator" property TCTC-1183

- src/components/DatePicker/CustomGranularityCalendar.vue
- src/components/Tabs.vue
- src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
- src/components/stepforms/widgets/DateComponents/TabbedRangeCalendars.vue
- stories/dates/date-range-input.js
- tests/unit/date-range-input.spec.ts
Add compact class and custom css to define a mobile version (passed as props to define endpoint outside)
Enable to hide placeholder (display only calendar icon, when no value is selected)
Use correct alignement for popover on mobile
Add all cases as knobs to storybook
Info:
The calendar will be removed on compact mode when a value is selected in order to display label more clearly.
> feat(date-range-input): enable to use a compact mode for mobile purpose TCTC-755

- src/components/DatePicker/Calendar.vue
- src/components/DatePicker/CustomGranularityCalendar.vue
- src/components/stepforms/widgets/DateComponents/TabbedRangeCalendars.vue
- src/lib/dates.ts
- tests/unit/calendar.spec.ts
- tests/unit/custom-granularity-calendar.spec.ts
- tests/unit/lib/dates.spec.ts
- tests/unit/tabbed-range-calendars.spec.ts
Avoid selected range error when upadting bounds and value is now out of bounds.
Reset value instead
Also add a new behaviour to adapt nav to new selected bounds if there is no value selected (avoid user to stay on the same calendar page and have no available options)
:warning: There is a bug with day calendar on my chrome version exclusively don't keep attention on it
> fix(calendars): reset value when selected range is out of updated bounds TCTC-1248

- src/components/stepforms/widgets/VariableInputs/VariableInputBase.vue
- tests/unit/variable-input-base.spec.ts
> fix(variable-input-base): avoid variable to replace single string when selecting a variable in multiple mode TCTC-1047

- src/components/stepforms/schemas/filter.ts
- src/components/stepforms/schemas/ifthenelse.ts
- src/components/stepforms/widgets/FilterSimpleCondition.vue
- src/lib/labeller.ts
- src/lib/steps.ts
- src/lib/translators/mongo.ts
- src/lib/translators/mongo42.ts
- tests/unit/filter-simple-condition-widget.spec.ts
- tests/unit/labeller.spec.ts
When selecting a date column, transform the operators to have specific one : 'until'/'from'/'isnull'/'notnull' other column type refers to unchanged older types.
> feat(filter-step): use specific operator for date columns TCTC-1193

- src/components/stepforms/widgets/DateComponents/CustomVariableList.vue
- src/components/stepforms/widgets/DateComponents/NewDateInput.vue
- src/components/stepforms/widgets/FilterSimpleCondition.vue
- src/styles/_variables.scss
- tests/unit/filter-simple-condition-widget.spec.ts
- tests/unit/new-date-input.spec.ts
:warning: Need to review https://github.com/ToucanToco/weaverbird/pull/1191 first.
Replace date widget with new date input when a date column is selected in filter step
Also filter variables to return only dates one
Before:
After:
**Design:**
Before:
After:
:warning: Optional (added a two last commit to use variable tag for variable and display value for variables in list, not sure if we want to keep them ? Useful for conceptor to know value of variable right ? )
There is a strange behaviour with tooltip when closing the dropdown, ( solved in the commit using !isEditorOpened, video has been made before :wink: )
> feat(filter-step): replace date widget with new date input TCTC-1194

- src/components/stepforms/FilterStepForm.vue
- src/components/stepforms/widgets/FilterSimpleCondition.vue
- tests/unit/filter-simple-condition-widget.spec.ts
When relative date feature flag is switched, operators change so it may happen that some previously selected operator missed. We want to replace them with correct available operator:
until -> le
from -> ge
ge/gt -> from
le/lt -> until
If the operator is available fallback to it
If the operator is not in the list (ex: eq) fallback to first available operator
Also fixed the filter step behaviour because it was reassigning default value after the migration of operator
> fix(filter-step): update invalid operator when switching relative date feature flag TCTC-1193

- src/components/stepforms/widgets/FilterSimpleCondition.vue
- src/lib/dates.ts
- src/lib/helpers.ts
- tests/unit/filter-simple-condition-widget.spec.ts
- tests/unit/helpers.spec.ts
- tests/unit/lib/dates.spec.ts
Keep a relative date selected when switching between relative date operators.
Before:
Relative date was transformed to a simple date because we didn't authorize relative date in Date validator
After:
Add a new condition to enable relative date, keep it unchanged if operator is from/until
UAT:
Apply feature flag for relative date as enabled
Create a filter step on a date column
Select from operator
Select a relative date as value
Switch to until operator (should keep relative date value unchanged)
> fix(filter-step): keep relative date selected when switching from/until operators TCTC-1193

- src/lib/dates.ts
- tests/unit/date-range-input.spec.ts
- tests/unit/labeller.spec.ts
- tests/unit/lib/dates.spec.ts
- tests/unit/new-date-input.spec.ts
Remove suffix and separator for relative date label going from:
2 months ago until - Last week
to
2 months until Last week
> fix(relative-date): simplify label for relative date removing suffix and separator

- src/components/stepforms/widgets/DateComponents/NewDateInput.vue
- src/lib/dates.ts
- src/lib/translators/mongo5.ts
- stories/dates/new-date-input.js
- tests/unit/mongo.spec.ts
- tests/unit/new-date-input.spec.ts
1. Retrieve relative variables based on date variables in availableVariables in NewDateInput
2. Use selected variable as date base for relative date filtering (mongo)
> feat(mongo): enable to use variable as base date for relative date filtering TCTC-1321

- CHANGELOG.md
- src/components/Pipeline.vue
- src/components/PreviewSourceSubset.vue
- src/lib/backend.ts
- src/lib/dataset/index.ts
- src/store/actions.ts
- src/store/getters.ts
- src/store/mutations.ts
Not the definitive design, just a quick but still functional implementation.
> feat(backend service):  configurable "preview source" rows subset TCTC-1324

- playground/app.js
- playground/dist/index.html
Hi Toucan,
Here is my PR to add buttons to select a backend.
When Pandas is selected, we remove the mongo query.
> feat(playground): add buttons to select a backend

- src/components/stepforms/StatisticsStepForm.vue
- src/components/stepforms/widgets/InputNumber.vue
- tests/unit/input-number-widget.spec.ts
- tests/unit/statistics-step-form.spec.ts
We returned value as string in input number, it should be a number.
Update statics steps because parseInt is not necessary anymore
> fix(ui): component InputNumber return value as number

- playground/app.js
- src/components/stepforms/widgets/DateComponents/NewDateInput.vue
- src/lib/send-analytics.ts
- src/main.ts
- tests/unit/lib/send-analytics.spec.ts
- tests/unit/new-date-input.spec.ts
Add a new util to populate a sendAnalytics method from outside of weaverbird
Add a case in playground for UAT
Use it to send events when user select a variable or advanced variable in NewDateInput
Example in playground with method populated with a console.debug only:
> feat(new-date-input): send analytics event when user select a (advanced or base) variable TCTC-899

- src/components/stepforms/AddTotalRowsStepForm.vue
- src/lib/helpers.ts
- tests/unit/utils.ts
Enable to edit add total steps rows.
Before step was not saved correctly
Before:
After:
> fix(add-total-steps-rows): avoid to submit form before set aggregations new columns is over TCTC-1300

- server/src/weaverbird/backends/pandas_executor/steps/addmissingdates.py
- server/src/weaverbird/backends/pandas_executor/steps/date_extract.py
- server/tests/backends/fixtures/dateextract/after_add_missing_dates_duplicate_values.json
- server/tests/steps/test_addmissingdates.py
This is very edge case found by adding a "missing dates" step with some
duplicate dates but not in the same group.
While fixing this, I noticed that the tests of the dateextract step were not executed because f a filename mismatch! I fixed this in #1226, so this PR needs to be merged first for the test case to be run.
> fix(pandas): some dateextract were failing if some dates were duplicated TCTC-1379

- src/assets/FA-ICONS.ts
- src/components/Pipeline.vue
- src/components/PreviewSourceSubset.vue
- src/components/Step.vue
- stories/step.js
- tests/unit/step.spec.ts
Move subset preview form to domain step rather than pipeline
It is display using a toggle logic
Add specific style to fit design
Design:
Storybook:
> feat(configurable-subset-preview): use correct design TCTC-1339

- src/components/PreviewSourceSubset.vue
to avoid selecting the "domain" step when
modifying or refreshing the preview source subset
> fix(preview source subset): stop click propagation TCTC-1419

- src/components/stepforms/widgets/FilterSimpleCondition.vue
- src/lib/labeller.ts
- tests/unit/labeller.spec.ts
Update labels of from/until operator in filter step when filtering on a date
> feat(filter-step): rename label for from/until date operators TCTC-1443

- src/components/stepforms/FromDateStepForm.vue
- src/components/stepforms/ToDateStepForm.vue
https://toucantoco.atlassian.net/browse/TCTC-1607
Missing translators made it so that some `.find` returned `undefined` and access to `(undefined).label` made everything crash, thus the bug.
This PR adds the missing Mongo 5.0 translator.
> fix: add missing translator to date conversion components [TCTC-1607]

- src/components/stepforms/CumSumStepForm.vue
- tests/unit/cumsum-step-form.spec.ts
The check introduced in #999 / #1246 for mongo translator to be able to handle legacy cumsum step format need the properties 'valueColumn' and 'newColumn' not be present (not just present to undefined) to interpret correctly new steps with the 'toCumSum' attribute.
This PR fixes the format produced by the CumSumStepForm so these two old attributes are not present anymore.
Before:
After:
> fix(ui): cumsumstep migration should delete old properties TCTC-1552

- src/components/QueryBuilder.vue
Before:
After:
When we create a new step we don't entre the editStep method so we don't update backendErrorMessage display.
The only way to hide it is to base our display on if the step is a newly created one or not. So i added a computed for this case.
:information_source: Didn't find a way to test it, feel free to help me on it if you have an idea :pray:
> fix(step): avoid display previous error when creating a new step TCTC-1343

- playground/app.js
- server/src/weaverbird/backends/pandas_executor/steps/utils/combination.py
- server/src/weaverbird/backends/pandas_executor/types.py
- server/src/weaverbird/pipeline/steps/append.py
- server/src/weaverbird/pipeline/steps/domain.py
- server/src/weaverbird/pipeline/steps/join.py
- server/src/weaverbird/pipeline/steps/utils/combination.py
- src/components/QueryBuilder.vue
- src/lib/dereference-pipeline.ts
- src/lib/labeller.ts
- src/lib/steps.ts
- src/lib/templating.ts
- src/lib/translators/mongo.ts
- src/store/actions.ts
- src/store/index.ts
- src/store/mutations.ts
- src/store/state.ts
- tests/unit/labeller.spec.ts
- tests/unit/lib/dereference-pipeline.spec.ts
- tests/unit/mongo.spec.ts
- tests/unit/query-builder.spec.ts
- tests/unit/store.spec.ts
These references will not resolved by weaverbird, but can be used by its host to create dependencies and enable query reuse and factorization.
I've added a few layers of protections to ensure the  (front-end) mongo translator will fail if we ever try to pass references to it. These references are intended to be resolved back-end side.
I the process, I cleaned the way domain was handled in the UI store. (There is no need for it to have a special treatment anymore, and it leads to code simplification/deletion ace6347 )
> feat: domains can be replaced by references to other queries  TCTC-1548

- CHANGELOG.md
- src/lib/backend.ts
- src/store/actions.ts
- tests/unit/store.spec.ts
The "load all values" button bottom of the unique column values list was a lie, it was only loading unique values found in the first 10K rows. Some users noticed dat. Let's fix it !
> fix(ui): trully load all unique column values TCTC-1688

- server/src/weaverbird/backends/sql_translator/steps/append.py
In render's log we have: 
```Jan 25 05:35:10 PM  ... line 3, in <module>    from server.src.weaverbird.backends.sql_translator.steps.utils.query_transformation import (ModuleNotFoundError: No module named 'server'``` 
This PR fixes that.
> fix: fix import path for render

- CHANGELOG.md
- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
Fix a 3 years old but that was messing up some filtering conditions.
Something like `_1_ AND (_2_ OR _2'_) AND (_3_ OR _3'_)` was "simplified" to : 
```
{
$match: {
_1_,
$or: [_3_, _3'_],
},
},
```
instead of 
```
{
$match: {
_1_,
$and: [
{ $or: [_2_, _2'_],},
{ $or: [_3_, _3'_], },
],
},
},
```
I also checked the WIP Mongo Translator implem in Python and the bug does not exist there as the "and condition simplifier" have not been ported to (which is probably a good choice I guess :sweat_smile:).
Original JS : 
https://github.com/ToucanToco/weaverbird/blob/48616a39726b41b3d65e3d82396020577730b215/src/lib/translators/mongo.ts#L2072-L2076
Python version : 
https://github.com/ToucanToco/weaverbird/blob/48616a39726b41b3d65e3d82396020577730b215/server/src/weaverbird/backends/mongo_translator/st …
> fix(mongo translator): do not simplify multiple "or" in a "and" conditions TCTC-1467

- src/components/DataViewer.vue
Adds a data-cy attribute for an element, used in the new Cypress test TCTC-191.
No further impact.
> chore: data-cy for TCTC-191

- server/src/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
- server/tests/steps/sql_translator/utils/test_query_transformation.py
A pipeline with a filter step using the 'in' operator but with a single value like `column='origin', operator='in', value=['france']` was translated to `WHERE origin IN ('france',)` instead of `WHERE origin IN ('france')` (notice the useless trailing comma that's invalid SQL).
> fix(sql): inclusion condition with a single value TCTC-1605

- playground/app.js
- server/playground.py
Playground was not displaying errors by step (for pandas executor)
> fix(playground): display step errors

- server/src/weaverbird/backends/pandas_executor/steps/todate.py
- server/tests/backends/fixtures/todate/from_integer_year.json
- server/tests/steps/test_todate.py
- src/components/DataTypesMenu.vue
- src/lib/translators/mongo4.ts
- tests/unit/data-types-menu.spec.ts
- tests/unit/mongo.spec.ts
Avoid to have error when trying to convert a year in int to a date.
Before:
We convert to date using convert step it results to an error because translators are not abled to transform a int to a date (it think that it is a timestamp)
After:
We convert to date using to date step (same behaviour than for str columns conversion). We add an automatic str conversion in pandas and mongo translator to transform int year to str before casting to date
> fix(convert-int-to-date): enable to convert year in int to date from types menu [TCTC-1895]

- server/src/weaverbird/backends/mongo_translator/steps/todate.py
- server/tests/backends/fixtures/todate/str_as_year_with_automatic_guess.json
- src/lib/translators/mongo4.ts
- tests/unit/mongo.spec.ts
This was working with the TypeScript implementation, so I added a test case and supported it in python one.
Also include a small fix to handle cases where years are in type "long" and not "int"
> fix(mongo): support years as strings in python implem TCTC-1831

- server/src/weaverbird/backends/mongo_translator/steps/__init__.py
- server/src/weaverbird/backends/mongo_translator/steps/convert.py
- server/tests/backends/fixtures/convert/snowflake.json
- server/tests/backends/fixtures/convert/to_bool.json
- server/tests/backends/fixtures/convert/to_datetime.json
- server/tests/backends/fixtures/convert/to_datetime_from_timestamp.json
- server/tests/backends/fixtures/convert/to_float.json
- server/tests/backends/fixtures/convert/to_integer.json
- server/tests/backends/fixtures/convert/to_integer_from_datetime.json
- server/tests/backends/fixtures/convert/to_integer_only_floats.json
- server/tests/backends/fixtures/convert/to_integer_only_strings.json
- server/tests/backends/fixtures/convert/to_text.json
- server/tests/backends/mongo_translator/test_mongo_translator_steps.py
Translates the concatenate step from `../src/lib/translators/mongo.ts`
:warning: I had to handle some edge cases in order to make it iso with the pandas executor. There are probably still missing cases because type conversion in mongo and pandas have different rules. I also fear that adding these edge cases might decrease performances.
> feat(mongo_translator): Implemented convert step [TCTC-1832]

- server/src/weaverbird/backends/mongo_translator/steps/__init__.py
- server/src/weaverbird/backends/mongo_translator/steps/delete.py
- server/tests/backends/fixtures/delete/simple.json
Implemented the delete step in python for the mongo-translator, following the logic from `./src/lib/translators/mongo.ts`
> feat(python-mongo-translator): delete step [TCTC-2656]

- server/src/weaverbird/backends/mongo_translator/steps/__init__.py
- server/src/weaverbird/backends/mongo_translator/steps/split.py
- server/tests/backends/fixtures/split/simple.json
Implemented the split step in python for the mongo-translator, following the logic from `./src/lib/translators/mongo.ts`
> feat(mongo-translator): added split step [TCTC-2657]

- server/tests/backends/fixtures/convert/to_bool.json
- server/tests/backends/fixtures/convert/to_text.json
- server/tests/backends/mongo_translator/test_mongo_translator_steps.py
This ensures the following:
* null booleans are kept null rather than being converted to False by pandas (allow our tests
to really check nulls)
* NaTs are converted to None (NaTs make pymongo fail)
* null strings are None rather than NaNs, which get stored in mongo as the litteral "nan" rather than
null
> fix(tests/mongo_translator): Sanitize pandas dataframes before inserting them into mongo TCTC-2688

- server/src/weaverbird/backends/mongo_translator/steps/__init__.py
- server/src/weaverbird/backends/mongo_translator/steps/duplicate.py
- server/tests/backends/fixtures/duplicate/simple.json
Implemented the duplicate step in python for the mongo-translator, following the logic from `./src/lib/translators/mongo.ts`
> feat(python-mongo-translator): added duplicate step [TCTC-2657]

- server/src/weaverbird/backends/mongo_translator/steps/__init__.py
- server/src/weaverbird/backends/mongo_translator/steps/addmissingdates.py
- server/src/weaverbird/backends/mongo_translator/steps/date_extract.py
- server/src/weaverbird/pipeline/steps/addmissingdates.py
- server/tests/backends/fixtures/dateextract/after_add_missing_dates_duplicate_values.json
- server/tests/backends/fixtures/dateextract/legacy_config.json
- server/tests/backends/fixtures/dateextract/legacy_config_without_column.json
- server/tests/backends/fixtures/dateextract/mongo_all_cases.json
`addmissingdates` was required by test fixtures.
Note that this only targets mongo 5.
Note that the behvaiour here is ISO with the mongo translator, BUT there are few issues/inconsistencies that would need to be adressed imo:
-  mongo's `$week` operator returns the week of the year for a date, starting at 0 (ending at 52, included). Other backends (and the commonly used form) start at 1 and end at 53. Maybe this should be adressed later on to be consistent throughout all backends ?
- Several steps using mongo's `$switch` statements have a weird behaviour with null values: Since `{$lte:  [null, anyPositiveInteger]}` is `true` in mongo 5, we get `1` for `quarter` with `null`, `4` for `previousQuarter` and so on... This could probably easily be fixed by checking first if the value is not …
> Mongo translator: implement `addmissingdates` and `dateextract` steps TCTC-2491

- server/src/weaverbird/backends/mongo_translator/steps/__init__.py
- server/src/weaverbird/backends/mongo_translator/steps/evolution.py
- server/tests/backends/fixtures/evolution/abs_nogroups.json
- server/tests/backends/fixtures/evolution/perc_groups_mongo.json
- server/tests/backends/fixtures/evolution/perc_nogroups.json
Implemented the evolution step in python for the mongo-translator, following the logic from `./src/lib/translators/mongo.ts`
⚠️ However am facing a difference behaviour between results from pandas <> mongo when it comes to group, that's why i added a new group fixture only reserved to mongo, not sure if am missing something somewhere or it should behave like that 🤔 .
> feat(python-mongo-translator): evolution step [TCTC-2657]

- server/src/weaverbird/backends/pandas_executor/steps/statistics.py
- server/tests/backends/fixtures/statistics/all.json
By default, pandas normalizes 'var' and 'std' by 1, which is unexpected behaviour and
inconsistent with mongo. This fixes this behaviour.
closes #1323
> fix(backend/pandas_executor): Do not normalize standard deviation and variance in statistics step TCTC-2701

- server/src/weaverbird/backends/mongo_translator/steps/__init__.py
- server/src/weaverbird/backends/mongo_translator/steps/comparetext.py
- server/tests/backends/fixtures/comparetext/simple.json
Implemented the comparetext step in python for the mongo-translator, following the logic from `./src/lib/translators/mongo.ts`
> feat(python-mongo-translator): comparetext step [TCTC-2695]

- playground/datastore/revenue-product-dataset.json
- playground/init-mongo/01-import-files.sh
- playground/init-mongo/02-adjust-types.js
Just added a good dataset to be able to well test the waterfall Step on python mongo translator
PS: this new dataset is comming from a fixture `waterfall/with_groups.json` **AND**, i converted the YEAR column to text first for the waterfall to work !
> feat(python-mongo-translator): new dataset to test the waterfall step on the playground [TCTC-2695]

- server/setup.cfg
- server/src/weaverbird/pipeline/steps/cumsum.py
- server/tests/steps/test_cumsum.py
We need to handle `valueColumn` as well as `value_column` for cumsum step.
> chore(server): handle cumsum legacy syntax aliases

- CHANGELOG.md
- package.json
- server/CHANGELOG.md
- server/setup.cfg
- server/src/weaverbird/backends/mongo_translator/utils.py
- server/tests/backends/fixtures/ifthenelse/dates-conditions.json
- server/tests/utils.py
- sonar-project.properties
- src/lib/translators/mongo.ts
- tests/unit/mongo.spec.ts
$match and $cond doesn't function extacly the same way: $cond takes an
expression while $match only a filter. Therefore, in $match, we need to
wrap some stuff with $expr, but not with $cond.
Added a fixture to test this behavior for mongo and pandas backends
> fix(mongo): remove $expr wrapping for ifthenelse condtions  TCTC-2118

- server/CHANGELOG.md
- server/setup.cfg
- minor bump for logs on each pandas step
> chore: bump weaverbird from 0.12.2 to 0.12.3

- server/CHANGELOG.md
- server/src/weaverbird/backends/pandas_executor/steps/delete.py
- server/src/weaverbird/backends/sql_translator/metadata.py
- server/tests/backends/fixtures/delete/non_existing_column.json
- server/tests/backends/sql_translator/test_metadata.py
- server/tests/steps/sql_translator/test_delete.py
- server/tests/test_pipeline_executor.py
To prevent getting errors in pipelines executed with the pandas backend when unused columns have been deleted.
This should already be the case for mongo and SQL backends.
> feat(pandas): delete step should not fail on non-existing cols

- server/src/weaverbird/backends/pandas_executor/geo_utils.py
- server/src/weaverbird/backends/pandas_executor/steps/dissolve.py
- server/tests/backends/pandas_executor/test_pandas_executor_steps.py
Since the contract of steps is to receive and emit DataFrames (and not GeoDataFrames),
fix the df_to_geodf method. Also update the pandas executor tests to provide a DataFrame rather
than a GeoDataFrame in case a geo step is tested.
> fix(server/pandas): Fix df_to_geodf

- server/src/weaverbird/backends/pandas_executor/steps/dissolve.py
- server/src/weaverbird/pipeline/steps/dissolve.py
- server/tests/backends/fixtures/dissolve/pandas_no_aggs.json
In case one want to dissolve without aggregations, all columns which aren't a group nor the 'geometry'
column are dropped.
> refactor(server/pandas/dissolve): Allow to use dissolve without aggregations

- server/src/weaverbird/backends/pypika_translator/translate.py
I think we should have a `Pipeline` type instead of `PipelineWithVariables` in `pypika_translator`'s `translate_pipeline` method as we expect the `pipeline` to be rendered when translating the query.
> chore: pypika translate typing

- server/src/weaverbird/backends/pypika_translator/dialects.py
- server/src/weaverbird/backends/pypika_translator/translators/postgresql.py
- server/tests/backends/sql_translator/test_sql_postgres_pypika_translator_steps.py
use `postgres` instead of `postgresql` to be consistent with backend
> chore: rename postgres dialect

- server/poetry.lock
Some bumping on the lock file
Package operations: 1 install, 14 updates, 0 removals
• Updated botocore (1.27.13 -> 1.27.17)
• Updated numpy (1.22.4 -> 1.23.0)
• Updated boto3 (1.24.13 -> 1.24.17)
• Updated pandas (1.4.2 -> 1.4.3)
• Updated backoff (1.11.1 -> 2.1.2)
• Updated pycryptodomex (3.14.1 -> 3.15.0)
• Updated tabulate (0.8.9 -> 0.8.10)
• Updated awswrangler (2.15.1 -> 2.16.0)
• Updated snowflake-connector-python (2.7.8 -> 2.7.9)
• Updated sqlalchemy (1.4.37 -> 1.4.39)
• Updated numexpr (2.8.1 -> 2.8.3)
• Installed psycopg (3.0.15)
• Updated pytest-mock (3.7.0 -> 3.8.1)
• Updated toucan-connectors (3.11.1 -> 3.14.0)
• Updated types-python-dateutil (2.8.17 -> 2.8.18)
> deps: poetry lock update

- server/tests/backends/sql_translator_integration_tests/test_sql_redshift_translator_steps.py
a `beers_tiny` dataset was inserted into the redshift test cluster to be used for integration tests.
> chore: enable redshift integration tests

- server/src/weaverbird/backends/pypika_translator/translators/base.py
- server/tests/backends/fixtures/formula/special_brackets_pypika.json
fix the regex on formula step for weird edge cases such as : 
```
'cost' - (price_per_l / [ cost]) + (`price_per_l` / 0) / ("price_per_l" + [ volume_ml  ])
```
PS :  a work on AST for our formulas is ongoing and this sanitizer may be removed, but for now we need it !
> feat: optimize regex on formula step for edge cases

- src/components/Step.vue
- src/lib/labeller.ts
- src/lib/matcher.ts
- src/store/mutations.ts
- src/store/state.ts
- tests/unit/labeller.spec.ts
- tests/unit/step.spec.ts
- tests/unit/store.spec.ts
Retrieve the name of the query referenced behind uid in domain step label
Before:
After:
> feat(domain-step): enable to label domain step with query name when query is referenced behind an uid [TCTC-3100]

- server/tests/backends/sql_translator_integration_tests/test_sql_athena_translator_steps.py
This doubles the speed of tests (CTAS is recommended for big results only)
> fix(server/tests/athena): Disable CTAS for athena

- CHANGELOG.md
- build-types.sh
- jest.config.js
- package.json
- rollup.config.js
- sonar-project.properties
- src/main.ts
- src/types.ts
- tsconfig.json
- tsconfig.types.json
https://toucantoco.atlassian.net/browse/TCTC-3320
https://github.com/ToucanToco/tucana/pull/12553
Weaverbird is fully written in TS but didn't export type definitions, which frequently broke Tucana and other dependent packages. This PR adds a build script to generate type definitions to resolve this.
Before:
:x: no type defs, usual workaround in Tucana was to ts-ignore imports
:x: type errors not prevented
After:
:heavy_check_mark: type defs of imports
:heavy_check_mark: error prevention
I first wanted to use rollup-plugin-dts, but it turned out that it required the latest rollup, the latest version of rollup plugins, the latest typescript, and after all these updates and many fixes in the code itself, the build was broken, likely due to a rollup error
```console …
```
> chore: build and export types [TCTC-3320]

- server/poetry.lock
- server/pyproject.toml
- server/src/weaverbird/backends/mongo_translator/mongo_pipeline_translator.py
- server/src/weaverbird/backends/mongo_translator/steps/ifthenelse.py
- server/src/weaverbird/pipeline/steps/percentage.py
- chore: added a missing type for pipeline_to_translate for mongo
- deps: bumping libs:
- Implicit bumps (transient):
- urllib3 (1.26.9 -> 1.26.11)
- botocore (1.27.21 -> 1.27.46)
- frozenlist (1.3.0 -> 1.3.1)
- attrs (21.4.0 -> 22.1.0)
- googleapis-common-protos (1.56.3 -> 1.56.4)
- grpcio (1.47.0 -> 1.48.0)
- numpy (1.23.0 -> 1.23.1)
- rsa (4.8 -> 4.9)
- yarl (1.7.2 -> 1.8.1)
- boto3 (1.24.21 -> 1.24.46)
- google-auth (2.9.0 -> 2.9.1)
- grpcio-status (1.47.0 -> 1.48.0)
- requests (2.27.1 -> 2.28.0)
- gremlinpython (3.6.0 -> 3.6.1)
- typing-extensions (4.2.0 -> 4.3.0)
- coverage (6.4.1 -> 6.4.2)
- google-cloud-bigquery-storage (2.13.2 -> 2.14.1)
- google-cloud-core (2.3.1 -> 2.3.2)
- mccabe (0.6.1 -> 0.7.0)
- pycodestyle (2.7.0 -> 2.9.1)
- pyflakes (2.3.1 -> 2.5.0)
- Explicit bumps:
- …
> chore: missing typing + deps bumping

- server/src/weaverbird/backends/pypika_translator/translate.py
- server/src/weaverbird/backends/pypika_translator/translators/base.py
- server/tests/backends/sql_translator_unit_tests/test_base_translator.py
This option will be useful to preview the result of complex queries on a subset of the source dataset (e.g when a table has 10M rows and you want to preview your transformations on 10k rows).
> feat(sql): add source_rows_subset option on translate sql

- playground/app.js
- src/lib/backend.ts
- src/store/actions.ts
- src/store/state.ts
- tests/unit/store.spec.ts
As now translator is retrieved from execute pipeline backendResponse in meta, we can add it to store directly from executePipeline call, no need to retrieve it from Tucana
Tucana PR to clean logic: https://github.com/ToucanToco/tucana/pull/12759
> feat(backend-service): retrieve translator from execute pipeline meta [TCTC-3370]

- server/poetry.lock
- server/pyproject.toml
- bump geopandas to 0.11.1
- bump toucan-connectors to 3.21.1
- We need to bump geopandas tobe able to bump peakina on the backend !
> chore: bump toucan-connectors to 3.21.1 and geopandas to 0.11.1

- src/directives/resizable/ResizableTable.ts
- src/directives/resizable/resizable.ts
- tests/unit/resizable.spec.ts
Quickfix to add a new maxHandleableColumns to v-resizable directive to be able to disable it with large amount of columns.
Do not merge until we know if merge on master or not: (this branch is plugged on v0.89.0 release for now) in order to be able to create a v0.89.1 if we need to target monthly directly
> fix(resizable-columns): disable directive when columns count is too big [TCTC-3887]

- server/CHANGELOG.md
- server/src/weaverbird/backends/pypika_translator/translators/athena.py
- server/src/weaverbird/backends/pypika_translator/translators/base.py
- server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
- server/src/weaverbird/backends/pypika_translator/translators/mysql.py
- server/tests/backends/fixtures/split/with_delimiter_pypika.yaml
The separator should be escaped as a string literal (single quotes).
relates to TCTC-3806
> fix(server/pypika/gbq): Fix split step quoting TCTC-3806

- server/src/weaverbird/backends/pypika_translator/translators/base.py
- server/tests/backends/fixtures/filter/notmatches_pypika.yaml
- server/tests/backends/sql_translator_unit_tests/test_filter_translators.py
> fix(server/pypika/filter): Fix "notmatches" operator for backends using REGEXP

- server/CHANGELOG.md
- server/src/weaverbird/backends/pypika_translator/translators/base.py
- server/src/weaverbird/backends/pypika_translator/translators/mysql.py
- server/src/weaverbird/pipeline/steps/text.py
- server/tests/backends/fixtures/text/simple.json
- server/tests/backends/fixtures/text/simple_pypika.json
- server/tests/backends/mongo_translator/test_mongo_translator_steps.py
- server/tests/backends/pandas_executor/test_pandas_executor_steps.py
- server/tests/backends/sql_translator_integration_tests/test_sql_athena_translator_steps.py
- server/tests/backends/sql_translator_integration_tests/test_sql_bigquery_translator_steps.py
- server/tests/backends/sql_translator_integration_tests/test_sql_mysql_translator_steps.py
- server/tests/backends/sql_translator_integration_tests/test_sql_postgres_translator_steps.py
- server/tests/backends/sql_translator_integration_tests/test_sql_redshift_translator_steps.py
- server/tests/backends/sql_translator_integration_tests/test_sql_snowflake_translator_steps.py
- server/tests/backends/sql_translator_unit_tests/test_base_translator.py
- server/tests/conftest.py
- server/tests/steps/test_text.py
**Before** : textstep can add columns of type string, only
**After** : other types are allowed. Useful when using variables like : 
```
{
"name": "text",
"new_column": "current_date",
"text": "{{ TODAY }}"
},
```
:information_source: since we only deal with `datetime` variables (and not `date`) in laputa, and since mongo doesnt have distinct types, I chose to only handle `datetime` type
> feat(textstep): allow to create columns of other types [TCTC-4365]

- server/CHANGELOG.md
- server/pyproject.toml
Major bump from 0.25.5 to 0.26.0:
- Dropped the support of the old sql-translator
- Added a custom queryBuilder for snowflake for columns having specials characters
- Added `replacetext` step for all our backends
- allow to create columns of other types
> chore: bump v0.26.0

- server/src/weaverbird/pipeline/steps/__init__.py
- server/src/weaverbird/pipeline/steps/customsql.py
- server/tests/test_pipeline.py
This PR doesnt change existing behaviour since CustomSqlStepWithVariables was not part of the union PipelineStepWithVariables ; but we want to make sure this is done on purpose.
> chore: prevent CustomSqlStepWithVariables

- server/src/weaverbird/pipeline/steps/replacetext.py
- src/components/constants.ts
- src/components/stepforms/ReplaceTextStepForm.vue
- src/components/stepforms/index.ts
- src/components/stepforms/schemas/index.ts
- src/components/stepforms/schemas/replaceText.ts
- src/lib/labeller.ts
- src/lib/steps.ts
- src/lib/templating.ts
- src/lib/translators/base.ts
- src/lib/translators/mysql.ts
- src/lib/translators/pandas-no_joins.ts
- src/lib/translators/pandas.ts
- src/lib/translators/pypika.ts
- tests/unit/labeller.spec.ts
- tests/unit/replace-text-step-form.spec.ts
- tests/unit/store.spec.ts
- tests/unit/templating.spec.ts
> feat(front): Implement front-end for replacetext step TCTC-4368

- .github/workflows/ci-ui.yml
- .github/workflows/npm-publish.yml
- Dockerfile
- README.md
The CI/CD is blocked by the version of node it uses (too old for dependencies that we just upgraded).
https://github.com/ToucanToco/weaverbird/actions/runs/3384849837/jobs/5622306593
> chore(front): upgrade node to LTS (v18)

- src/components/DataViewer.vue
- src/lib/dataset/index.ts
- src/lib/dataset/pandas.ts
- tests/unit/data-viewer.spec.ts
Use map icon when column type is geometry
Before
After
> feat(data-viewer): use map icon when column type is geometry [TCTC-4376]

- ui/.eslintrc.js
- ui/.storybook/main.ts
- ui/CHANGELOG.md
- ui/package.json
- ui/sonar-project.properties
- ui/src/components/stepforms/widgets/DateComponents/TabbedRangeCalendars.vue
- ui/src/components/stepforms/widgets/FilterSimpleCondition.vue
- ui/tests/unit/filter-simple-condition-widget.spec.ts
- ui/tests/unit/filter-step-form.spec.ts
- ui/tests/unit/ifthenelse-step-form.spec.ts
- ui/yarn.lock
For an unknown reason, the default value of a prop seemed never applied.
We found some issues about this in vue-class-component's repo, but non e of the solutions worked.
So I switched to `defineComponent`, which works like a charm.
> test(ui): fixes default values not set TCTC-4635

- server/src/weaverbird/backends/pypika_translator/translators/base.py
- server/tests/backends/fixtures/filter/matches_with_float_pypika.yaml
- server/tests/backends/fixtures/filter/notmatches_with_float_pypika.yaml
- server/tests/backends/sql_translator_unit_tests/test_filter_translators.py
Without this, it is not possible to use the matches/notmatches operator on non-text columns
> fix(server/pypika/filter): Ensure column to match with a regex is first casted to text

- CHANGELOG.md
- package.json
- sonar-project.properties
Fix comming from : https://github.com/ToucanToco/weaverbird/pull/1633
> chore: bump weaverbird ui from 0.92.1 to 0.92.2

- server/CHANGELOG.md
- server/src/weaverbird/backends/mongo_translator/steps/fromdate.py
- server/src/weaverbird/backends/mongo_translator/steps/todate.py
- server/tests/backends/fixtures/fromdate/simple_with_null.json
* fix: added a default on switch
* chore: added a entry to the changelog
* test: some fixtures with null in dataset
* feat: restore the old fixture
* feat: added a new fixture for the fix that handle nulls on weird formats
> fix(server): date as null default on switch to prevent PlanExecutor error [TCTC-4622] (#1632)

- server/CHANGELOG.md
- server/src/weaverbird/backends/pandas_executor/steps/addmissingdates.py
- server/tests/backends/fixtures/addmissingdates/simple.json
- server/tests/backends/fixtures/addmissingdates/simple_with_tz.yaml
- server/tests/steps/test_addmissingdates.py
Before this change, in case we had timezone-aware series, inserting the start of a period (naive) would result in an integer (representing a unix timestamp in nanoseconds). The resulting series would end up being a mix of tz-aware timestamp objects and integers (for naive inserted dates).
This ensures that inserted objects are properly localized if required.
closes TCTC-4429
> [cherry-pick] fix(backend/pandas/addmissingdates): Ensure we always insert pd.Timestamp objects (#1644)

- ui/CHANGELOG.md
- ui/package.json
- ui/sonar-project.properties
- ui/src/components/Popover.vue
- ui/src/components/domutil.ts
- ui/src/components/stepforms/widgets/DateComponents/NewDateInput.vue
- ui/tests/unit/domutil.spec.ts
The Popover was overflowing the window, so we couldn't click on the bottom buttons
Before
https://user-images.githubusercontent.com/18734475/207180976-41706956-b73e-41d9-a576-898c13accadd.mp4
After
https://user-images.githubusercontent.com/18734475/207180990-b5657c32-b5f4-409d-b423-848d13fe1045.mp4
ℹ️ I add a prop `shouldCalculateHeight` prop set to false by default to prevent to break other components that are using Popover.
> fix(new-date-input): popover position [TCTC-4324]

- ui/src/components/Step.vue
- ui/src/lib/labeller.ts
- ui/src/store/mutations.ts
- ui/src/store/state.ts
- ui/tests/unit/step.spec.ts
- ui/tests/unit/store.spec.ts
We will need to retrieve domain name for uid on a model that can be different than {type: 'ref', uid: xxx}, i thought than it won't be very impacting on performances to check if a domain (even only a string) is referencing as an uid into the list of availableDomains (previously queries but renamed because it could be other things than queries). This way if we find a reference as uid in the list we will use the domain instead, we always suppose that the domain can be an uid, even if it is only a string.
> feat(labeller): rename queries to availableDomains [TCTC-4877]

- server/CHANGELOG.md
- server/src/weaverbird/backends/pandas_executor/steps/evolution.py
- server/tests/steps/test_evolution.py
> fix(backend/pandas): Convert target columns to timestamps before operating on them in evolution step TCTC-4826

- server/CHANGELOG.md
- server/src/weaverbird/backends/pandas_executor/steps/duration.py
- server/tests/steps/test_duration.py
> fix(backend/pandas): Convert target columns to timestamps before operating on them in duration step TCTC-4823

- server/src/weaverbird/backends/mongo_translator/steps/aggregate.py
- server/tests/backends/fixtures/aggregate/first_with_special_column_name.json
- server/tests/backends/fixtures/aggregate/first_with_special_column_name_mongo.json
_id is reserved by mongo. Thus, we cannot overwrite it
> fix(backend/mongo/aggregate): Rename `_id` to `__id` in case it's part of an aggregation's new columns

- server/CHANGELOG.md
- server/pyproject.toml
- server/src/weaverbird/backends/mongo_translator/steps/aggregate.py
- server/tests/backends/fixtures/aggregate/first_with_special_column_name_mongo.json
_id is reserved by mongo. Thus, we cannot overwrite it
> [backport] fix(backend/mongo/aggregate): Rename _id to __id in case it's part of an aggregation's new columns

- ui/src/components/stepforms/widgets/Autocomplete.vue
- ui/src/components/stepforms/widgets/DateComponents/NewDateInput.vue
- ui/src/components/stepforms/widgets/DateComponents/RelativeDateForm.vue
- ui/stories/dates/RelativeDateForm.stories.ts
- ui/tests/unit/autocomplete-widget.spec.ts
The bottom of the relative date dropdown was hidden
- Fix the overflow
- Improve design
- Add title attribute for long labels
When this PR will be OK, I will open a duplicate one for the release 0.92
Before
After
> fix(new-date-input): show all options for relative date dropdown [TCTC-3428] [TCTC-2484]

- ui/src/components/stepforms/widgets/Autocomplete.vue
- ui/src/components/stepforms/widgets/DateComponents/RelativeDateForm.vue
Fix the fix 😅 
A bug occurs in some cases with multiselect in the date popover.
Indeed, sometimes the dropdown was overflowing the popover, so we can't see the end of its content.
It happens because VueMultiselect appends the dropdown next to the triggerer, instead of into the body. But the height calculation is bases on the window height... And the library doesn't provides any props to set another parent.
Quick win approach was to fix the dropdown max-height or remove the overflow hidden to let the dropdown overflow the popover.
First I thought the fixed max-height solution will not work because sometimes the popover is resized when not enough space, but in fact when it happens, we don't have the bug, because the bottom of the screen is reached so multiselect height is good :)
A big …
> fix(new-date-input): show all options for relative date dropdown (2nd fix) [TCTC-3428] [TCTC-2484] 

- ui/src/store/state.ts
We need a default value for available variables otherwise it's no well set on init setupVQBStore hook
> fix(store): use default value for available variables [TCTC-5196]

- ui/src/components/stepforms/widgets/CodeEditorWidget.vue
There is a strange issue with @Watch decorator and rollup that causes input event to not bubble.
We remove v-model to use simple input value logic instead
> feat(code-editor-widget): remove watch flacky logic [TCTC-6012]

- server/src/weaverbird/pipeline/pipeline.py
- server/tests/test_pipeline.py
This is a POC for skipping considering a filter step that may contain as value "__VOID__" to be able to still,
on an AND, OR, or simple filter condition type.
Resolves: TCTC-5480
> feat: avoid filter step having __VOID__ in it (AND, OR or simple condition) recursivelly [TCTC-5480, TCTC-6102]

- server/src/weaverbird/backends/pypika_translator/translators/base.py
- server/tests/backends/sql_translator_unit_tests/test_base_translator.py
- server/tests/backends/sql_translator_unit_tests/test_snowflake_translator.py
We need to cast to integer all "date extraction" like we did here for pandas executor : https://github.com/ToucanToco/weaverbird/pull/1777
This will be backported on master
> feat(nativeSQL): we want to cast to integer a column resulting from a date extract

- ui/src/components/Step.vue
- ui/src/store/actions.ts
- ui/src/store/state.ts
- ui/tests/unit/step.spec.ts
- ui/tests/unit/store.spec.ts
In some cases, the domain name can refers to something else than one of the available datasets provided to weaverbird. To enable to display correct name for used source, we enable to override labeller default method using a 'customRetrieveDomainName' method from store state.
> feat(labeller): enable to override retrieveDomainName by passing a custom method to store state

- server/CHANGELOG.md
- server/src/weaverbird/backends/mongo_translator/steps/filter.py
- server/tests/backends/mongo_translator/steps/test_filter.py
On "Match Pattern", we want a case insensitive for mongo filter step
By adding the "$options" "I" on filter step for mongo
> fix: add case insensitive on matches/notmatches filter steps [TCTC-6338]

- server/CHANGELOG.md
- server/src/weaverbird/pipeline/pipeline.py
- server/tests/test_pipeline.py
While cleaning `__VOID__` from a mongo pipeline, we introduced a regression [HERE](https://github.com/ToucanToco/weaverbird/pull/1797) because we were removing also normal/casual `$ne/$eq` direct isnull/isnotnull values from filter condition,.
This PR is to isolate those specific cases and adapt the test for the fix.
> fix: keep None/null on $ne and $eq direct value to fix isnull/isnotnull filter step condition for mongo [TCTC-6339]

- server/src/weaverbird/pipeline/references.py
- server/src/weaverbird/pipeline/steps/append.py
- server/src/weaverbird/pipeline/steps/domain.py
- server/src/weaverbird/pipeline/steps/join.py
- server/src/weaverbird/pipeline/steps/utils/combination.py
- server/tests/pipeline/test_references.py
We need to plan the case when a reference is not returned. This cas is not OK when it's the Domain step of the main pipeline, but it's fine when it's a sub-pipeline (meaning it just should be ignored).
> feat(server): handle unresolved references TCTC-6355

- server/CHANGELOG.md
- server/src/weaverbird/pipeline/pipeline.py
- server/tests/test_pipeline.py
While removing __VOID__ from mongo pipeline, we were also removing key/value with empty list or empty dict !
But after some investigations, we noticed that some steps like the `rank` needs some of it keys to be empty such as `'a':[]` or `pipeline:[]`
In this example :
```
[
{"$match": {"domain": "cars"}},
{"$sort": {"color": 1}},
{"$group": {"_id": None, "_vqbArray": {"$push": "$$ROOT"}}},
{
"$project": {
"_vqbSortedArray": {
"$let": {
"vars": {
"reducedArrayInObj": {
"$reduce": {
"input": "$_vqbArray",
"initialValue": {
"a": [],
"order": 0,
"prevValue": None,
"prevRank": None,
},
"in": {
"$let": {
"vars": {
"order": {
"$cond": [
{
"$ne": [
"$$this.color",
"$$value.prevValue",
]
},
{"$add": ["$$value.order", 1]},
"$$value.order",
]
},
"rank": {
"$cond": [
{
"$ne": [
"$$this.color", …
```
> fix: keep empty list to make mongo steps still working as before [TCTC-6370]

- server/src/weaverbird/backends/pypika_translator/translators/base.py
- server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
- server/tests/backends/sql_translator_unit_tests/test_google_big_query.py
> fix: escape properly column names on GBQ [TCTC-6519]

- server/CHANGELOG.md
- server/src/weaverbird/backends/pypika_translator/translators/base.py
- server/src/weaverbird/backends/pypika_translator/utils/formula.py
- server/tests/backends/fixtures/ifthenelse/number_values.json
- server/tests/backends/fixtures/ifthenelse/number_values_pypika.json
I noticed that ifthenelse steps with numbers as results were not accepted by the Pypika translators with the following errors: `('Could not translate parameters to a SQL query', AttributeError("'int' object has no attribute 'encode'"))``
Example of such a step:
```js
{
name: 'ifthenelse',
if: { column: 'order', operator: 'eq', value: 'first' },
then: 0,
else: {
if: { column: 'order', operator: 'eq', value: 'second' },
then: 1,
else: {
if: { column: 'order', operator: 'eq', value: 'third' },
then: 2,
else: 3,
},
},
newColumn: 'order',
}
```
> fix(sql): if then else step can accept numerical values

- server/CHANGELOG.md
- server/src/weaverbird/backends/pypika_translator/operators.py
- server/src/weaverbird/backends/pypika_translator/translators/athena.py
- server/src/weaverbird/backends/pypika_translator/translators/base.py
- server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
- server/src/weaverbird/backends/pypika_translator/translators/postgresql.py
- server/src/weaverbird/backends/pypika_translator/translators/redshift.py
- server/tests/backends/fixtures/fromdate/day_longmonth_year_space_pypika.yaml
- server/tests/backends/fixtures/fromdate/day_shortmonth_year_dash_pypika.yaml
- server/tests/backends/fixtures/fromdate/day_shortmonth_year_space_pypika.yaml
- server/tests/backends/fixtures/fromdate/longmonth_year_space_pypika.yaml
- server/tests/backends/fixtures/fromdate/shortmonth_year_dash_pypika.yaml
- server/tests/backends/fixtures/fromdate/simple_pypika.yaml
- server/tests/backends/sql_translator_unit_tests/test_adapt_date_format.py
Work items:
* Duplicated all existing fixtures for PyPika translators. Ensure formattings are the same across all
PyPika backends.
* Postgres: Do not pad Months to 9 chars
* Athena: Set FROM_DATE_OP to an existing function
* GBQ: Implement a FORMAT_DATE function (neither DATE_FORMAT nor TO_CHAR are supported)
* Redshift: Make formatting consistent with other backends
> fix(server/pypika): Various improvements on the fromdate step TCTC-6156

- playground/dist/app.js
- ui/Playground.vue
- ui/src/components/stepforms/widgets/FilterSimpleCondition.vue
- ui/src/store/state.ts
- ui/tests/unit/filter-simple-condition-widget.spec.ts
- Removing the `RELATIVE_DATE_FILTERING` feature flag that was only used in the `FIlterSimpleCondition` component and was preventing the display of the right operators when having a `dateTime` column selected. 
- Remove related code since this was the only place where the FF was used.
> fix(ui): remove relative date filtering feature flag and related code [TCTC-6755]

- server/CHANGELOG.md
- server/src/weaverbird/backends/mongo_translator/steps/waterfall.py
- server/src/weaverbird/backends/pandas_executor/steps/waterfall.py
- server/tests/backends/fixtures/waterfall/simple.json
- server/tests/backends/fixtures/waterfall/with_aggregation.json
- server/tests/backends/fixtures/waterfall/with_backfill.yaml
- server/tests/backends/fixtures/waterfall/with_groups.json
- server/tests/backends/fixtures/waterfall/without_backfill.yaml
- server/tests/steps/test_waterfall.py
Rather than having both milestones as the last elements, the first milestone is now the first element,
and the last one is the last element
> fix(server/waterfall): Make the first milestone the first element of the dataset

- ui/package.json
The engine field is used to specify which node version should be used to _use_ the package, not to _build_ it.
Once built, the engine required is actually a browser :joy:
I removed this field, so that dependent packages could choose which node version they should use. They will use the pre-built js files from weaverbird anyway, without the need to build them again.
> chore(ui): remove engine

- server/CHANGELOG.md
- server/src/weaverbird/backends/pypika_translator/translators/base.py
- server/src/weaverbird/pipeline/steps/customsql.py
- ui/src/components/stepforms/CustomSqlStepForm.vue
- ui/src/components/stepforms/schemas/customsql.ts
- ui/src/lib/steps.ts
Avoid to rely on a `__custom_sql_table__`, which would be overridden when there is multiple customsql steps
> feat(sql): customsql step can contains a column list TCTC-7280

- ui/src/components/stepforms/widgets/FilterSimpleCondition.vue
- ui/tests/unit/filter-simple-condition-widget.spec.ts
Display all variables, not only date once for date column in filter editor.
Before:
After:
Test : 
https://weaverbird-playground-pr-1953.onrender.com/
> fix(filter-condition): display all variables for date component not only date type once [TCTC-7312]

- ui/CHANGELOG.md
- ui/src/components/stepforms/widgets/DateComponents/RelativeDateForm.vue
- ui/tests/unit/custom-granularity-calendar.spec.ts
- ui/tests/unit/relative-date-form-widget.spec.ts
We always use untrusted delimiters in relative date form while we should adapt delimiters depending on if variable is trusted or not.
We probably forgot to update this when adding untrusted delimiters
> fix(relative-date-form): use correct delimiters depending on if variable is trusted or not [TCTC-7581]

- server/CHANGELOG.md
- server/src/weaverbird/pipeline/steps/utils/combination.py
- server/tests/pipeline/test_references.py
When providing an append step a pipeline with refs, its references are not correctly resolved. Example: 
```
AppendStepWithRefs(
pipelines=[
[
DomainStepWithRef(domain=Reference(uid="other_pipeline")),
TextStep(new_column="text", text="Lorem ipsum"),
],
]
)
```
> fix(server/steps/append): correctly resolve pipeline with refs [TCTC-7450]

- server/CHANGELOG.md
- server/src/weaverbird/pipeline/steps/utils/combination.py
- server/tests/test_pipeline.py
In append steps, I noticed that sub-pipelines containing variables were not considered valid.
> fix(server): accept variables in combined pipelines TCTC-7763

- docs/_docs/tech/python-package.md
- server/CHANGELOG.md
- server/playground.py
- server/src/weaverbird/pipeline/pipeline.py
- server/src/weaverbird/pipeline/steps/__init__.py
- server/src/weaverbird/pipeline/steps/append.py
- server/src/weaverbird/pipeline/steps/domain.py
- server/src/weaverbird/pipeline/steps/join.py
- server/src/weaverbird/pipeline/steps/utils/combination.py
- server/tests/backends/sql_translator_unit_tests/test_base_translator.py
- server/tests/pipeline/steps/utils/test_combination.py
- server/tests/pipeline/test_references.py
- server/tests/test_pipeline.py
Support references in both Pipeline and PipelineWithVariables.
And remove PipelineWithRefs.
> feat(server): references support in Pipeline (remove PipelineWithRefs type) TCTC-7763

- server/CHANGELOG.md
- server/pyproject.toml
- server/src/weaverbird/backends/mongo_translator/steps/evolution.py
- server/tests/backends/mongo_translator/steps/test_evolution.py
Fixed the `evolution` step when several index columns are used. The generated pipeline now filters on all of them rather than just the last one.
Thanks Ruff for catching this :smile:
> fix(server/mongo): evolution step filters on all index columns

- ui/CHANGELOG.md
- ui/src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
- ui/src/components/stepforms/widgets/DateComponents/NewDateInput.vue
- ui/tests/unit/date-range-input.spec.ts
- ui/tests/unit/new-date-input.spec.ts
In a previous PR: https://github.com/ToucanToco/weaverbird/pull/1988, we updated the delimiters for relative variables but we forgot to do it for default variables (TODAY, YESTERDAY), picked in variables list not in relative date form.
We add logic to retrieve correct delimiters depending on if the variable is trusted or not.
> fix(date-inputs): use correct variables delimiters for default variables [TCTC-8076]

- server/CHANGELOG.md
- server/src/weaverbird/backends/pypika_translator/translators/base.py
- server/src/weaverbird/pipeline/steps/filter.py
- server/tests/backends/fixtures/filter/eq_with_null_pypika.yaml
- server/tests/backends/fixtures/filter/isin_with_null_pypika.yaml
```sql
WHERE column IN (NULL, "foo", "bar")
```
does not work. Replace it with
```sql
WHERE column IS NULL OR column IN ("foo", "bar")
```
```sql
WHERE column=NULL
```
does not work. Replace it with
```sql
WHERE column IS NULL
```
> fix(pypika translator): cannot select null in filterstep with operators in / nin / eq / ne [TCTC-7943]

- ui/package.json
This is a blocker for upgrading consumers to recent bundlers and typescript (such as vite 5)
> chore(ui): declare types as export in package.json

- ui/CHANGELOG.md
- ui/src/components/constants.ts
- ui/tests/unit/action-toolbar-button.spec.ts
We remove the deprecated 'Custom sql' and 'Custom' steps from action menu.
It won't be usable anymore with hybrid pipeline
:information_source: We don't remove steps code and pipeline listing because we may have migrated apps with custom steps so we want them to be removed before cleaning the code
The customs steps are still accessible (to be deleted) if a step has been created earlier but app builder won't be able to create new ones
> fix(steps): remove custom and custom sql deprecated steps from action menu [TCTC-7178]

- server/CHANGELOG.md
- server/src/weaverbird/backends/pandas_executor/steps/waterfall.py
- server/tests/backends/fixtures/waterfall/with_backfill.yaml
Mongo and pandas waterfall steps had slightly different behaviors when handling rows that have the same value for group and label.
Fixes this difference in favor of producing one parent row and one child row.
> fix(server): correctly generate one parent and one child row even if labels are the same TCTC-8331 

- server/CHANGELOG.md
- server/src/weaverbird/backends/pandas_executor/steps/utils/formula.py
- server/src/weaverbird/backends/pypika_translator/utils/formula.py
- server/src/weaverbird/pipeline/formula_ast/eval.py
- server/tests/backends/fixtures/ifthenelse/quotes.json
- server/tests/backends/fixtures/ifthenelse/quotes_pypika.yaml
- server/tests/steps/test_formula.py
Specially useful for ifthenelse
Breaking, but should be safer for the future
Also, corresponds to the behavior explained in UI
> fix(server): only support strings in quotes in formulas TCTC-8504

- server/CHANGELOG.md
- server/src/weaverbird/backends/mongo_translator/steps/fromdate.py
- server/tests/backends/fixtures/fromdate/longmonth_only_custom.json
- server/tests/backends/mongo_translator_unit_tests/test_fromdate_separators.py
Mongo fromdate translator is now more flexible and accepts custom formats like "%B foo" or "bar %b %d"
There was an error when an user was trying to use a custom format in fromdate step.
`pymongo.errors.OperationFailure: PlanExecutor error during aggregation :: caused by :: Invalid format character '%B' in format string, full error: {'ok': 0.0, 'errmsg': "PlanExecutor error during aggregation :: caused by :: Invalid format character '%B' in format string", 'code': 18536, 'codeName': 'Location18536'}`
> fix(fromdate  mongo): mongo translator accepts custom date formats (TCTC-8511)

- server/CHANGELOG.md
- server/src/weaverbird/backends/pypika_translator/translators/base.py
- server/tests/backends/fixtures/ifthenelse/overwrite_column_pypika.yaml
Can generates an other column name instead of an overwrite:
> fix(ifthenelse): dont select column name if its ifthenelse result alias (TCTC-8780)

- server/CHANGELOG.md
- server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
- server/tests/backends/fixtures/dateextract/google_big_query_datetimes.yaml
- server/tests/backends/fixtures/dateextract/google_big_query_timestamps.yaml
- server/tests/backends/sql_translator_integration_tests/test_sql_bigquery_translator_steps.py
- Cast field to datetime in DATE_ADD google big query method
- Raises error in `dateextract` step : 
`BadRequest('DATE_ADD does not support the WEEK date part when the argument is TIMESTAMP type at [1:318]')`
> fix: GBQ DATE_ADD function doesnt support timestamps (TCTC-8784)

- server/CHANGELOG.md
- server/src/weaverbird/backends/pandas_executor/steps/utils/condition.py
- server/tests/backends/fixtures/filter/dates_from_until_too_wide.json
Ces dates "ouf of bounds" arrivent par exemple quand on sélectionne "all dates" dans un filtre (ça génère from year 1000 to year 9999)
(en attendant un meilleur fix qui consisterait à envoyer des `__void__` pour ces variables)
jira card: https://toucantoco.atlassian.net/browse/TCTC-8867
> fix(pandas): handle out of bounds dates in filter from/until [TCTC-8867]

- server/CHANGELOG.md
- server/src/weaverbird/backends/pandas_executor/steps/rollup.py
- server/tests/backends/fixtures/rollup/datetime_followed_by_dateextract.yaml
- Can raise  `*** ValueError: cannot reindex on an axis with duplicate labels` if the next step assigns a new column
> fix(server/pandas): reindex rows at the end of rollup step (TCTC-8689)

- ui/src/components/stepforms/StepFormComponent.vue
- ui/src/components/stepforms/StoreStepFormComponent.vue
- ui/stories/StepForm.stories.ts
Form was not working as expected with defaults values (partial config), due to missing props propagation
We also need to add a selectedColumn property because some complex steps (filter, rename...) preselect column not based on defaults but on selectedColumns logic
> fix(step-form-component): provide step form defaults and preselect column if necessary in complex steps [TCTC-9437]

- ui/CHANGELOG.md
- ui/package.json
While consuming the NPM package, exports needs to be defined explicitly in order to not raise errors when imported. 
See https://webpack.js.org/guides/package-exports/ and https://nodejs.org/api/packages.html#subpath-exports
> fix(ui): declare css export

- ui/src/components/stepforms/StepFormComponent.vue
I missed reactivity for selected column in weaverbird data viewer migration, it results to selected column not working as expected in migrated code
Watch update state value
Key update form component (because it not watch anything, it only apply state on init based on selected column so we need a full refresh)
> fix(step-form-component): handle reactivity for selected column

- server/CHANGELOG.md
- server/src/weaverbird/backends/mongo_translator/steps/ifthenelse.py
- server/src/weaverbird/backends/mongo_translator/utils.py
- server/tests/backends/fixtures/ifthenelse/after_join.yaml
- server/tests/backends/mongo_translator/steps/test_ifthenelse.py
- server/tests/backends/mongo_translator/test_mongo_translator_steps.py
A join step can introduce missing fields: if the `$lookup` step does not return anything,
the right fields will be missing from the resulting documents. This causes
`{$eq: [$missing_field, null]}` to always evaluate to false since the field cannot be
looked up.
This PR fixes that behaviour by defaulting to null for missing expressions with the
isnull/isnotnull operators.
The same logic was applied to the `then` and `else` branches: an `$addFields` aggreation with a
`$cond` evalutating to an empty field just does NOT add a new field.
> fix(server/mongo): support missing fields with isnull/notnull [TCTC-9655]

- server/CHANGELOG.md
- server/src/weaverbird/backends/pypika_translator/translators/athena.py
- server/src/weaverbird/backends/pypika_translator/translators/base.py
- server/tests/backends/sql_translator_unit_tests/test_offset_limit_behaviour.py
> fix(server/pypika): reverse OFFSET and LIMIT for Athena translator [TCTC-9905]

- ui/src/components/stepforms/widgets/Autocomplete.vue
- ui/src/components/stepforms/widgets/InputDate.vue
- ui/src/components/stepforms/widgets/InputNumber.vue
- ui/src/components/stepforms/widgets/InputText.vue
- ui/src/components/stepforms/widgets/MultiInputText.vue
- ui/src/components/stepforms/widgets/VariableInput.vue
- ui/src/components/stepforms/widgets/VariableInputs/VariableInputBase.vue
We modify the variable button display to always make it visible.
We also add a padding to components that use it (Input/Autocomplete) in order to display labels correctly as there is an extra element in it.
Before:
After:
> fix(variable-input): always display variable input

- ui/CHANGELOG.md
- ui/src/components/stepforms/widgets/VariableInputs/VariableInputBase.vue
- ui/tests/unit/variable-input-base.spec.ts
[TCTC-10072](https://toucantoco.atlassian.net/browse/TCTC-10072?atlOrigin=eyJpIjoiMTBiMDJlODVlZDMzNGEzMmI2NTQzZDU0MmRiNzg2MzIiLCJwIjoiaiJ9):
> As we want to be able to better track feature usage we want to add some Mixpanel events to the addition we’ve done on weaverbird: [fix(variable-input): always display variable input](https://github.com/ToucanToco/weaverbird/pull/2333)
> - Click on variable button
This PR adds the analytics event on the click, and the unit test to match.
[TCTC-10072]: https://toucantoco.atlassian.net/browse/TCTC-10072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui, variables): send mixpanel event [TCTC-10072]

- server/CHANGELOG.md
- server/src/weaverbird/utils/toucan_connectors.py
- server/tests/backends/mongo_translator/test_mongo_translator_steps.py
- server/tests/backends/pandas_executor/test_pandas_executor_steps.py
- server/tests/backends/sql_translator_integration_tests/test_sql_athena_translator_steps.py
- server/tests/backends/sql_translator_integration_tests/test_sql_bigquery_translator_steps.py
- server/tests/backends/sql_translator_integration_tests/test_sql_mysql_translator_steps.py
- server/tests/backends/sql_translator_integration_tests/test_sql_postgres_translator_steps.py
- server/tests/backends/sql_translator_integration_tests/test_sql_redshift_translator_steps.py
- server/tests/backends/sql_translator_integration_tests/test_sql_snowflake_translator_steps.py
- server/tests/steps/test_filter.py
- server/tests/steps/test_ifthenelse.py
- server/tests/test_pipeline.py
When there is a pipeline with a variable and a value is not provided, we get this error:
```
E       pydantic_core._pydantic_core.ValidationError: 3 validation errors for FilterStep
E       condition.ConditionComboAnd.and
E         Field required [type=missing, input_value={'column': 'price', 'operator': 'lt'}, input_type=dict]
E           For further information visit https://errors.pydantic.dev/2.10/v/missing
E       condition.ConditionComboOr.or
E         Field required [type=missing, input_value={'column': 'price', 'operator': 'lt'}, input_type=dict]
E           For further information visit https://errors.pydantic.dev/2.10/v/missing
E       condition.tagged-union[ComparisonCondition,ComparisonCondition,ComparisonCondition,ComparisonCondition,ComparisonCondition,ComparisonCondition,Inc …
```
> refactor!(server/pipeline): raise UndefinedVariableError when variables are missing during rendering [TCTC-10013]

- server/uv.lock
Issue with dependabot : https://github.com/astral-sh/uv/issues/12254
This reverts commit 97fcf7482cbf759018335d6ea9f520fe02e87a34.
> Revert "build(deps): bump the prod-deps group across 1 directory with 4 updates (#2371)"

- ui/CHANGELOG.md
- ui/src/components/stepforms/DateGranularityStepForm.vue
- ui/src/components/stepforms/schemas/dategranularity.ts
- ui/tests/unit/dategranularity-step-form.spec.ts
Fixes two problems: 
- better validation message
- handle type differences between enum values and variable values
> fix(ui, dategranularity): `granularity` handle both enum values and variables

- server/CHANGELOG.md
- server/src/weaverbird/backends/pandas_executor/steps/ifthenelse.py
- server/src/weaverbird/backends/pandas_executor/steps/utils/formula.py
- server/src/weaverbird/backends/pypika_translator/translators/base.py
- server/src/weaverbird/pipeline/formula_ast/eval.py
- server/src/weaverbird/pipeline/formula_ast/types.py
- server/tests/backends/fixtures/ifthenelse/simple_with_dates_and_nulls.yaml
- server/tests/backends/fixtures/ifthenelse/simple_with_dates_and_nulls_pypika.yaml
- server/tests/steps/test_ifthenelse.py
In some `ifthenelse` cases, it is preferable to simply output `null` in the `then` or `else`.
It is indeed a breaking change.
> feat(ifthenelse, formula): allow `null` as value
