package.json, src/main.ts
Allow us to expose one package with Pipeline component and translation utils functions
=> Feature :: Create One Package

src/components/DomainSelector.vue, src/components/Pipeline.vue
Improve style of the component Pipeline when no steps defined yet
=> Fix :: Pipeline pristine case

src/App.vue, src/components/Step.vue
`Step` component now handle a `disabled` step and we adapt its template to our new format of step (renaming `name` to `step`)
=> Feature :: Step Disabled State 

.circleci/config.yml, README.md
This PR adds 2 very simple build and test jobs and a badge in the README file.
=> Feature :: add circleci configuration

README.md, package.json, src/App.vue, src/components/Pipeline.vue, src/components/Step.vue, src/example.ts, src/main.ts, tests/unit/pipeline.spec.ts, yarn.lock
Allow us to return a part of steps' pipeline in order to see our query at different step
=> Feature :: Pipeline time travel

doc/steps.md
Add missing documentation about the `newcolumn` step.
=> [doc] document `newcolumn` step

.storybook/addons.js, .storybook/config.js, README.md, package.json, stories/index.js, yarn.lock
Add storybook to visually develop the UI components
=> Dev :: Storybook environment

src/App.vue
Use `Arrray<PipelineStep>` instead of `Array<any>` in `App.vue` component.
=> tech :: update example App component to match valid step types

.circleci/config.yml, .gitignore, README.md, codecov.yml, jest.config.js, package.json, yarn.lock
=> Tech :: Add Coverage

doc/steps.md, src/lib/steps.ts, src/lib/translators/base.ts, src/lib/translators/mongo.ts, tests/unit/mongo.spec.ts
Replace null values by a given value in a column.
Closes https://github.com/ToucanToco/vue-query-builder/issues/69
=> Feature: fillna step translation to mongo

doc/steps.md, src/lib/steps.ts, src/lib/translators/base.ts, src/lib/translators/mongo.ts, tests/unit/mongo.spec.ts
This step computes the percentage of total, i.e. for every row the value is divided
by the total as the sum of every values in a column. The computation can be performed
by group if specified. The result can be either output inplace or in a new column if specified
Closes https://github.com/ToucanToco/vue-query-builder/issues/68
=> Feature :: percentage step to mongo

jest.config.js
Otherwise it seems like the `--watch` option doesn't handle them
correctly.
=> [jest] make sure `.d.ts` are matched by jest

src/components/DataViewer.vue, src/lib/dataset.ts, src/lib/dataset/index.ts, src/lib/dataset/mongo.ts, stories/data-viewer.js, tests/unit/data-viewer.spec.ts, tests/unit/dataset.spec.ts
DataSet type is defined as two properties:
- `headers`: a list of objects defining columns
- each column is itself defined by a `name` and
an optional `type`. We'll probably add extra
metadata later,
- `data`: a list of list of values
Use this type in the `DataViewer` component.
Related to https://github.com/ToucanToco/vue-query-builder/issues/26
=> feature :: define a basic dataset type

src/lib/steps.ts
Remove hardcoded property values :thinking_face:
=> [steps] fix pivot step type definition

.gitignore, .storybook/bundle.ts, jest.config.js, package.json, playground/App.vue, playground/dbservice.ts, playground/main.ts, playground/rollup.config.js, src/App.vue, src/components/DataViewer.vue, src/components/DomainSelector.vue, src/components/Pipeline.vue, src/lib/pipeline.ts, src/lib/steps.ts, src/lib/translators/mongo.ts, src/store/backend-plugin.ts, src/store/getters.ts, src/store/index.ts, src/store/mutations.ts, src/store/state.ts, stories/data-viewer.js, tests/unit/data-viewer.spec.ts, tests/unit/mongo.spec.ts, tests/unit/pipebuild.spec.ts, tests/unit/pipeline.spec.ts, tests/unit/plugins.spec.ts, tests/unit/store.spec.ts, yarn.lock
=> feature :: use vuex for application state

.prettierrc.js, package.json, src/components/DataViewer.vue, src/components/DataViewerCell.vue, src/components/DomainSelector.vue, src/components/Pipeline.vue, src/components/Step.vue, src/lib/dataset/index.ts, src/lib/dataset/mongo.ts, src/lib/matcher.ts, src/lib/pipeline.ts, src/lib/steps.ts, src/lib/translators/base.ts, src/lib/translators/mongo.ts, src/store/backend-plugin.ts, src/store/index.ts, src/store/state.ts, src/typings/mathjs/index.d.ts, tests/unit/mongo.spec.ts, tests/unit/pipebuild.spec.ts, tests/unit/plugins.spec.ts, tests/unit/translator.spec.ts, yarn.lock
- report unused vars:
- accept `_` as function arguments
- add a few local eslint disable statements to bypass https://github.com/eslint/typescript-eslint-parser/issues/223
- ignore type declration files
- run autofix:
- prefer `const` over `let`
- use `[]` instead of `Array` in type definitions (e.g.
`Array<string>` becomes `string[]`)
Related to #128
=> [eslint] better configuration and use typescript-eslint

src/components/DataViewer.vue, src/components/Pipeline.vue, src/components/Step.vue, src/store/backend-plugin.ts, src/store/mutations.ts, tests/unit/pipeline.spec.ts, tests/unit/step.spec.ts
Delete a step when clicking on its trash icon.
Closes https://github.com/ToucanToco/vue-query-builder/issues/39
=> Feature :: Delete step

playground/App.vue, src/components/FormRenameStep.vue, src/components/Pipeline.vue, src/components/Step.vue, src/store/getters.ts, src/store/mutations.ts, src/store/state.ts
A rename step can be editing inside a pipeline.
Improvements and tests to come...
=> Feature :: edit rename step

src/components/DataViewer.vue, src/components/Step.vue, src/styles/Steps.scss, tests/unit/step.spec.ts
Make a pipeline step fully clickable (not only the time travel dot)
Closes https://github.com/ToucanToco/vue-query-builder/issues/45
=> Improve :: Select pipeline step

src/components/Pipeline.vue, src/components/Step.vue, src/styles/DataViewer.scss, src/styles/Steps.scss, src/styles/_variables.scss, tests/unit/pipeline.spec.ts
To be iso with the design, I propose theses changes with a refacto of classes computation.
Before
After
=> [step] :: enhance active step UI

src/components/Vqb.vue
Following bad resolution of merge conflicts
=> Fix :: add back editStep event handler in Vqb

src/components/WidgetAutocomplete.vue, src/styles/_variables.scss
Improve style and and remove deselect initial value option for vue multiselect
Before :
Now :
=> Polishing :: style for WidgetAutoComplete

.circleci/config.yml
remove useless `--runInBand` option
=> [circleci] jest is not used anymore

src/components/Vqb.vue, src/styles/ResizablePanels.scss, tests/unit/vqb.spec.ts
To enhance a little bit the UI, I add a slide transition when switching between Pipeline and step Forms edition.
=> Feature :: Nice Slide Transition between Pipeline and StepForms component

src/assets/schemas/filter-step__schema.json, src/components/ActionMenu.vue, src/components/stepforms/FilterStepForm.vue, src/components/stepforms/index.ts, tests/unit/filter-step-form.spec.ts, tests/unit/karma-test-suite.ts
**This is to be merged in f/form-mixin-refacto** (or in master once the other is merged)
NOTE: I've put the filter action inside the action menu rather than
in the "filter" toolbar popover because I'm waiting for PR #173 to
be finished.
=> [stepforms] implement FilterStep form

src/assets/schemas/domain-step__schema.json, src/components/Pipeline.vue, src/components/Step.vue, src/components/Vqb.vue, src/components/stepforms/DomainStepForm.vue, src/components/stepforms/index.ts, src/store/getters.ts, src/styles/Steps.scss, tests/unit/domain-step-form.spec.ts, tests/unit/karma-test-suite.ts, tests/unit/pipeline.spec.ts, tests/unit/step.spec.ts, tests/unit/store.spec.ts, tests/unit/vqb.spec.ts
In order to have the possibility to time travel back to the domain choice, we now consider it like a Step unremovable (I'd like feedback on this, we can maybe improve the check). We had to aslo create a form component in order to change the domain because is no long a dropdown.
=> Feature :: Domain Step in the Pipeline 

src/components/stepforms/AggregateStepForm.vue
Just fix a typo in the name of Aggregate Step form
=> fix :: aggregate step title

src/components/ActionToolbar.vue, src/components/ActionToolbarButton.vue, src/components/constants.ts, tests/unit/action-toolbar.spec.ts
- add new properties for button in `constant.ts`
- add new object `ACTION_CATEGORIES`
- add property `enable` to display a special style / remove hover cursor for disabled button
=> Feature :: Action toolbar popover 

package.json, playground/app.js, playground/dist/index.html, playground/server.js, src/components/DataViewer.vue, yarn.lock
In order to make quick demos with the playground, we decide to add a little feature to drop a CSV file into it.
=> Feature :: Playground :: Drop CSV File

playground/server.js
=> Fix :: empty cells in csv

src/components/stepforms/FillnaStepForm.vue
remove unnecessary import of BaseStep form into FillnaStepForm components
=> FillnaStepForm :: clean unnecessary import

src/components/ActionToolbarButton.vue
I just replace hex code to define colors by its already defined SASS variable.
=> Refacto :: ActionToolButton use SASS $active-color variable

src/components/stepforms/AggregateStepForm.vue
Use the new way to update property when selectedColumns change using the reactive property inherit of BaseStepForm
=> AggregateStepForm :: Use the new way to update property when selectedColumns change

src/assets/schemas/argmax-step__schema.json, src/components/stepforms/ArgmaxStepForm.vue, src/components/stepforms/index.ts, tests/unit/argmax-step-form.spec.ts
Closes https://github.com/ToucanToco/vue-query-builder/issues/219
=> Feature :: UI argmax step

src/assets/schemas/argmax-step__schema.json, src/assets/schemas/argmin-step__schema.json, src/components/stepforms/ArgmaxStepForm.vue, src/components/stepforms/ArgminStepForm.vue, src/components/stepforms/index.ts, src/lib/translators/mongo.ts, tests/unit/argmax-step-form.spec.ts, tests/unit/argmin-step-form.spec.ts, tests/unit/karma-test-suite.ts, tests/unit/mongo.spec.ts
Closes https://github.com/ToucanToco/vue-query-builder/issues/218
=> Feature :: UI argmin step

src/assets/schemas/percentage-step__schema.json, src/components/stepforms/PercentageStepForm.vue, src/components/stepforms/index.ts, tests/unit/karma-test-suite.ts, tests/unit/percentage-step-form.spec.ts
Closes https://github.com/ToucanToco/vue-query-builder/issues/216
=> Introduce Percentage Step

tests/unit/action-toolbar.spec.ts, tests/unit/argmax-step-form.spec.ts, tests/unit/argmin-step-form.spec.ts, tests/unit/data-viewer.spec.ts, tests/unit/percentage-step-form.spec.ts, tests/unit/rename-step-form.spec.ts, tests/unit/step.spec.ts, tests/unit/vqb.spec.ts
They are technically the same, we simply don't need to import `Vue` for that :)
=> [tests] uses localVue.nextTick() instead of Vue.nextTick()

src/assets/schemas/unpivot-step__schema.json, src/components/ActionToolbar.vue, src/components/stepforms/UnpivotStepForm.vue, src/components/stepforms/WidgetCheckbox.vue, src/components/stepforms/index.ts, tests/unit/karma-test-suite.ts, tests/unit/unpivot-step-form.spec.ts, tests/unit/widget-checkbox.spec.ts
=> Feature :: implement Unpivot Step form

src/components/stepforms/AggregateStepForm.vue, src/components/stepforms/ArgmaxStepForm.vue, src/components/stepforms/ArgminStepForm.vue, src/components/stepforms/DeleteColumnStepForm.vue, src/components/stepforms/DomainStepForm.vue, src/components/stepforms/FillnaStepForm.vue, src/components/stepforms/FilterStepForm.vue, src/components/stepforms/PercentageStepForm.vue, src/components/stepforms/RenameStepForm.vue, src/components/stepforms/StepForm.vue, src/components/stepforms/StepFormTitle.vue, src/components/stepforms/WidgetAggregation.vue, src/components/stepforms/WidgetAutocomplete.vue, src/components/stepforms/WidgetMultiselect.vue, src/styles/_variables.scss
This PR mainly consists in aesthetics:
- Clean duplicated CSS
- Improve styling: text sizing of labels, placeholders & buttons, text color, title alignment and  autocomplete/multiselect items highlight color
- Improve naming: labels & title
**Before:**
**After:**
**Before:**
**After:**
=> Feature :: Improve forms diplay

src/components/stepforms/PivotStepForm.vue, src/components/stepforms/index.ts, src/components/stepforms/schemas/index.ts, src/components/stepforms/schemas/pivot.ts, tests/unit/karma-test-suite.ts, tests/unit/pivot-step-form.spec.ts
=> Feature :: Pivot Step Form

doc/steps.md, src/components/ActionMenu.vue, src/components/stepforms/DuplicateColumnStepForm.vue, src/components/stepforms/index.ts, src/components/stepforms/schemas/duplicate.ts, src/components/stepforms/schemas/index.ts, src/lib/steps.ts, src/lib/translators/mongo.ts, tests/unit/action-menu.spec.ts, tests/unit/duplicate-column-step-form.spec.ts, tests/unit/karma-test-suite.ts, tests/unit/mongo.spec.ts
Closes https://github.com/ToucanToco/vue-query-builder/issues/213
=> Feature :: Duplicate column step

src/components/stepforms/AggregateStepForm.vue, src/components/stepforms/WidgetList.vue, tests/unit/widget-list.spec.ts
Pass directly the repeatable component as property to WidgetList
=> Feature :: Improve WidgetList

tests/rollup.config.test.js
Fix typo in glob path (add a missing "s" to "tests")
=> [tests] exclude test files from coverage

src/components/stepforms/TopStepForm.vue, src/components/stepforms/index.ts, src/components/stepforms/schemas/index.ts, src/components/stepforms/schemas/top.ts, tests/unit/karma-test-suite.ts, tests/unit/top-step-form.spec.ts
Closes https://github.com/ToucanToco/vue-query-builder/issues/232
=> Introduce a Top step

src/components/constants.ts, src/components/stepforms/DeleteColumnStepForm.vue, src/components/stepforms/StepForm.vue, src/components/stepforms/schemas/delete.ts, tests/unit/delete-column-step-form.spec.ts
Replace autocomplete by multiselect to be able to delete multiple columns at once, and make the step accessible from the "Filter widget"
=> Feature :: Improve delete step

src/components/constants.ts, src/components/stepforms/SelectColumnStepForm.vue, src/components/stepforms/index.ts, src/components/stepforms/schemas/index.ts, src/components/stepforms/schemas/select.ts, tests/unit/select-column-step-form.spec.ts
Closes https://github.com/ToucanToco/vue-query-builder/issues/235
=> Feature :: UI Keep Columns

src/components/stepforms/ArgmaxStepForm.vue, src/components/stepforms/ArgminStepForm.vue, src/components/stepforms/ColumnPicker.vue, src/components/stepforms/DuplicateColumnStepForm.vue, src/components/stepforms/FillnaStepForm.vue, src/components/stepforms/FilterStepForm.vue, src/components/stepforms/PercentageStepForm.vue, src/components/stepforms/PivotStepForm.vue, src/components/stepforms/RenameStepForm.vue, src/components/stepforms/TopStepForm.vue, tests/unit/argmax-step-form.spec.ts, tests/unit/argmin-step-form.spec.ts, tests/unit/column-picker.spec.ts, tests/unit/duplicate-column-step-form.spec.ts, tests/unit/fillna-step-form.spec.ts, tests/unit/filter-step-form.spec.ts, tests/unit/karma-test-suite.ts, tests/unit/percentage-step-form.spec.ts, tests/unit/pivot-step-form.spec.ts, tests/unit/rename-step-form.spec.ts, tests/unit/top-step-form.spec.ts
=> [widgets] introduce column picker component

src/components/ActionToolbar.vue, src/components/stepforms/FormulaStepForm.vue, src/components/stepforms/index.ts, src/components/stepforms/schemas/formula.ts, src/components/stepforms/schemas/index.ts, tests/unit/formula-step-form.spec.ts, tests/unit/karma-test-suite.ts
Closes https://github.com/ToucanToco/vue-query-builder/issues/243
=> Feature: UI Formula

doc/known_limitations.md
Closes https://github.com/ToucanToco/vue-query-builder/issues/252
=> Introduce a Known Limitations section in the documentation

src/components/stepforms/FilterStepForm.vue, src/components/stepforms/WidgetAutocomplete.vue, src/components/stepforms/WidgetFilterSimpleCondition.vue, src/components/stepforms/WidgetList.vue, src/components/stepforms/WidgetMultiInputText.vue, src/components/stepforms/schemas/filter.ts, src/lib/steps.ts, src/lib/translators/mongo.ts, tests/unit/filter-step-form.spec.ts, tests/unit/karma-test-suite.ts, tests/unit/mongo.spec.ts, tests/unit/widget-filter-simple-condition.spec.ts, tests/unit/widget-multi-input-text.spec.ts
Improve Filter step:
- The API now allows for complex conditions (imbricated and/or)
- The UI allows to configure several conditions, linked by a logical "and" (at this stage the UI does not allow to build "or" conditions)
- For every condition, the user input depends on the selected operator (multiple values for in/nin, single value for the other operators)
Related to https://github.com/ToucanToco/vue-query-builder/issues/56
=> [Step] Improve Filter step

tests/unit/vqb.spec.ts
There was a mistake into the transition component stubbing, that PR resolves that.
=> Fix :: stub transition component with correct parameter

src/components/ActionMenu.vue, src/components/stepforms/FillnaStepForm.vue, src/components/stepforms/ReplaceStepForm.vue, src/components/stepforms/WidgetToReplace.vue, src/components/stepforms/index.ts, src/components/stepforms/schemas/index.ts, src/components/stepforms/schemas/replace.ts, src/lib/helpers.ts, tests/unit/helpers.spec.ts, tests/unit/replace-step-form.spec.ts, tests/unit/widget-to-replace.spec.ts
Closes https://github.com/ToucanToco/vue-query-builder/issues/244
=> Introduce a replace step ui component

src/components/Popover.vue, tests/unit/popover.spec.ts
Otherwise it simpy doesn't work
=> [popover] suffix style units with px expclitly

tests/unit/filter-step-form.spec.ts
This was just supposed to be a debug test but it somehow managed to go
trhough review :/
=> [tests] fix hardcoded filter-step-form jsonschema test

playground/app.js, src/components/SearchBar.vue, src/main.ts
- eslint,
- useless exports,
- useless `translator` attribute in playground.
=> Minor cleanings

README.md
My feedback after my vqb onboarding :)
=> Tech :: update readme

src/components/Step.vue, src/lib/labeller.ts, src/lib/steps.ts, src/lib/translators/mongo.ts, src/styles/Steps.scss, tests/unit/labeller.spec.ts
=> Provide human-readable representations for each kind of step

src/components/Step.vue, src/styles/Steps.scss, tests/unit/step.spec.ts
=> Feature :: Step Action Buttons Wholly Clickable

playground/app.js
Forget to pass down store as first parameters due to this PR #287
=> Fix :: Playground pipeline initialization

src/components/Pipeline.vue, src/styles/Pipeline.scss, tests/unit/pipeline.spec.ts
Always a message to invite the user to interact with table or the widgets. So I also rename the CSS classes as well
=> Enhancement :: Always leave tips message under steps on Pipeline

src/components/stepforms/FilterStepForm.vue, src/components/stepforms/widgets/FilterSimpleCondition.vue, tests/unit/filter-step-form.spec.ts
=> [FilterStepForm] Fix :: Set column value with current selected column

playground/dist/index.html, src/components/Popover.vue, src/styles/_variables.scss
Apply styles on `body` overwrote global style in project where VQB is used.
=> Improve :: global style scope

CHANGELOG.md, doc/variables.md, playground/app.js, playground/dist/index.html, playground/server.js, src/components/stepforms/StepForm.vue, src/lib/steps.ts, src/lib/templating.ts, src/store/backend-plugin.ts, src/store/state.ts, tests/unit/fillna-step-form.spec.ts, tests/unit/plugins.spec.ts, tests/unit/templating.spec.ts, tests/unit/top-step-form.spec.ts
Implement parametrized queries.
Closes #320
=> Variable interpolation in pipeline steps

CHANGELOG.md, doc/steps.md, src/components/stepforms/PercentageStepForm.vue, src/components/stepforms/schemas/percentage.ts, src/lib/labeller.ts, src/lib/steps.ts, src/lib/translators/mongo.ts, tests/unit/labeller.spec.ts, tests/unit/mongo.spec.ts, tests/unit/percentage-step-form.spec.ts, tests/unit/templating.spec.ts
Remove optional `new_column` parameter
Closes https://github.com/ToucanToco/vue-query-builder/issues/315
=> Simplify percentage step

src/styles/DataViewer.scss
It lead to bad integration on other project
=> Fix :: add a minimum of margin on data-viewer

doc/steps.md, src/components/constants.ts, src/components/stepforms/ToLowerStepForm.vue, src/components/stepforms/ToUpperStepForm.vue, src/components/stepforms/index.ts, src/components/stepforms/schemas/index.ts, src/components/stepforms/schemas/tolower.ts, src/components/stepforms/schemas/toupper.ts, src/lib/labeller.ts, src/lib/steps.ts, src/lib/templating.ts, src/lib/translators/base.ts, src/lib/translators/mongo.ts, tests/unit/action-toolbar-button.spec.ts, tests/unit/action-toolbar.spec.ts, tests/unit/labeller.spec.ts, tests/unit/mongo.spec.ts, tests/unit/templating.spec.ts, tests/unit/tolower-step-form.spec.ts, tests/unit/toupper-step-form.spec.ts
This branch introduces toLower and toUpper steps and is a parent branch for other text operations branches (concatenate, split, substring)
Closes #335
=> Feature :: Add text operations (toLower and toUpper)

CHANGELOG.md, package.json
=> Release :: v0.3.0

CHANGELOG.md, README.md, docs/_config.yml, docs/about.html, package.json, playground/dist/index.html, playground/dist/playground.css, playground/dist/vue-query-builder.browser.js, playground/dist/weaverbird.browser.js, public/index.html, rollup.config.js, src/components/Vqb.vue, stories/index.js
Rename `vue-query-builder` into `weaverbird`
=> Weaverbird has spoken, let it leave the nest

.gitignore
cf. https://git-scm.com/docs/gitignore and https://julien.danjou.info/properly-managing-your-gitignore/
=> [git] remove editor/OS-specific paths

tests/unit/popover.spec.ts
This test was supposed to be run in a browser with karma.
=> [tests] remove browser tests for popover

src/components/DataViewer.vue, src/components/Pagination.vue, src/styles/DataViewer.scss
There was two problem:
1. First, as the pagination is inside a div that is destroyed between each fetch, when leaving the component handle the current page, it was always reset to 1. We decide to put our confidence in the store and hard set it in our parent component.
2. Enhance the template and CSS in order to ease integration
=> Fix :: Pagination Integration

playground/app.js, playground/dist/index.html, src/styles/ResizablePanels.scss
Some linting changes are in it too. Cause before padding/marging were badly handled, we've got scroll on playground, this PR resolves that.
=> Enhancement :: Playground Scrolling Hell

src/components/constants.ts, src/components/stepforms/CustomStepForm.vue, src/components/stepforms/index.ts, src/components/stepforms/schemas/custom.ts, src/components/stepforms/schemas/index.ts, src/components/stepforms/widgets/TextareaWidget.vue, src/lib/pipeline.ts, src/lib/steps.ts, src/lib/translators/base.ts, src/lib/translators/mongo.ts, src/lib/translators/mongo4.ts, tests/unit/action-toolbar-button.spec.ts, tests/unit/custom-step-form.spec.ts, tests/unit/labeller.spec.ts, tests/unit/mongo.spec.ts, tests/unit/pipebuild.spec.ts, tests/unit/search-bar.spec.ts, tests/unit/templating.spec.ts, tests/unit/textarea-widget.spec.ts
Please read commit by commit
related to https://github.com/ToucanToco/weaverbird/issues/241
=> New Step :: custom step

CHANGELOG.md, src/lib/translators/mongo.ts
=> Fix unpivot translation to manage dropna option properly

CHANGELOG.md, src/components/stepforms/ToDateStepForm.vue, src/components/stepforms/schemas/todate.ts, src/lib/translators/mongo4.ts, tests/unit/mongo.spec.ts, tests/unit/mongo4.spec.ts, tests/unit/todate-step-form.spec.ts, tests/unit/utils.ts
Not supported for mongo36 translator
=> Add UI for format parameter in todate step

src/components/stepforms/widgets/CodeEditorWidget.vue, src/components/stepforms/widgets/DefaultCodeEditor.vue
It should not be styled like other widget as this widget will be customised from outside.
These styles should be good to get a proper integration
=> widget-code-editor re-style

CHANGELOG.md, src/lib/templating.ts, tests/unit/templating.spec.ts
=> custom step :: add support for templating

src/components/stepforms/widgets/Aggregation.vue, src/components/stepforms/widgets/List.vue, tests/unit/aggregation-widget.spec.ts, tests/unit/list-widget.spec.ts
Revert #448 and fixes the original problem: the autocomplete widget was not updating itself when its data changed.
=> Fix aggregation list behavior

src/components/stepforms/ReplaceStepForm.vue, src/components/stepforms/widgets/Replace.vue, tests/unit/replace-widget.spec.ts
the problem is explain here => https://github.com/ToucanToco/weaverbird/issues/462
=> fix :: replaceWidget change props behavior

src/components/QueryBuilder.vue, src/components/stepforms/StepFormHeader.vue
=> hyperlinks :: add 'nooponer' protection to _blank targets

CHANGELOG.md, src/components/stepforms/FromDateStepForm.vue, src/components/stepforms/ToDateStepForm.vue, src/components/stepforms/widgets/InputText.vue, tests/unit/input-text-widget.spec.ts
=> In-app doc :: add link to supported date formats in todate and fromdate steps UI

src/components/stepforms/SortStepForm.vue, src/components/stepforms/widgets/SortColumn.vue, tests/unit/sort-column-widget.spec.ts, tests/unit/sort-step-form.spec.ts
the problem is described here => #462
=> Fix :: sort step change props propagation

README.md, package.json, yarn.lock
- remove @formschema/native
- move to dev dependencies `ts-jest` and `@types`
- add npm version badge
=> Update dependencies and add version badge in README

src/components/stepforms/widgets/Autocomplete.vue, tests/unit/autocomplete-widget.spec.ts
Remove watchers to simplify the code
=> Change how updates are propagated from Autocomplete widget

src/components/ConditionsEditor/ConditionsEditor.vue, src/components/FilterEditor.vue, src/components/stepforms/FilterStepForm.vue, src/components/stepforms/convert-filter-step-tree.ts, src/main.ts, tests/unit/conditions-editor.spec.ts, tests/unit/convert-filter-step-tree.spec.ts, tests/unit/filter-editor.spec.ts, tests/unit/filter-step-form.spec.ts
Create an intermediate component (`FilterEditor`) between `FilterStepForm` and `ConditionsEditor`.
`FilterEditor` contains conditionsEditor + filterSimpleCondition + all data transformation logic
to permit the export of the interface with all the its logical, but without filterStep env.
=> Components :: create component FilterEditor

docs/_data/docs.yml, docs/_docs/contributing/new-step.md, docs/_docs/tech/index.md, docs/_docs/tech/known_limitations.md, docs/_docs/tech/translators.md, docs/_docs/tech/ui-components.md, docs/_includes/topnav.html, src/main.ts
Along with a few small others improvements, I added a "UI components" page to tech docs.
This will come handy to explain why components are exported, and how to use them.
It will be enriched, e.g. with this PR: #494  that exports a new component.
=> Tech docs :: Documented exported UI components 

src/store/backend-plugin.ts, tests/unit/plugins.spec.ts
- extract the pipeline preparation from `_updateDataset`, e.g. the
dereferencing,
- introduce the `backendify` "decorator" (but can't be used as
@backendify around functions unfortunately because JavaScript doesn't
support it) that:
- sets the `loading: true` property on the store at the beginning,
- logs the error in the store if any,
- sets the `loading: false` property on the store at the end.
=> Split `_updateDataset` and introduce `backendify`

.storybook/bundle.ts, .storybook/preview-head.html, src/components/ListUniqueValues.vue, src/lib/steps.ts, src/styles/_variables.scss, stories/index.js, stories/list-unique-values.js, tests/unit/list-unique-values.spec.ts
This component display a column's unique values. It allows to search among values and to select and unselect values.
Notes: This is a visual component, it does not trigger any action nor mutationhimself.
It is meant to be used inside "ActionMenu".
This commit introduce `ListUniqueValue` component, tests and a storybook. For now, the component is not used inside the project.
In the close futur: (spoiler alert)
=> New component: ListUniqueValue

CHANGELOG.md, src/components/ActionMenu.vue, src/components/DataViewer.vue, src/components/ListUniqueValues.vue, src/components/Popover.vue, src/lib/dataset/helpers.ts, src/lib/dataset/index.ts, src/lib/helpers.ts, src/main.ts, src/store/actions.ts, src/store/backend-plugin.ts, src/store/getters.ts, src/store/mutations.ts, src/store/state.ts, tests/unit/action-menu.spec.ts, tests/unit/data-viewer.spec.ts, tests/unit/dataset.spec.ts, tests/unit/helpers.spec.ts, tests/unit/list-unique-values.spec.ts, tests/unit/plugins.spec.ts, tests/unit/popover.spec.ts, tests/unit/store.spec.ts
Please, read commit by commit.
Test the feature here: https://weaverbird-test.herokuapp.com/
=> Compute and display unique values of column

src/components/stepforms/widgets/FilterSimpleCondition.vue, src/components/stepforms/widgets/MultiInputText.vue, tests/unit/filter-simple-condition-widget.spec.ts, tests/unit/multi-input-text-widget.spec.ts
=> Fix props propagation of mutlti-input-text

CHANGELOG.md, src/components/ActionMenu.vue
=> Update "Apply Filter" button design

CHANGELOG.md, src/store/getters.ts, tests/unit/store.spec.ts
This is useful when vuex sate is in strict mode
=> Add a trivial state getter to get backendMessage

CHANGELOG.md, src/lib/dataset/helpers.ts, tests/unit/dataset.spec.ts, tests/unit/store.spec.ts
Before: the values were sorted by count
Before:
After:
=> Sort unique values in alphanumeric order

src/components/stepforms/widgets/VariableInput/VariableInput.vue
Popover was getting closed as soon as it opened :'(
@rhuille I think it's related to popover PRs ;)
=> Fix popover opening to choose a variable

playground/app.js, playground/dist/index.html
- Setup data is done by calling the updateDataset action
- Remove example warning
- Display the vqb pipeline in console
before:
After:
=> Playground enhancements

src/components/stepforms/JoinStepForm.vue, src/components/stepforms/schemas/join.ts, src/lib/steps.ts, tests/unit/join-step-form.spec.ts
Fixes #549 
Add `left outer` to the lists of join types.
=> Add the 'left outer' to the schema and type enum for JoinStep.

CHANGELOG.md, src/components/stepforms/widgets/VariableInput/VariableInput.vue
=> Button to toogke variable input is '{}'

src/components/DataViewer.vue, src/components/Pagination.vue, src/store/getters.ts, tests/unit/data-viewer.spec.ts, tests/unit/pagination-component.spec.ts, tests/unit/store.spec.ts
=> Always show the result's row count.

src/components/stepforms/IfThenElseStepForm.vue, tests/unit/ifthenelse-step-form.spec.ts
After one "else if", the produced pipeline/query was not cast properly.
=> fix: cast values on deeper conditionnal levels

src/lib/translators/mongo.ts, tests/unit/mongo.spec.ts
Internal implementation of the mongo join translator requires a variable
name from each join column. Rules on variables names implies that
they cannot contain spaces an other non simple characters. Therefore, we
need to replace them by valid ones in the variable name.
=> fix(mongo): join on column names with invalid characters

.storybook/bundle.ts, CHANGELOG.md, src/components/ConditionsEditor/ConditionsGroup.vue, src/components/convert-if-then-else-to-human-format.ts, src/components/stepforms/IfThenElseStepForm.vue, src/components/stepforms/widgets/IfThenElseWidget.vue, src/lib/steps.ts, src/styles/_variables.scss, stories/ifthenelse-widget.js, tests/unit/convert-if-then-else-to-human-format.spec.ts, tests/unit/ifthenelse-widget.spec.ts
=> Update IF...THEN...ELSE widget

CHANGELOG.md, src/components/stepforms/AppendStepForm.vue, src/components/stepforms/DomainStepForm.vue, src/components/stepforms/JoinStepForm.vue, src/lib/steps.ts, src/main.ts, src/store/getters.ts, src/store/state.ts, src/store/utils/dereference-pipeline.ts, tests/unit/dereference-pipeline.spec.ts, tests/unit/store.spec.ts
Also, the join and append step can make a reference to a domain
TODO:
=> Pipeline can start by a reference to an other Pipeline

CHANGELOG.md, package.json, src/components/stepforms/widgets/VariableInput/VariableInput.vue, src/styles/utils/v-tooltip.scss, stories/variable.js, tests/unit/variable-input.spec.ts, yarn.lock
Check behaviour here: https://dashboard.featurepeek.com/peek/jw0h9n53#/?path=/story/inputs-with-variables--wrapping-a-text-input
Display a tooltip with variable value, on variable tag hovering.
=> feat(variableInput): display value as tooltip on hover

.storybook/bundle.ts, CHANGELOG.md, src/components/stepforms/widgets/Autocomplete.vue, src/components/stepforms/widgets/VariableInput/VariableInput.vue, stories/variable.js, tests/unit/autocomplete-widget.spec.ts, tests/unit/variable-input.spec.ts
Allow to use variables in Autocomplete Widget.
Move variable toggle button when parent has arrow
Disable multiselect when choosing a variable
=> feat: add variableInput to Autocomplete widget

.storybook/bundle.ts, .storybook/main.js, src/components/stepforms/FilterStepForm.vue, src/components/stepforms/widgets/FilterSimpleCondition.vue, src/components/stepforms/widgets/VariableInput/VariableInput.vue, stories/stepforms/filter-stepform.js, stories/widgets/index.js
Enable availableVariables store usage in filterStep
=> feat: use variables in filterStep

src/components/Pipeline.vue, src/components/Step.vue, src/lib/labeller.ts, tests/unit/labeller.spec.ts, tests/unit/step.spec.ts
Add a method to replace variable delimiters in pipeline step name
=> feat: remove variable delimiters in pipeline step name

src/components/stepforms/widgets/MultiInputText.vue, src/components/stepforms/widgets/Multiselect.vue, src/components/stepforms/widgets/VariableInputs/VariableTag.vue, src/styles/utils/v-tooltip.scss, tests/unit/multi-input-text-widget.spec.ts, tests/unit/variable-tag.spec.ts
Fix cross position
Fix double trigger event with click
Fix tooltip position when multiinputtext is open
=> fix(variableTag): display variableTag correctly in multiVariableInput

.circleci/config.yml, jest.config.js, package.json, sonar-project.properties, yarn.lock
Let's see if this can provide more insights :)
=> chore(build): add sonar scan to the CI process

src/components/ConditionsEditor/ConditionsGroup.vue
Resolves some Sonar issues:
https://sonarcloud.io/project/issues?id=ToucanToco_weaverbird&issues=AXPtE5ywf24zNDnLP_NT&open=AXPtE5ywf24zNDnLP_NT
=> fix: accessibility for delete icons in filter step form

.storybook/bundle.ts, src/components/stepforms/AddTextColumnStepForm.vue, src/components/stepforms/AggregateStepForm.vue, src/components/stepforms/ArgmaxStepForm.vue, src/components/stepforms/ArgminStepForm.vue, src/components/stepforms/ColumnPicker.vue, src/components/stepforms/ConcatenateStepForm.vue, src/components/stepforms/CumSumStepForm.vue, src/components/stepforms/EvolutionStepForm.vue, src/components/stepforms/FormulaStepForm.vue, src/components/stepforms/IfThenElseStepForm.vue, src/components/stepforms/SplitStepForm.vue, src/components/stepforms/TopStepForm.vue, src/components/stepforms/widgets/Aggregation.vue, src/components/stepforms/widgets/IfThenElseWidget.vue, src/components/stepforms/widgets/JoinColumns.vue, src/components/stepforms/widgets/List.vue, stories/stepforms/add-text-column-stepform.js, stories/stepforms/aggregate-stepform.js, stories/stepforms/argmax-stepform.js, stories/stepforms/argmin-stepform.js, stories/stepforms/concatenate-stepform.js, stories/stepforms/cumsum-stepform.js, stories/stepforms/evolution-stepform.js, stories/stepforms/formula-stepform.js, stories/stepforms/if-then-else-stepform.js, stories/stepforms/split-stepform.js, stories/stepforms/top-stepform.js
**Please review commit by commit, it will be easier to read**
Add variable delimiters and availableVariables possibility in steps widget.
Fix list widget to keep variableInput at width 60%
Fix ifthenelse if value is undefined replace with ''
Add storybook for each step
**To check for review:**
Compare with featurepeek: https://dashboard.featurepeek.com/peek/zy7hl9ke#/?path=/story/step-forms-addtextcolumnstepform--addtextcolumnstepform
**Widget:**
**Steps (fields to add variable):**
=> feat(variables): enable variables usage in all eligible steps

.gitignore, sonar-project.properties
Sonar will be able to indicate us coverage on diff lines, like codecov did
=> chore(tests): pass coverage report to sonar

src/components/stepforms/AppendStepForm.vue, src/components/stepforms/JoinStepForm.vue, src/components/stepforms/widgets/Multiselect.vue, src/components/stepforms/widgets/VariableInputs/VariableTag.vue, tests/unit/append-step-form.spec.ts, tests/unit/join-step-form.spec.ts, tests/unit/multiselect-widget.spec.ts
This PR fixes several object to string issues in the following components:
- JoinStepForm
- AppendStepForm
- MultiSelect
=> fix(multi-select): transform object to string for MultiVariableInput

src/lib/translators/mongo.ts, tests/unit/mongo.spec.ts
Before this PR, we would only keep columns referenced in the step form, whereas we would rather want to add the computation in a new column while keeping track of all the other ones. Now it's the case!
Also, we took the opportunity to simplify the mongo query.
=> cumsum step :: simplify mongo translation and keep track of all columns

src/components/stepforms/widgets/VariableInputs/AdvancedVariableModal.vue, src/components/stepforms/widgets/VariableInputs/VariableChooser.vue, src/components/stepforms/widgets/VariableInputs/VariableInputBase.vue, tests/unit/advanced-variable-modal.spec.ts, tests/unit/variable-chooser.spec.ts, tests/unit/variable-input-base.spec.ts
Start at commit : https://github.com/ToucanToco/weaverbird/commit/753e517b2489a67465ef770ea1322f43757d4ed3
Please review add advanced variable option first : https://github.com/ToucanToco/weaverbird/pull/613
- Add a new component AdvancedVariableModal to create an advanced variable
- Open it when clicking on Advanced variable option of VariableChooser
=> feat(variables): add advanced variable modal

src/components/stepforms/widgets/Autocomplete.vue, src/components/stepforms/widgets/InputText.vue, src/components/stepforms/widgets/MultiVariableInput.vue, src/components/stepforms/widgets/VariableInput.vue, src/components/stepforms/widgets/VariableInputs/AdvancedVariableModal.vue, tests/unit/advanced-variable-modal.spec.ts
- Add inputs to advanced variable modal and style it
:information_source: As we call component in the modal, we include a circular depency that we fixed with : 
https://fr.vuejs.org/v2/guide/components-edge-cases.html#References-circulaires-entre-composants
=> feat(variables): add advanced variable modal inputs

src/components/stepforms/widgets/MultiInputText.vue, src/components/stepforms/widgets/Multiselect.vue
- Fix position of button picker for variable in multiselect and multiinputtext
- Fix oldValue issue can be undefined at first (so value is never apply )
=> fix(muti-variable-input): fix button picker style and multiselect pick

src/components/stepforms/widgets/MultiVariableInput.vue, src/components/stepforms/widgets/VariableInput.vue, src/components/stepforms/widgets/VariableInputs/AdvancedVariableModal.vue, src/components/stepforms/widgets/VariableInputs/VariableInputBase.vue, src/components/stepforms/widgets/VariableInputs/VariableTag.vue, stories/variable.js, tests/unit/advanced-variable-modal.spec.ts, tests/unit/multi-variable-input.spec.ts, tests/unit/variable-input-base.spec.ts, tests/unit/variable-input.spec.ts, tests/unit/variable-tag.spec.ts
Add specific class tag for advanced variable
Add advanced variable to input value when saving
=> feat(advanced-variable): save advanced variable

playground/app.js
Add variables example to test variables in playground
=> chore(playground): add variables to playground

tests/unit/multiselect-widget.spec.ts
Coverage failed due to uncovered condition
=> chore(sonar): fix missing cover condition

src/components/stepforms/widgets/VariableInputs/AdvancedVariableModal.vue
=> fix(advanced-variable-modal): remove style of code editor

src/components/FilterEditor.vue, src/components/stepforms/AddTextColumnStepForm.vue, src/components/stepforms/AggregateStepForm.vue, src/components/stepforms/ArgmaxStepForm.vue, src/components/stepforms/ArgminStepForm.vue, src/components/stepforms/ColumnPicker.vue, src/components/stepforms/ConcatenateStepForm.vue, src/components/stepforms/CumSumStepForm.vue, src/components/stepforms/EvolutionStepForm.vue, src/components/stepforms/FilterStepForm.vue, src/components/stepforms/FormulaStepForm.vue, src/components/stepforms/IfThenElseStepForm.vue, src/components/stepforms/RankStepForm.vue, src/components/stepforms/SplitStepForm.vue, src/components/stepforms/TopStepForm.vue, src/components/stepforms/WaterfallStepForm.vue, src/components/stepforms/widgets/Aggregation.vue, src/components/stepforms/widgets/Autocomplete.vue, src/components/stepforms/widgets/FilterSimpleCondition.vue, src/components/stepforms/widgets/IfThenElseWidget.vue, src/components/stepforms/widgets/InputNumber.vue, src/components/stepforms/widgets/InputText.vue, src/components/stepforms/widgets/JoinColumns.vue, src/components/stepforms/widgets/List.vue, src/components/stepforms/widgets/MultiInputText.vue, src/components/stepforms/widgets/MultiVariableInput.vue, src/components/stepforms/widgets/Multiselect.vue, src/components/stepforms/widgets/VariableInput.vue, src/components/stepforms/widgets/VariableInputs/VariableInputBase.vue, src/components/stepforms/widgets/VariableInputs/VariableTag.vue
Update types default and optionnal for variables
=> fix(variables): fix types

src/lib/steps.ts, src/lib/templating.ts, tests/unit/templating.spec.ts
https://trello.com/c/WbYGUUxA/4308-as-a-conceptor-i-could-use-some-templating-on-my-right-dataset-when-im-using-the-join-vqb-step
=> fix(templating): append and join steps should template dereferenced pipelines

src/components/stepforms/PivotStepForm.vue
=> pivot step: add variables support

CHANGELOG.md, src/lib/templating.ts, tests/unit/templating.spec.ts
=> pivot step: support variables interpolation

src/components/stepforms/JoinStepForm.vue
Everything is in the title. The linter was not happy....
=> Fix types in JoinStepForm.vue

.eslintignore, .github/workflows/ci-server.yml, .github/workflows/storybook.yml, .npmignore, server/.coveragerc, server/.editorconfig, server/.gitignore, server/Makefile, server/README.md, server/poetry.lock, server/pyproject.toml, server/setup.cfg, server/tests/test_hello_world.py, server/weaverbird/hello_world.py
Start the pythonmodule which will contain weaverbird's pandas engine.
=> feat(server): init the python package, which will contains pandas engine

server/README.md, server/playground.py, server/poetry.lock, server/pyproject.toml, server/setup.cfg, server/tests/fixtures/domain_a.csv, server/tests/test_hello_world.py, server/tests/test_pipeline_executor.py, server/weaverbird/hello_world.py, server/weaverbird/pipeline_executor.py, server/weaverbird/steps.py
Starting point of any pipeline :)
I also added a very light playground server, that we later can connect to the front-end playground, as replacement of the mongo-based one.
=> feat(server): domain step in pandas engine

server/weaverbird/steps/filter.py
Conditions can be nested with and/or operators.
This completes the support of the filter step in pandas engine.
=> feat(server): support for logical and/or in filter

server/tests/steps/test_filter.py
A bad rebase removed the tests from the last commit of #674 
Here there are!
=> tests(server): add tests for logical conditions

.dockerignore, Dockerfile, README.md, jest.config.js, package.json, playground/app.js, playground/datastore/sales.csv, playground/server.js, server/playground.py, server/tests/test_pipeline_executor.py, server/weaverbird/pipeline_executor.py, src/lib/dataset/pandas.ts, src/lib/translators/index.ts, src/lib/translators/pandas.ts, src/main.ts, tests/unit/lib/dataset/pandas.spec.ts, tests/unit/translator.spec.ts, yarn.lock
Using `?backend=pandas` switches to the `server/playground.py` server.
=> feat(playground): use optional pandas backend

.github/workflows/docker-playground.yml, .github/workflows/storybook.yml, peek.yml
We should be able to test the playground with `?backend=pandas` in each PR.
=> build(playground): build docker image and publish it for FeaturePeek

server/playground.py
Put any csv file in playground/datastore, and it will be loaded in panda's server.
=> feat(playground): load all csv files in playground/datastore

server/tests/steps/test_filter.py, server/tests/steps/test_join.py, server/tests/steps/test_rename.py, server/weaverbird/pipeline.py, server/weaverbird/pipeline_executor.py, server/weaverbird/steps/__init__.py, server/weaverbird/steps/base.py, server/weaverbird/steps/domain.py, server/weaverbird/steps/filter.py, server/weaverbird/steps/join.py, server/weaverbird/steps/rename.py, server/weaverbird/types.py, src/lib/translators/pandas.ts
Introduces a way for steps to execute subpipelines
=> feat(server): panda join step

.github/workflows/docker-playground.yml
github.head_ref doesn't exist outside pull requests ; it broke the docker image workflow :'(
=> build(playground): works on master

src/components/stepforms/FromDateStepForm.vue, src/lib/translators/mongo.ts, tests/unit/mongo.spec.ts
This PR fixes typos in month complete names.
=> fix(mongo): month index for november 

package.json, src/lib/dataset/index.ts, src/typings/mathjs/index.d.ts, yarn.lock
This PR fixes the doc generation by updating the `typedoc` tool.
=> docs(typedoc): fix the documentation build step

server/playground.py
=> fix(server): playground :: display error messages when using pandas

server/tests/steps/test_ifthenelse.py, server/weaverbird/steps/ifthenelse.py
handled the else if... case. I am a little bit disapointed with my solution that I find not very elegant. The model is almost repeated. We have a weird isinstance(self.else_value, dict).
=> Pandas ifthenelse step: else if

server/tests/steps/test_aggregate.py, server/weaverbird/steps/aggregate.py
This is used in the "load unique values" for each column
=> fix(server): aggregate step can operate on the on columns

server/tests/steps/test_append.py, server/tests/steps/test_join.py, server/weaverbird/steps/append.py, server/weaverbird/steps/combination.py, server/weaverbird/steps/join.py, server/weaverbird/types.py
With this, the python module will be able to execute pipeline whether they are de referenced or not.
=> feat(server): combination steps accept domain names

server/tests/steps/test_aggregate.py, server/tests/steps/test_cumsum.py, server/tests/steps/test_evolution.py, server/tests/steps/test_percentage.py, server/tests/steps/test_rank.py, server/tests/steps/test_rename.py, server/tests/steps/test_rollup.py, server/tests/steps/test_statistics.py, server/tests/steps/test_substring.py, server/weaverbird/steps/aggregate.py, server/weaverbird/steps/base.py, server/weaverbird/steps/cumsum.py, server/weaverbird/steps/evolution.py, server/weaverbird/steps/ifthenelse.py, server/weaverbird/steps/percentage.py, server/weaverbird/steps/rank.py, server/weaverbird/steps/rename.py, server/weaverbird/steps/rollup.py, server/weaverbird/steps/sort.py, server/weaverbird/steps/statistics.py, server/weaverbird/steps/substring.py, server/weaverbird/types.py
Careful of ifthenelse and its multiple inheritance.
It should not be an issue, especially since the alias is only used because 'else' is a reserved keyword. we do not really care about the field name here.
=> all steps, and everything in it can be populated by field name

src/components/ActionMenu.vue, src/components/ActionToolbarButton.vue, src/components/DataTypesMenu.vue, src/components/DataViewer.vue, src/components/DeleteConfirmationModal.vue, src/components/Pagination.vue, src/components/Pipeline.vue, src/components/QueryBuilder.vue, src/components/SearchBar.vue, src/components/Step.vue, src/components/stepforms/StatisticsStepForm.vue, src/components/stepforms/StepFormHeader.vue, src/components/stepforms/widgets/Aggregation.vue, src/components/stepforms/widgets/Autocomplete.vue, src/components/stepforms/widgets/IfThenElseWidget.vue, src/components/stepforms/widgets/InputNumber.vue, src/components/stepforms/widgets/InputText.vue, src/components/stepforms/widgets/JoinColumns.vue, src/components/stepforms/widgets/List.vue, src/components/stepforms/widgets/MultiInputText.vue, src/components/stepforms/widgets/SortColumn.vue, src/styles/utils/v-tooltip.scss
Clean sonar warning from master branch
=> chore: remove sonar warnings

server/tests/test_pipeline_executor.py, server/weaverbird/pipeline_executor.py
To help debugging failing pipelines, I suggest to raise more helpful errors.
On failure, we now indicate:
- the index of the failing step,
- the name of the failing step,
- and the original exception message.
Later, we could improve the exceptions messages inside the steps, on a step-by-step basis.
=> feat(server): raise more helpful error on pipeline failure

server/tests/steps/test_totals.py, server/weaverbird/steps/totals.py
fix(pandas/total): some combination of totals were missing.
=> fix pandas total step: missing results

server/weaverbird/steps/aggregate.py
Better way to concat aggregated columns
=> perf: optimize aggregate step

server/weaverbird/steps/pivot.py
the update to pandas 1.2.0 causes a bug in the pivot table. Cf commit messages
=> chore(server): fixes for Pandas 1.2.0

server/pyproject.toml, server/tests/steps/test_fillna.py, server/tests/steps/test_rename.py, server/tests/steps/test_totals.py, server/tests/test_utils.py, server/weaverbird/conditions.py, server/weaverbird/steps/fillna.py, server/weaverbird/steps/ifthenelse.py, server/weaverbird/steps/join.py, server/weaverbird/steps/rename.py, server/weaverbird/steps/totals.py, server/weaverbird/utils/__init__.py, server/weaverbird/utils/cleaning.py
- handle legacy syntax for rename & fillna steps
- fix re-serialisation for ifthenelse step
- prevent join step to create duplicated column names
=> fix(server): some retrocompatibility fixes

CHANGELOG.md, docs/_docs/tech/steps.md, docs/_docs/user-interface/aggregate.md, docs/_docs/user-interface/rollup.md, docs/_docs/user-interface/totals.md, server/tests/steps/test_aggregate.py, server/weaverbird/steps/aggregate.py, src/components/stepforms/schemas/aggregations.ts, src/components/stepforms/widgets/Aggregation.vue, src/lib/labeller.ts, src/lib/steps.ts, src/lib/translators/mongo.ts, tests/unit/mongo.spec.ts
Impacts the following steps:
- aggregate
- rollup
- totals
=> Add support for count distinct aggregation function

CHANGELOG.md, src/lib/labeller.ts, tests/unit/labeller.spec.ts, tests/unit/step.spec.ts
=> feat(domain step): change label

CHANGELOG.md, package.json, sonar-project.properties, src/components/ConditionsEditor/ConditionsGroup.vue
Remove a CSS rule preventing dropdown display in condition groups/filter step + Patch Release Commit
=> fix(filter step): hidden dropdown

src/components/Step.vue
Implement the new design for the pipeline component. ( No implementation for errors for now, will do it in another PR)
Design:
Before:
After:
=> feat(pipeline): update design to fit guidelines

server/tests/test_pipeline.py, server/weaverbird/pipeline.py, server/weaverbird/steps/base.py
this pr excludes by default None values from .dict().
These None values did trigger some validation error on the front end
=> feat(back): no more None values in step.dict()

server/pyproject.toml, server/tests/test_pipeline_executor.py, server/weaverbird/pipeline_executor.py
This PR is copied from #868 
It also contains a bump of weaverbird to version 0.4.0
=> feat(pipeline executor): pilepineExecutor#execute now returns a detailed report

src/components/ActionToolbarButton.vue, src/components/DataViewer.vue, src/components/DataViewerCell.vue, src/components/Popover.vue, src/components/QueryBuilder.vue, src/components/Step.vue, src/components/stepforms/FilterStepForm.vue, src/components/stepforms/StepFormButtonbar.vue, src/components/stepforms/widgets/Autocomplete.vue, src/components/stepforms/widgets/FilterSimpleCondition.vue, src/components/stepforms/widgets/InputText.vue, src/components/stepforms/widgets/JoinColumns.vue
Add data cy attribute to necessary DOM element
:warning: **IMPORTANT CHOICES:**
* data-cy weaverbird elements are all prefixes with `weaverbird-` to identifiy them
* elements that could be duplicated by external packages (ex: modal or dropdown) are prefixed with `tc-`
* chart elements can't really be data-cy transformed because they use d3, i would add complexity
* external packages (multiselect) are not data-cy as well
Related PRS:
Tucana: https://github.com/ToucanToco/tucana/pull/9973
E2E: ToucanToco/e2e#39
=> chore: add data cy for story create e2e tests

src/components/stepforms/widgets/FilterSimpleCondition.vue
Needed to run the update permission e2e test.
=> test: add data-cy for filter value

CHANGELOG.md, src/lib/translators/empty.ts, src/lib/translators/index.ts, tests/unit/translator.spec.ts
Add a new empty translator that handle only domain step
=> feat(translators): add new empty translator

src/components/Pipeline.vue, tests/unit/pipeline.spec.ts
To ease the life of Mac users.
=> feat(pipeline): handle cmd for copy/pasting + backspace key to delete

server/tests/steps/test_aggregate.py, server/weaverbird/steps/aggregate.py
Issue: https://toucantoco.atlassian.net/browse/ASK-60 
Solution: Enforce unique column names for aggregation column
=> feat(aggregate steps): add unique column names validation

CHANGELOG.md, package.json, server/pyproject.toml, sonar-project.properties
Revert changes from: https://github.com/ToucanToco/weaverbird/pull/938 
And bump server version to 0.4.3
=> chore(version): bump server 0.4.3

README.md
Update README for backend release process.
=> doc: add backend release how to

server/pyproject.toml, server/weaverbird/backends/pandas_executor/steps/__init__.py
Oupsy, this would have been detected with all the tests specs ^^
=> fix(server): pandas step names case

docs/_docs/tech/python-package.md
Mainly consists of giving a toy example (mongo translator).
=> Doc add a section "howto add a new translator"

CHANGELOG.md, src/lib/translators/mongo4.ts, tests/unit/mongo.spec.ts
=> feat(to-date-step): implement "try to guess" with "%Y"

.github/workflows/docker-playground.yml, .github/workflows/storybook.yml, peek.yml
=> build: deactivate featurepeek

server/pyproject.toml, server/tests/steps/sql_translator/test_filter.py, server/tests/steps/sql_translator/test_table.py, server/tests/steps/sql_translator/utils/test_query_transformation.py, server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
Fix issues spotted during UAT.
https://trello.com/c/H7tzJFOw/1088-5-snowflake-vqb-translator-as-an-app-maker-i-can-filter-using-snowflake-vqb-4
=> fix: filter step match & arithmetic comparisons for strings

server/pyproject.toml
chore(versions): backend 0.5.5
=> chore(versions): backend 0.5.5

server/tests/steps/sql_translator/test_aggregate.py, server/tests/steps/sql_translator/test_filter.py, server/tests/steps/sql_translator/test_select.py, server/tests/steps/sql_translator/test_table.py, server/tests/steps/sql_translator/utils/test_query_transformation.py, server/tests/test_pipeline_translator.py, server/weaverbird/backends/sql_translator/steps/__init__.py, server/weaverbird/backends/sql_translator/steps/aggregate.py, server/weaverbird/backends/sql_translator/steps/filter.py, server/weaverbird/backends/sql_translator/steps/select.py, server/weaverbird/backends/sql_translator/steps/table.py, server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py, server/weaverbird/backends/sql_translator/types.py
Voir: https://toucantoco.atlassian.net/wiki/spaces/TTA/pages/3087466529/PAT+234+bis+--+R+cup+ration+passage+des+colonnes+entre+steps#R%C3%A9sultat-impl%C3%A9mentation-%E2%80%9CPOC%E2%80%9D
=> feat(query metadata manager): add query metadata manager

server/pyproject.toml, server/tests/steps/sql_translator/test_aggregate.py, server/tests/steps/sql_translator/test_filter.py, server/tests/steps/sql_translator/test_select.py, server/tests/steps/sql_translator/test_table.py, server/tests/steps/sql_translator/utils/test_query_transformation.py, server/tests/test_pipeline_translator.py, server/weaverbird/backends/sql_translator/sql_pipeline_translator.py, server/weaverbird/backends/sql_translator/steps/__init__.py, server/weaverbird/backends/sql_translator/steps/aggregate.py, server/weaverbird/backends/sql_translator/steps/filter.py, server/weaverbird/backends/sql_translator/steps/select.py, server/weaverbird/backends/sql_translator/steps/table.py, server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py, server/weaverbird/backends/sql_translator/types.py
add a params to have a describe method from connectors & use it in table step
=> feat(sql pipeline columns): add a params to have a describe method from connectors & use it in table step

server/Makefile
- Added the installation of poetry in `make install` inside the `Makefile`
=> fix(makefile): adding poetry installation

server/tests/steps/sql_translator/test_rename.py, server/weaverbird/backends/sql_translator/steps/__init__.py, server/weaverbird/backends/sql_translator/steps/rename.py
- Added the `rename` step in sql_translator.
- Wrote tests of `translate_rename`.
=> feat(vqb-step): added rename translator step

server/tests/steps/sql_translator/test_sort.py, server/weaverbird/backends/sql_translator/steps/__init__.py, server/weaverbird/backends/sql_translator/steps/sort.py
- Added the `sort` step in sql_translator.
- Wrote tests of `translate_sort`.
=> feat(vqb-step): added sort translator step

.storybook/bundle.ts, src/components/Tabs.vue, stories/tabs.js, tests/unit/tabs.spec.ts
=> feat(tabs): add new tabs component

server/tests/steps/sql_translator/test_rename.py, server/tests/steps/sql_translator/test_sort.py, server/weaverbird/backends/sql_translator/steps/rename.py, server/weaverbird/backends/sql_translator/steps/sort.py
=> fix(vqb-step): fix rename/sort step [KeyError - table1]

src/components/FilterEditor.vue, src/components/stepforms/convert-filter-step-tree.ts, src/components/stepforms/widgets/FilterSimpleCondition.vue, src/lib/helpers.ts, tests/unit/filter-simple-condition-widget.spec.ts, tests/unit/helpers.spec.ts
We want to have date input for every date column now, we can remove the feature flag security to always display the date input in this case.
=> chore(esjson): remove all occurencies to esjson

server/pyproject.toml
- VQB ifthenelse step
- VQB convert(cast) step
Interface | Weaverbird (local pc) | Snowflake (query history)
--- | --- | --- 
Screenshot | ![Screenshot from 2021-08-16 15-21-06](https://user-images.githubusercontent.com/22576758/129571565-c48dadaa-21ab-48c7-ba20-5572dd8f2a53.png) | ![Screenshot from 2021-08-16 15-28-40](https://user-images.githubusercontent.com/22576758/129571597-5eac84ac-26f0-4fcf-a5d5-72a757b04ee3.png)
=> chore(bump): from version 0.5.8 to 0.5.9

server/pyproject.toml, server/tests/steps/sql_translator/conftest.py, server/tests/steps/sql_translator/test_aggregate.py, server/tests/steps/sql_translator/test_convert.py, server/tests/steps/sql_translator/test_filter.py, server/tests/steps/sql_translator/test_ifthenelse.py, server/tests/steps/sql_translator/test_lowercase.py, server/tests/steps/sql_translator/test_rename.py, server/tests/steps/sql_translator/test_select.py, server/tests/steps/sql_translator/test_sort.py, server/tests/steps/sql_translator/test_text.py, server/tests/steps/sql_translator/test_uppercase.py, server/tests/steps/sql_translator/utils/test_query_transformation.py, server/tests/test_pipeline_translator.py, server/weaverbird/backends/sql_translator/steps/aggregate.py, server/weaverbird/backends/sql_translator/steps/convert.py, server/weaverbird/backends/sql_translator/steps/filter.py, server/weaverbird/backends/sql_translator/steps/ifthenelse.py, server/weaverbird/backends/sql_translator/steps/lowercase.py, server/weaverbird/backends/sql_translator/steps/rename.py, server/weaverbird/backends/sql_translator/steps/select.py, server/weaverbird/backends/sql_translator/steps/sort.py, server/weaverbird/backends/sql_translator/steps/table.py, server/weaverbird/backends/sql_translator/steps/text.py, server/weaverbird/backends/sql_translator/steps/uppercase.py, server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py, server/weaverbird/backends/sql_translator/types.py
* Add a query metadata dict in metadata manager
* Update the related metadata manager's method
* Keep the tables metadata, dict. It will be store tables metadata during table step & join step.
=> feat: update metadata storage and usage in steps

server/tests/steps/sql_translator/test_lowercase.py, server/tests/steps/sql_translator/test_replace.py, server/tests/steps/sql_translator/test_uppercase.py, server/weaverbird/backends/sql_translator/steps/__init__.py, server/weaverbird/backends/sql_translator/steps/replace.py
- vqb updates
- added replace step
=> feat(vqb): added step replace + unit tests

server/pyproject.toml, server/setup.cfg, server/tests/steps/sql_translator/test_formula.py, server/tests/steps/sql_translator/utils/test_query_transformation.py, server/weaverbird/backends/sql_translator/steps/__init__.py, server/weaverbird/backends/sql_translator/steps/formula.py, server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
=> feat: add formula step

server/weaverbird/backends/sql_translator/steps/convert.py
- a fix on a redumpdant unecessary code
=> fix(vqb): remove unecesary code from convert step

server/pyproject.toml
- Step text to date step
- Step formula
- e2e
=> chore(bump): upgrade version to 0.6.6

.storybook/bundle.ts, src/components/stepforms/widgets/DateComponents/RelativeDateForm.vue, src/components/stepforms/widgets/DateComponents/RelativeDateRangeForm.vue, src/lib/dates.ts, stories/dates/relative-date-form.js, stories/dates/relative-date-range-form.js, tests/unit/relative-date-form-widget.spec.ts, tests/unit/relative-date-range-form-widget.spec.ts
need to review: https://github.com/ToucanToco/weaverbird/pull/988 first
Design:
Usage:
=> feat(relative-date-range-form): add new component

CHANGELOG.md
Forgotten in https://github.com/ToucanToco/weaverbird/pull/1007
=> chore(changelog): add note about trim step

.storybook/bundle.ts, src/components/Tabs.vue, src/components/stepforms/widgets/DateComponents/NewDateInput.vue, src/lib/dates.ts, stories/dates/new-date-input.js, tests/unit/lib/dates.spec.ts, tests/unit/new-date-input.spec.ts
:warning: Need to review: https://github.com/ToucanToco/weaverbird/pull/994 first
Design:
Usage:
=> feat(new-date-input): add a new component to select a date

.github/workflows/ci-ui.yml, jest.config.js, package.json, sonar-project.properties, yarn.lock
This should remove this warning in Sonar:
and restore coverage metric:
=> build(sonar): fix sonar analysis

CHANGELOG.md, package.json
=> chore: bump v.0.56.0

server/pyproject.toml
- UniqueGroups Step
- TopN rows Step
=> chore(bump): from version 1.0.0.a1 to 1.0.0.a2

server/pyproject.toml
=> build(server): v0.7.0

src/lib/translators/snowflake.ts
- VQB snowflake (front):
- Added Percentage step to the Snowflake translator
=> feat(vqb): added percentage step on snowflake translator

server/pyproject.toml, server/tests/backends/fixtures/percentage/simple.json, server/tests/steps/sql_translator/test_percentage.py, server/weaverbird/backends/sql_translator/steps/__init__.py, server/weaverbird/backends/sql_translator/steps/percentage.py
- VQB snowflake (back):
- Added percentage step (unit tests + fixtures)
PS : this is just a redo from [1040](https://github.com/ToucanToco/weaverbird/pull/1040) due to a strange linter issue with mypy
=> feat(vqb): added percentage step

CHANGELOG.md, docs/_docs/user-interface/pivot.md, package.json, server/pyproject.toml, server/tests/backends/fixtures/pivot/simple.json, server/tests/fixtures/fixtures_templating/pivot.json, server/tests/steps/sql_translator/test_pivot.py, server/tests/steps/test_pivot.py, server/weaverbird/backends/sql_translator/metadata.py, server/weaverbird/backends/sql_translator/steps/__init__.py, server/weaverbird/backends/sql_translator/steps/pivot.py, server/weaverbird/pipeline/steps/pivot.py, sonar-project.properties, src/components/stepforms/PivotStepForm.vue, src/components/stepforms/schemas/pivot.ts, src/lib/steps.ts, tests/unit/labeller.spec.ts, tests/unit/mongo.spec.ts, tests/unit/pivot-step-form.spec.ts, tests/unit/templating.spec.ts
=> feat(sql pivot): add pivot step & unit tests

server/pyproject.toml
Bump backend to 0.7.5
- fixes on SQL Pivot, Unpivot, Join steps
- Append Step
- Concatenate Step
- Date Extract Step.
=> chore(backend version): 0.7.5

CHANGELOG.md, package.json, sonar-project.properties
=> chore(front version): 0.60.3

server/tests/steps/sql_translator/test_top.py, server/weaverbird/backends/sql_translator/steps/top.py
- top-nrows step was not displaying other columns even without the group-by
=> fix(vqb): top-n-rows

CHANGELOG.md, package.json, server/pyproject.toml, server/tests/steps/sql_translator/test_delete.py, server/weaverbird/backends/sql_translator/steps/__init__.py, server/weaverbird/backends/sql_translator/steps/delete.py, sonar-project.properties, src/lib/translators/snowflake.ts
- Adding the "Delete" Step to SQL VQB. 
Good news: no need to adapt the integration test, it works the same as for Pandas :).
=> feat(sql vqb): delete step

server/tests/backends/fixtures/split/simple.json, server/tests/steps/sql_translator/test_split.py, server/weaverbird/backends/sql_translator/steps/__init__.py, server/weaverbird/backends/sql_translator/steps/split.py, src/lib/translators/snowflake.ts
=> feat(vqb): added split step to snowflake

server/tests/backends/fixtures/fillna/date.json, server/tests/backends/fixtures/fillna/fillinteger.json, server/tests/backends/fixtures/fillna/simple.json, server/tests/steps/sql_translator/test_fillna.py, server/tests/steps/sql_translator/utils/test_query_transformation.py, server/weaverbird/backends/sql_translator/steps/__init__.py, server/weaverbird/backends/sql_translator/steps/fillna.py, server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py, src/lib/translators/snowflake.ts
https://user-images.githubusercontent.com/71276735/132383762-40b9bbc1-1acc-4b4f-a734-27e72fbbc167.mp4
* Add sql vqb fillna step 
weird behavior with dates, as the front end directly fills null date values.
=> feat(sql vqb): add fillna step

CHANGELOG.md, package.json, server/pyproject.toml, sonar-project.properties
- SQL VQB [Snowflake]: Rank step
- SQL VQB [Snowflake]: Substring step
- SQL VQB [Snowflake]: Split Column step
- SQL VQB [Snowflake]: Fill Null step
=> chore(bump): back 0.7.7->0.7.8, front 0.60.4->0.60.5

server/tests/backends/fixtures/rank/pandas.json, server/tests/backends/fixtures/rank/snowflake.json, server/tests/steps/sql_translator/test_rank.py, server/weaverbird/backends/sql_translator/steps/aggregate.py, server/weaverbird/backends/sql_translator/steps/rank.py, server/weaverbird/backends/sql_translator/steps/top.py, server/weaverbird/backends/sql_translator/steps/utils/aggregation.py, server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
To get the same results as the Pandas Rank Step we need to use `PARTITION BY` Keyword in the Query built.
=> fix(sql vqb): fix sql vqb rank step + unit tests

server/tests/backends/sql_translator/test_snowflake_translator_steps.py, server/tests/steps/sql_translator/test_aggregate.py, server/tests/steps/sql_translator/utils/test_query_transformation.py, server/weaverbird/backends/sql_translator/steps/aggregate.py, server/weaverbird/backends/sql_translator/steps/utils/aggregation.py, server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
- Snowflake VQB  :
- fix columns metadatas problems
- fix the keeping of granularity on aggregate step
- writing unittests for keep-granularity option
- fix collision on snowflake fixtures test when creating table names (allowing multiple tests instances running at the same time)
=> fix(vqb): fix granularity aggregate + unit tests

server/tests/backends/fixtures/duplicate/simple.json, server/tests/steps/sql_translator/test_duplicate.py, server/weaverbird/backends/sql_translator/metadata.py, server/weaverbird/backends/sql_translator/steps/__init__.py, server/weaverbird/backends/sql_translator/steps/duplicate.py, server/weaverbird/backends/sql_translator/steps/unpivot.py, src/lib/translators/snowflake.ts
=> feat(vqb): added duplicate step

server/tests/backends/fixtures/argmax/simple.json, server/tests/backends/fixtures/argmax/with_group.json, server/tests/backends/fixtures/argmin/simple.json, server/tests/backends/fixtures/argmin/with_group.json, server/tests/steps/sql_translator/test_argmax.py, server/tests/steps/sql_translator/test_argmin.py, server/weaverbird/backends/sql_translator/steps/__init__.py, server/weaverbird/backends/sql_translator/steps/argmax.py, server/weaverbird/backends/sql_translator/steps/argmin.py, src/lib/translators/snowflake.ts
=> feat(vqb): Snowflake added argmin + argmax steps

CHANGELOG.md, package.json, server/pyproject.toml, sonar-project.properties
chore: front 0.60.7 & back 0.8.1 release
=> chore: front 0.60.7 & back 0.8.1 release

server/pyproject.toml
- Fix join on two tables with the same name
=> chore(bump): back-0.8.3

src/components/DeleteConfirmationModal.vue, src/components/Pipeline.vue, src/components/Step.vue, src/components/stepforms/StepFormHeader.vue
Add data-cy for e2e tests on a set of needed elements
=> chore: add data-cy to needed elements for e2e tests

src/main.ts
=> chore(dates): export date range and new input date components

src/components/stepforms/widgets/DateComponents/DateRangeInput.vue
=> style(ui): remove background on DateRangeInput reset btn TCTC-1097

server/tests/backends/fixtures/replace/snowflake_simple.json, server/tests/steps/sql_translator/test_replace.py, server/weaverbird/backends/sql_translator/steps/replace.py
=> fix(sql): replace step work w & w/ quotes [TCTC-1246]

server/tests/backends/fixtures/HOWTO-create-fixtures.md, server/tests/backends/fixtures/filter/dates.json, server/tests/backends/pandas_executor/test_pandas_executor_steps.py, server/tests/backends/sql_translator/test_snowflake_translator_steps.py, server/tests/backends/sql_translator/test_sql_translator_steps.py, server/tests/steps/sql_translator/test_filter.py, server/tests/utils.py, server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
=> fix(sql): fix filter step on date [TCTC-1242]

server/setup.cfg, server/tests/utils.py
=> feat(release): from 0.8.8 to 0.8.9

src/assets/FA-ICONS.ts, src/components/stepforms/widgets/DateComponents/CustomVariableList.vue, src/components/stepforms/widgets/DateComponents/DateRangeInput.vue, src/components/stepforms/widgets/DateComponents/NewDateInput.vue, src/components/stepforms/widgets/VariableInputs/VariableChooser.vue, src/components/stepforms/widgets/VariableInputs/VariableList.vue, src/components/stepforms/widgets/VariableInputs/VariableTag.vue, tests/unit/custom-variable-list.spec.ts, tests/unit/new-date-input.spec.ts, tests/unit/variable-chooser.spec.ts, tests/unit/variable-list.spec.ts, tests/unit/variable-tag.spec.ts
Didn't change other components behaviour
=> feat(new-date-input): enable to use advanced variable TCTC-1195

playground/Dockerfile-mongo, playground/init-mongo/01-import-files.sh, playground/init-mongo/02-adjust-types.js
Necessary for working with relative dates.
This will be deployed on render, like the playground server.
=> feat(playground): provide a mongo 5 container with data from playground TCTC-1197

playground/app.js, src/lib/templating.ts
Fix the exampelInterpolateFunc which were not iterating over arrays and
objects
=> feat(playground): add dates variables to test in playground TCTC-1196

server/static
So the webserver works in development
=> fix(playground): add symlink with static files

playground/dist/index.html
Hi Toucan,
Here a some UI improvements :
- Move the debug panel to a separated sheet.
- Move the debug button to a toolbar.
I don't have access to the main product components. So the code may be different than the main product ;)
=> feat(playground): improve the debug panel display

src/components/stepforms/widgets/DateComponents/NewDateInput.vue
I forgot to had some verificaton during the refacto
=> fix(new-date-input): add relative date secruity where missing TCTC-1321

src/lib/translators/mongo.ts, tests/unit/mongo.spec.ts
- include external methods inside the mongo class
- IfThenElse tests updated with the dateTrunc loggic
=> fix(relativDate): fix on ifthenElse + small refacto [TCTC-1322]

playground/app.js, server/setup.cfg, server/src/weaverbird/backends/pandas_executor/steps/utils/condition.py, server/src/weaverbird/backends/pandas_executor/steps/utils/dates.py, server/src/weaverbird/backends/sql_translator/steps/utils/query_transformation.py, server/tests/backends/fixtures/filter/dates_from_until.json, server/tests/backends/fixtures/filter/dates_from_until_strip_hours.json, server/tests/backends/fixtures/filter/relative_dates.json, server/tests/backends/pandas_executor/utils/test_dates.py
Implement the same functionnality than #1194 #1195 #1202 for pandas and SQL backends
Checklist:
=> feat(sql,pandas): support from/until operators (comparison of days) TCTC-906 TCTC-907

server/setup.cfg
Includes support of from/until operators for sql and pandas
=> chore(server): v0.9.0

src/components/stepforms/widgets/DateComponents/NewDateInput.vue, tests/unit/new-date-input.spec.ts
Add analytics when saving a relative date for date filtering
=> feat(new-date-input): add analytics when saving a relative date TCTC-899

CHANGELOG.md, docs/_docs/tech/sql-pipeline.md, playground/app.js, playground/dist/index.html, server/CHANGELOG.md, server/playground.py, server/setup.cfg, server/src/weaverbird/backends/sql_translator/steps/pivot.py, server/src/weaverbird/backends/sql_translator/steps/utils/query_transformation.py, server/src/weaverbird/backends/sql_translator/types.py, server/tests/backends/sql_translator/test_snowflake_translator_steps.py, server/tests/steps/sql_translator/test_pivot.py
I added the test data to a demo Snowflake account of ours, and set up the playground to be ablt to use it.
It's quite rough for now, but a good first step.
Among the known issues are the dates not transmitted correctly, which will be fixed in a second PR.
=> feat(playground): support snowflake SQL TCTC-906

server/CHANGELOG.md, server/setup.cfg
- SQL translator: date-extract step:
- first day of ISO week (monday)
- first day of week (sunday)
- first day of previous ISO week (monday)
- first day of previous week (sunday)
- first day of previous month
- first day of previous quarter
- first day of previous year
- day of week (sunday to sunday)
- previous ISO week number (monday to monday)
- previous day
- milliseconds
=> chore(server): v0.10.1

server/tests/backends/fixtures/comparetext/simple.json, server/tests/utils.py
Like dateextract tests because they were called date_extract in python
files of backends...
=> test(server): some tests were not played

src/main.ts
export method to use it outside of weaverbird
=> chore: export date range to string method TCTC-1398

src/assets/FA-ICONS.ts, src/components/PreviewSourceSubset.vue, src/components/Step.vue
=> fix(preview-source-subset): use correct icon and label TCTC-1339

src/components/stepforms/widgets/InputText.vue, src/components/stepforms/widgets/Multiselect.vue, src/components/stepforms/widgets/TotalDimensions.vue
Making placeholders in step forms appear different than actual values.
https://toucantoco.atlassian.net/browse/TCTC-1380 
Well ... css
=> fix(stepforms): change placeholders color [TCTC-1380]

CHANGELOG.md, package.json, sonar-project.properties, src/components/stepforms/widgets/TotalDimensions.vue
An other release ! 
0.79.4 for fix on placeholders colors in step forms.
=> chore(version): 0.79.4

server/CHANGELOG.md, server/setup.cfg
=> chore(version): bump weaverbird 0.10.2

CHANGELOG.md, src/lib/backend.ts, src/store/getters.ts, src/store/mutations.ts, src/store/state.ts, tests/unit/store.spec.ts
Full explanation in commits :wink:
=> refactor(store): refine code comments and removed unused stuff

server/tests/backends/fixtures/cumsum/simple.json, server/tests/backends/fixtures/cumsum/with_groups.json, server/tests/backends/fixtures/cumsum/with_multiple_values.json
=> test(mysql, pgsql): exclude cumsum from test cases

src/components/DataViewer.vue, src/components/DatePicker/Calendar.vue, src/components/Pagination.vue, src/components/PreviewSourceSubset.vue, src/components/stepforms/widgets/DateComponents/CustomVariableList.vue, src/components/stepforms/widgets/DateComponents/DateRangeInput.vue, src/components/stepforms/widgets/DateComponents/NewDateInput.vue, src/components/stepforms/widgets/DateComponents/RelativeDateForm.vue
Only add data-cy in order to add e2e tests for missing features
=> chore(ui): add data cy for date components, pagination and source subset preview TCTC-1515

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/join.py, server/src/weaverbird/backends/mongo_translator/utils.py, server/src/weaverbird/exceptions.py, server/tests/backends/fixtures/join/inner.json, server/tests/backends/fixtures/join/left.json, server/tests/backends/fixtures/join/left_outer.json, server/tests/backends/mongo_translator/test_mongo_translator_steps.py
This PR aims to replicate mongo translator's join step logic from frontend to backend.
=> feat(python mongo join): Join Step [TCTC-1993]

server/CHANGELOG.md, server/setup.cfg, server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/append.py, server/src/weaverbird/backends/mongo_translator/steps/join.py, server/tests/backends/fixtures/append/simple.json, server/tests/backends/fixtures/append/with_domain_name.json, server/tests/backends/mongo_translator/test_mongo_translator_steps.py
* Move Append step from front mongo translator to Back.
=> feat:python mongo append step [TCTC-1829]

server/CHANGELOG.md, server/setup.cfg, server/src/weaverbird/backends/mongo_translator/steps/append.py, server/src/weaverbird/backends/mongo_translator/steps/join.py, server/tests/backends/fixtures/append/domain_name_only.json, server/tests/backends/fixtures/join/domain_name_only.json
Append & Join steps of mongo back translator. should handle the domain name provided as a str directly
=> fix(mongo back): fix append & join to handle domain step as str [TCTC-1829]

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/rename.py, server/tests/backends/fixtures/rename/edge_case.json, server/tests/backends/fixtures/rename/multiple.json, server/tests/backends/fixtures/rename/simple.json
=> feat(mongo back): rename step TCTC-1830

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/aggregate.py, server/src/weaverbird/backends/mongo_translator/steps/append.py, server/src/weaverbird/backends/mongo_translator/steps/argmax.py, server/src/weaverbird/backends/mongo_translator/steps/argmin.py, server/src/weaverbird/backends/mongo_translator/steps/domain.py, server/src/weaverbird/backends/mongo_translator/steps/filter.py, server/src/weaverbird/backends/mongo_translator/steps/join.py, server/src/weaverbird/backends/mongo_translator/steps/rename.py, server/src/weaverbird/backends/mongo_translator/steps/text.py, server/src/weaverbird/backends/mongo_translator/steps/types.py, server/tests/backends/fixtures/aggregate/count.json, server/tests/backends/fixtures/aggregate/count_distinct.json, server/tests/backends/fixtures/aggregate/first.json, server/tests/backends/fixtures/aggregate/keep_original_granularity_empty_on.json, server/tests/backends/fixtures/aggregate/last.json, server/tests/backends/fixtures/aggregate/with_original_granularity.json, server/tests/backends/fixtures/aggregate/with_original_granularity_multiple_aggregations.json, server/tests/backends/fixtures/aggregate/with_original_granularity_multiple_aggregations_multiple_columns.json, server/tests/backends/fixtures/aggregate/without_on.json, server/tests/backends/fixtures/rename/simple.json
Create the aggregate step in Mongo's backend translator.
=> feat(mongo back): aggregate step mongo back TCTC-1830

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/sort.py, server/tests/backends/fixtures/sort/simple.json
Nothing to add from the title.
=> feat(mongo): sort step TCTC-1831

server/src/weaverbird/backends/sql_translator/steps/append.py
There was an import error, the path was wrong
=> fix(sql): import error in append step

server/tests/backends/sql_translator/test_snowflake_translator_steps.py
Snowflake tests are really slow, this is attempt to speed them up a bit.
=> tests(snowflake): avoid connecting multiple times

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/unpivot.py, server/tests/backends/fixtures/unpivot/pandas.json
Implementation of the `unpivot` step in mongo backend translator (logic copied from `translators/mongo.ts`)
=> feat(mongo back): unpivot step

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/uniquegroups.py, server/tests/backends/fixtures/uniquegroups/simple.json
=> feat(mongo_translator): Implement uniquegroups step

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/select.py, server/tests/backends/fixtures/select/simple.json
Mongo-Back KeepColumn (a.k.a select) Step from `../src/lib/translators/mongo.ts`
=> feat(mongo back): KeepColumn (a.k.a select) Step [TCTC-1832]

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/replace.py, server/tests/backends/fixtures/replace/simple.json
Mongo-Back Replace Step from `../src/lib/translators/mongo.ts`
=> feat(mongo back): replace Step [TCTC-1832]

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/rank.py, server/tests/backends/fixtures/rank/group_by.json, server/tests/backends/fixtures/rank/simple.json
Implemented the rank step in python for the mongo-translator, following the logic from `./src/lib/translators/mongo.ts`
=> feat(python-mongo-translator): rank step [TCTC-2656]

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/substring.py, server/tests/backends/fixtures/substring/simple.json
Implemented the substring step in python for the mongo-translator, following the logic from `./src/lib/translators/mongo.ts`
=> feat(python-mongo-translator): extract substring step [TCTC-2656]

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/cumsum.py, server/tests/backends/fixtures/cumsum/simple.json, server/tests/backends/fixtures/cumsum/with_groups.json, server/tests/backends/fixtures/cumsum/with_multiple_values.json
=> feat(mongo_translator): Implement cumsum step TCTC-2694

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/moving_average.py, server/tests/backends/fixtures/movingaverage/simple.json, server/tests/backends/fixtures/movingaverage/with_groups.json
=> feat(mongo_translator): Implement moving average step TCTC-2694

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/totals.py, server/tests/backends/fixtures/totals/simple-pandas.json, server/tests/backends/fixtures/totals/simple.json
Just copy logic from js mongo translator.
=> feat(mongo_translator): Implement totals step [TCTC-2658]

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/rollup.py, server/tests/backends/fixtures/rollup/groupby.json, server/tests/backends/fixtures/rollup/no_aggregation.json, server/tests/backends/fixtures/rollup/simple.json, server/tests/backends/mongo_translator/test_mongo_translator_steps.py
Copy logic from mongo js translator.
:information_source: I had to make mongo translator test agnostic to the order of columns.
=> feat(mongo_translator): implement rollup step [TCTC-2658]

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/duration.py, server/tests/backends/fixtures/duration/simple.json
Just copy logic from mongo js translator.
=> feat(mongo_translator): implement duration step [TCTC-2658]

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/statistics.py, server/tests/backends/fixtures/statistics/all.json
=> feat(mongo_translator): Implement statistics step TCTC-2694

server/src/weaverbird/backends/mongo_translator/steps/__init__.py, server/src/weaverbird/backends/mongo_translator/steps/trim.py, server/tests/backends/fixtures/trim/multiple_columns.json, server/tests/backends/fixtures/trim/single_column.json
Implemented the trim step in python for the mongo-translator, following the logic from `./src/lib/translators/mongo4.ts`
=> feat(python-mongo-translator): added trim step [TCTC-2695]

package.json, src/components/stepforms/TopStepForm.vue, tests/unit/top-step-form.spec.ts, yarn.lock
https://user-images.githubusercontent.com/18406791/169989322-57532939-2c6f-426d-a8b0-2a798bbf8a1d.mov
https://user-images.githubusercontent.com/18406791/169988823-c0c61362-0243-4204-80e1-33e6903eb7f0.mov
=> feat(steps): use 'desc' as default order in top step

server/src/weaverbird/backends/pandas_executor/pipeline_executor.py
Added a detail log monitor for our pandas steps.
Related to this discovery : https://toucantoco.atlassian.net/wiki/spaces/TTA/pages/3529113648/Measuring+our+Success#Format---What-we-would-like-to-measure-(KPI-and-dimensions)
By adding those extras values, we will be able to filter  well our logs on kibana related to a step name, index or memory_usage
=> feat: added a monitoring log for steps in pandas executor [TCTC-2844]

server/CHANGELOG.md, server/setup.cfg, server/src/weaverbird/backends/pandas_executor/pipeline_executor.py
An error was occurring on laputa for this log on any step object, with orjson failing to parse the json extras !
=> fix: logs steps objects [TCTC-2844]

Dockerfile
=> fix(Dockerfile): Set python version in Dockerfile to 3.10

server/CHANGELOG.md, server/pyproject.toml
=> chore(server): v0.13.1

playground/app.js, src/store/state.ts
Retrieve the ff defined in tucana in order to hide feature for basemap as usual datasource currently under development
Also need to review: https://github.com/ToucanToco/tucana/pull/12280
=> chore: add ff for basemap as usual datasource [TCTC-3016]

server/CHANGELOG.md
=> docs: Update server changelog

server/src/weaverbird/backends/pypika_translator/translators/base.py
We muste handle the case of user defined query string "code mode" for sql queries. 
Thus I suggest we allow the pipeline's first step to be a CustomSqlStep.
=> feat(sql pypika): handle code mode query as customsqlstep

server/CHANGELOG.md, server/pyproject.toml
* To release the code mode query feature on pypika translators
=> chore(bump): v0.16.0

server/CHANGELOG.md, server/pyproject.toml
=> chore(version): v0.16.1

docker-compose.yml
=> fix(docker-compose): Add missing POSTGRESQL_CONNECTION_STRING

server/tests/backends/fixtures/aggregate/with_original_granularity_athena.json, server/tests/backends/fixtures/argmax/simple_athena.json, server/tests/backends/fixtures/argmax/with_group_athena.json, server/tests/backends/fixtures/argmin/with_group_athena.json, server/tests/backends/fixtures/delete/simple_athena.json, server/tests/backends/fixtures/duplicate/simple_athena.json, server/tests/backends/fixtures/fillna/simple_athena.json, server/tests/backends/fixtures/filter/eq_athena.json, server/tests/backends/fixtures/formula/division_athena.json, server/tests/backends/fixtures/formula/nested_athena.json, server/tests/backends/fixtures/formula/simple_athena.json, server/tests/backends/fixtures/ifthenelse/combinations_athena.json, server/tests/backends/fixtures/ifthenelse/nested_athena.json, server/tests/backends/fixtures/ifthenelse/simple_athena.json, server/tests/backends/fixtures/lowercase/simple_athena.json, server/tests/backends/fixtures/rename/edge_case_athena.json, server/tests/backends/fixtures/rename/multiple_athena.json, server/tests/backends/fixtures/rename/simple_athena.json, server/tests/backends/fixtures/replace/simple_athena.json, server/tests/backends/fixtures/sort/simple_athena.json, server/tests/backends/fixtures/split/simple_athena.json, server/tests/backends/fixtures/substring/simple_athena.json, server/tests/backends/fixtures/text/simple_athena.json, server/tests/backends/fixtures/top/simple_athena.json, server/tests/backends/fixtures/trim/multiple_columns_athena.json, server/tests/backends/fixtures/trim/single_column_athena.json, server/tests/backends/fixtures/uppercase/simple_athena.json
=> fix(backend/fixtures/athena): Update fixtures according to recent dataset update

server/CHANGELOG.md, server/pyproject.toml, server/src/weaverbird/pipeline/steps/customsql.py, server/tests/steps/test_cumstomsql.py
DO NOT SQUASH & MERGE THIS, it includes a release
=> Trim semicolumn customsql

server/tests/backends/fixtures/lowercase/simple_pypika_null.json, server/tests/backends/fixtures/uppercase/simple_pypika_null.json, server/tests/backends/sql_translator_integration_tests/test_sql_postgres_pypika_translator_steps.py
* Add a edge case (null values) for pypika uppercase & lowercase
=> tests(pypika): upper & lower case edge case

server/tests/backends/fixtures/concatenate/simple_pypika.yaml
=> test(server/pypika): Add concatenate fixture for pypika

server/src/weaverbird/backends/pypika_translator/translators/base.py, server/tests/backends/fixtures/formula/division_zero_pypika.json, server/tests/backends/fixtures/formula/nested_divisions_pypika.json, server/tests/backends/sql_translator_unit_tests/test_base_translator.py
- add fixture for nested formula division
- add a support/except for zero division on formula step + fixture test
=> feat: pypika formula divsisions [TCTC-3293]

server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py, server/tests/backends/fixtures/split/simple_pypika.json
* Implement big query split's step
=> feat(bigquery): split step

server/src/weaverbird/backends/pypika_translator/translators/base.py, server/tests/backends/fixtures/append/different_columns_pypika.yaml, server/tests/backends/fixtures/append/different_columns_tricky_pypika.yaml, server/tests/backends/fixtures/append/multiple_pypika.yaml, server/tests/backends/fixtures/append/nested_pypika.yaml, server/tests/backends/fixtures/append/simple_pypika.yaml, server/tests/backends/sql_translator_unit_tests/test_base_translator.py
=> feat(backend/pypika): Implement APPEND step TCTC-3157

src/lib/translators/pypika.ts, tests/unit/translator.spec.ts
=> chore(frontend): Enable join and append steps for pypika-based translators

server/src/weaverbird/backends/pypika_translator/translators/athena.py, server/src/weaverbird/backends/pypika_translator/translators/base.py, server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py, server/src/weaverbird/backends/pypika_translator/translators/mysql.py, server/src/weaverbird/backends/pypika_translator/translators/postgresql.py, server/src/weaverbird/backends/pypika_translator/translators/redshift.py, server/src/weaverbird/backends/pypika_translator/translators/snowflake.py, server/tests/backends/fixtures/convert/from_datetime_to_text_athena_bq.json, server/tests/backends/fixtures/convert/from_datetime_to_text_pypika.json, server/tests/backends/fixtures/convert/to_bool_pypika.json, server/tests/backends/fixtures/convert/to_text_pypika.json, server/tests/backends/sql_translator_integration_tests/test_postgres_translator_steps.py, server/tests/backends/sql_translator_unit_tests/test_type_mapping_translators.py
* Fixtures for convert to int/bool & text
=> feat(pypika convert) TCTC-3291

server/src/weaverbird/backends/pypika_translator/translators/athena.py, server/src/weaverbird/backends/pypika_translator/translators/base.py, server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py, server/src/weaverbird/backends/pypika_translator/translators/mysql.py, server/src/weaverbird/backends/pypika_translator/translators/postgresql.py, server/src/weaverbird/backends/pypika_translator/translators/snowflake.py, server/tests/backends/fixtures/formula/special_brackets_pypika.json, server/tests/backends/sql_translator_unit_tests/test_base_translator.py
- added a sanitizer for columns on the formula step
=> fix: formula step pypika [TCTC-3293]

.github/workflows/ci-server.yml, server/Makefile, server/poetry.lock, server/pyproject.toml, server/tests/backends/sql_translator_integration_tests/test_postgres_translator_steps.py, server/tests/backends/sql_translator_integration_tests/test_sql_mysql_translator_steps.py, server/tests/backends/sql_translator_integration_tests/test_sql_postgres_pypika_translator_steps.py
Parallelize tests that can be parallelized.
=> ci: parallelize tests

server/CHANGELOG.md, server/poetry.lock, server/pyproject.toml
=> chore: bump v0.18.0

server/CHANGELOG.md, server/poetry.lock, server/pyproject.toml, server/src/weaverbird/backends/pypika_translator/translators/athena.py, server/src/weaverbird/backends/pypika_translator/translators/base.py, server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py, server/src/weaverbird/backends/pypika_translator/translators/mysql.py, server/src/weaverbird/backends/pypika_translator/translators/postgresql.py, server/src/weaverbird/backends/pypika_translator/translators/redshift.py, server/src/weaverbird/backends/pypika_translator/translators/snowflake.py, server/tests/backends/fixtures/dateextract/snowflake_all_cases.json, server/tests/backends/sql_translator_unit_tests/test_snowflake_translator.py
This step was not implemented. 
Only Snowflake pypika for now as it was requested within a bug card
=> feat(pypika Snowflake): date extract

server/CHANGELOG.md, server/poetry.lock, server/pyproject.toml, server/src/weaverbird/backends/pypika_translator/operators.py, server/src/weaverbird/backends/pypika_translator/translators/athena.py, server/src/weaverbird/backends/pypika_translator/translators/base.py, server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py, server/src/weaverbird/backends/pypika_translator/translators/mysql.py, server/src/weaverbird/backends/pypika_translator/translators/postgresql.py, server/src/weaverbird/backends/pypika_translator/translators/redshift.py, server/src/weaverbird/backends/pypika_translator/translators/snowflake.py, server/tests/backends/sql_translator_unit_tests/test_date_format_translators.py, server/tests/backends/sql_translator_unit_tests/test_type_mapping_translators.py
* Make `to_date` return timestamps.
=> chore: return to_date result as timestamps

src/lib/translators/pypika.ts
=> chore(frontend): Enable todate step for pypika-based translators

server/CHANGELOG.md, server/pyproject.toml, server/src/weaverbird/backends/pypika_translator/translators/athena.py, server/src/weaverbird/backends/pypika_translator/translators/base.py, server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py, server/src/weaverbird/backends/pypika_translator/translators/mysql.py, server/src/weaverbird/backends/pypika_translator/translators/postgresql.py, server/src/weaverbird/backends/pypika_translator/translators/redshift.py, server/src/weaverbird/backends/pypika_translator/translators/snowflake.py, server/tests/backends/fixtures/unpivot/simple_pypika.json, server/tests/backends/sql_translator_unit_tests/test_redshift_translator.py, server/tests/backends/sql_translator_unit_tests/test_snowflake_translator.py, src/lib/translators/pypika.ts
=> feat(pypika): unpivot [TCTC-3668]

CHANGELOG.md, package.json, sonar-project.properties
* Enable Unpivot Step in Pypika Translators;
=> chore: v0.88.0

docs/_docs/user-interface/formula.md
In the interface (user) doc, we added the listing of supported operators.
=> Formula step : Adding supported operators

server/src/weaverbird/backends/pypika_translator/translators/base.py, server/tests/backends/sql_translator_unit_tests/test_base_translator.py
if can have a patch version of weaverbird that'd be great
=> fix: step names should be predictive for cache to work

server/CHANGELOG.md, server/pyproject.toml
=> chore(server): v0.23.0

server/CHANGELOG.md, server/pyproject.toml
=> chore(server): v0.24.0

README.md, playground/app.js, server/playground.py, server/poetry.lock, server/pyproject.toml
Useful when developing the front-end!
=> feat(playground): run front-end against a remote server

server/CHANGELOG.md, server/pyproject.toml, server/src/weaverbird/backends/pypika_translator/dialects.py
Necessary for https://toucantoco.atlassian.net/browse/TCTC-3370
=> chore(server): SQLDialect now uses the same values than frontend translator names

src/lib/translators/athena.ts, src/lib/translators/google-big-query.ts, src/lib/translators/postgresql.ts, src/lib/translators/redshift.ts
=> feat(frontend): Add dateextract step to different native translators TCTC-3513

server/src/weaverbird/backends/pypika_translator/translators/base.py, server/tests/backends/fixtures/cumsum/simple_pypika.json, server/tests/backends/fixtures/cumsum/with_groups_pypika.json, server/tests/backends/fixtures/cumsum/with_multiple_values_pypika.json, server/tests/backends/sql_translator_unit_tests/test_base_translator.py, src/lib/translators/pypika.ts
=> feat(server/pypika): Implement cumsum step TCTC-3801

.github/workflows/ci-server.yml
=> fix(ci): Pin python version to 3.10.6

CHANGELOG.md, package.json, sonar-project.properties
=> chore(front): v0.91.0

server/CHANGELOG.md, server/pyproject.toml
=> chore(back): v0.25.0

server/CHANGELOG.md, server/pyproject.toml
=> chore(server): v0.25.3

.github/workflows/ci-server.yml
=> chore(ci/server): Bump ubuntu version 20.04 -> latest

.github/dependabot.yml
Just added dependabot for weaverbird front
=> chore(front): added dependabot for weaverbird frontend

server/playground.py
=> fix(playground): Allow playground to work even if snowflake is not available

docker-compose.yml, playground/app.js, playground/datastore-mysql/default-dataset.csv, playground/datastore-mysql/sales.csv, playground/init-mysql/default-dataset.sql, playground/init-mysql/enable_local_files.cnf, playground/init-mysql/sales.sql, server/playground.py
=> feat(playground): Added support for MySQL TCTC-3401

src/lib/translators/mongo5.ts, tests/unit/action-toolbar-button.spec.ts
=> feat(frontend): Added support for replacetext to mongo5 translator

CHANGELOG.md, package.json, sonar-project.properties
=> chore(front): v0.92.1

src/lib/translators/mongo5.ts, tests/unit/action-toolbar-button.spec.ts
=> feat(frontend): Added support for replacetext to mongo5 translator (#1563) [backport]

server/playground.py
=> fix(playground): _SNOWFLAKE_CONNECTION needs to be defined

playground/app.js, src/components/constants.ts, src/store/state.ts, tests/unit/action-toolbar.spec.ts
=> chore(front): remove feature flag hiding geo category TCTC-4234

CHANGELOG.md, package.json
=> chore(front): v0.93.0

docs/_docs/user-interface/todate.md
=> docs: Update the links for todate format strings TCTC-4349

docs/_docs/user-interface/todate.md, src/components/stepforms/ToDateStepForm.vue
=> feat(front/ToDateStepForm): Update format reference links to match the documentation TCTC-4350

server/CHANGELOG.md, server/pyproject.toml
=> chore(server): 0.27.0

server/CHANGELOG.md, server/pyproject.toml
=> chore: v0.26.2

server/playground.py
=> feat(server/playground): Add support for "geometry" dtype for the pandas executor

docs/_data/docs.yml
=> fix(docs): Add missing menu entries for geo steps

playground/dist/index.html, playground/dist/weaverbird.umd.cjs, playground/dist/weaverbird.umd.js, server/playground.py
Work items:
* fix(playground/frontend): Fix links for dist files
* fix(playground/backend): Enforce the right mimetype for .cjs files
=> Adapt playground to recent UI build changes

ui/package.json, ui/yarn.lock
Closes #1588 #1587 #1596 #1597 #1598
=> chore(ui): depencies security updates

playground/dist/index.html, playground/dist/weaverbird.umd.cjs, playground/dist/weaverbird.umd.js, server/playground.py, ui/CHANGELOG.md, ui/src/lib/labeller.ts, ui/tests/unit/labeller.spec.ts
=> fix(frontend): Try to also access camel case attributes in the step labeller TCTC-4619

server/CHANGELOG.md, server/poetry.lock, server/pyproject.toml
=> chore(server): v0.27.2

server/playground.py
Seems like this disappeared during a previous rebase..
=> fix(playground): Add pagination_info for pandas

.github/dependabot.yml
Slow down dependabot checks from day to day to week !
=> deps: dependabot from daily to weekly checks

ui/CHANGELOG.md, ui/src/lib/labeller.ts, ui/tests/unit/labeller.spec.ts
=> feat(ui/labeller): Improve label for geographical hierarchy step

ui/CHANGELOG.md, ui/package.json, ui/sonar-project.properties
=> chore(ui): v0.98.0

server/CHANGELOG.md, server/pyproject.toml
=> chore(backend): v0.26.3

server/CHANGELOG.md, server/pyproject.toml
bump weaverbird from 0.27.2 to 0.27.3
https://github.com/ToucanToco/weaverbird/pull/1639
=> chore(server): bump weaverbird from 0.27.2 to 0.27.3

server/CHANGELOG.md, server/src/weaverbird/backends/pandas_executor/steps/date_extract.py, server/tests/steps/test_date_extract.py
=> fix(backend/pandas): Convert target column to datetime before extracting datetime information TCTC-4825

server/src/weaverbird/backends/pandas_executor/steps/date_extract.py
=> refactor(backend/pandas): Make previous quarter logic more explicit

server/CHANGELOG.md, server/pyproject.toml
=> chore(server): v0.26.4

server/CHANGELOG.md, server/pyproject.toml, server/src/weaverbird/backends/pandas_executor/steps/date_extract.py, server/src/weaverbird/backends/pandas_executor/steps/duration.py, server/src/weaverbird/backends/pandas_executor/steps/evolution.py, server/tests/steps/test_date_extract.py, server/tests/steps/test_duration.py, server/tests/steps/test_evolution.py
On approval, this will be rebased and merged
=> Backport recent pandas fixes

server/poetry.lock, server/pyproject.toml
=> chore(deps): Avoid yanked releases

server/CHANGELOG.md, server/pyproject.toml
=> chore: v0.26.5

server/src/weaverbird/backends/pypika_translator/translators/base.py, server/src/weaverbird/backends/pypika_translator/translators/exceptions.py, server/tests/backends/sql_translator_unit_tests/test_base_translator.py, server/tests/backends/sql_translator_unit_tests/test_base_translator_strings.py
=> refactor(backend/pypika): Prevent the usage of wildcards in column lists TCTC-4241

server/CHANGELOG.md, server/src/weaverbird/backends/pandas_executor/steps/top.py, server/tests/backends/fixtures/top/simple_strings.json, server/tests/backends/fixtures/top/with_groups_and_dates.json
=> fix(backend/pandas): Add support for non-numeric columns to "top" step TCTC-4604

server/CHANGELOG.md, server/pyproject.toml
=> chore(server): v0.26.6

ui/package.json
This will help render figure out which version to use https://render.com/docs/node-version
=> fix(ui): specify which node version is supported

server/CHANGELOG.md, server/pyproject.toml
=> chore(server): v0.28.1

server/CHANGELOG.md, server/poetry.lock, server/pyproject.toml
=> chore(server): v0.28.2

server/src/weaverbird/backends/pypika_translator/translators/base.py, server/tests/backends/fixtures/aggregate/multiple_aggregations_with_window_func_pypika.json
Fixes https://toucantoco.atlassian.net/browse/TCTC-5844
=> chore: quote column names in "OVER(PARTITION BY xxx" [TCTC-5844]

server/tests/backends/sql_translator_integration_tests/test_sql_mysql_translator_steps.py
This is just a backport to skip flaky MySQL tests
=> fix(server/tests): Skip flaky MySQL tests (#1759)

server/CHANGELOG.md, server/pyproject.toml
=> chore: bump weaverbird from 0.26.6 to 0.26.7

server/CHANGELOG.md, server/pyproject.toml
=> chore: bump from 0.26.7 to 0.26.8 [TCTC-6089]

server/src/weaverbird/backends/pypika_translator/translators/base.py, server/tests/backends/sql_translator_unit_tests/test_base_translator.py, server/tests/backends/sql_translator_unit_tests/test_snowflake_translator.py
This is just a backport from https://github.com/ToucanToco/weaverbird/pull/1789
=> feat: we want to cast to integer a column resulting from a date extract (#1789)

server/CHANGELOG.md, server/pyproject.toml, server/src/weaverbird/backends/pypika_translator/translators/base.py, server/tests/backends/sql_translator_unit_tests/test_base_translator.py, server/tests/backends/sql_translator_unit_tests/test_snowflake_translator.py
Just a bump from 0.31.0 to 0.31.1
=> chore: bump from 0.31.0 to 0.31.1

server/CHANGELOG.md, server/pyproject.toml
Just bumping from 0.31.1 to 0.32.0
=> chore: bump from 0.31.1 to 0.32.0

playground/dist/app.js, ui/CHANGELOG.md, ui/Playground.vue, ui/src/components/stepforms/AppendStepForm.vue, ui/src/components/stepforms/JoinStepForm.vue, ui/src/components/stepforms/widgets/Autocomplete.vue, ui/src/components/stepforms/widgets/Multiselect.vue, ui/tests/unit/append-step-form.spec.ts, ui/tests/unit/join-step-form.spec.ts
Add a tooltip to unjoinable datasets aqnd make title readable in multiselect disabled options
=> feat(append-join-steps): add a tooltip to explain disabled dataset options [TCTC-5745]

server/src/weaverbird/backends/mongo_translator/steps/join.py, server/tests/backends/fixtures/join/left_weird_name.json, server/tests/backends/mongo_translator/test_mongo_translator_steps.py
This fixes the join step when joining on columns with invalid names.
closes TCTC-6412
=> fix(server/mongo): Fix join step on columns with weird names TCTC-6412

ui/CHANGELOG.md, ui/src/lib/translators/pypika.ts
The step is already implemented in the pypika translator, it just needs to be added in the frontend
=> feat(ui): Added concatenate step to pypika translator TCTC-6155

server/CHANGELOG.md, server/src/weaverbird/pipeline/pipeline.py, server/tests/test_pipeline.py
=> fix(server/pipeline): Preserve falsy values in remove_void_conditions_from_mongo_steps TCTC-6570

server/CHANGELOG.md, server/src/weaverbird/backends/pypika_translator/translators/athena.py, server/src/weaverbird/backends/pypika_translator/translators/base.py, server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py, server/src/weaverbird/backends/pypika_translator/translators/postgresql.py, server/src/weaverbird/backends/pypika_translator/translators/snowflake.py, server/tests/backends/fixtures/duration/all_cases_pypika.yaml, server/tests/backends/sql_translator_unit_tests/conftest.py, server/tests/backends/sql_translator_unit_tests/test_base_translator.py, server/tests/backends/sql_translator_unit_tests/test_date_format_translators.py, server/tests/backends/sql_translator_unit_tests/test_filter_translators.py, server/tests/backends/sql_translator_unit_tests/test_row_number_translators.py, server/tests/backends/sql_translator_unit_tests/test_split_part_translators.py, server/tests/backends/sql_translator_unit_tests/test_type_mapping_translators.py, ui/CHANGELOG.md, ui/src/lib/translators/pypika.ts
=> feat(server/pypika): Add support for the duration step TCTC-6158

ui/CHANGELOG.md, ui/src/lib/translators/pypika.ts
=> feat(ui): Disable customsql step in pypika translator TCTC-6722

server/CHANGELOG.md, server/src/weaverbird/backends/pypika_translator/translators/base.py, server/tests/backends/fixtures/evolution/perc_nogroups_integers_pypika.yaml
=> fix(server/pypika): Ensure the duration step converts columns to floats before dividing

server/CHANGELOG.md, server/src/weaverbird/backends/pypika_translator/translators/base.py, server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py, server/tests/backends/fixtures/dateextract/first_day_of_previous_month_pypika.yaml
=> fix(server/pypika): fix `firstDayOfPreviousMonth` for dateextract step TCTC-6735

server/CHANGELOG.md, server/pyproject.toml, server/src/weaverbird/pipeline/steps/utils/combination.py, server/tests/pipeline/steps/utils/test_combination.py
=> fix(server): Fix perf issues with PipelineOrDomainName validators TCTC-7558

server/CHANGELOG.md, server/src/weaverbird/pipeline/conditions.py, server/src/weaverbird/pipeline/dates.py, server/src/weaverbird/pipeline/steps/filter.py, server/tests/steps/test_filter.py
=> feat(steps/filter): Allow using variables in RelativeDate TCTC-7581

server/CHANGELOG.md, server/src/weaverbird/pipeline/steps/ifthenelse.py, server/tests/steps/test_ifthenelse.py
=> fix(server/steps): Allow IfThenElseStepWithVariables to be used with RelativeDateConditionWithVariables

server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py
fix the error `'DATE_ADD does not support the YEAR date part when the argument is TIMESTAMP type at [1:4223]'`
=> fix(gbq translator): todate now produces DATETIME cols, not TIMESTAMP [TCTC-7994]

server/CHANGELOG.md, server/pyproject.toml, server/src/weaverbird/backends/mongo_translator/utils.py, server/src/weaverbird/backends/pypika_translator/translators/googlebigquery.py, server/tests/backends/fixtures/ifthenelse/combination_or.json
backport of https://github.com/ToucanToco/weaverbird/pull/2030 for LTS
=> [backport] fix(mongo translator): fix typo in ifthenelse "$or" combination

server/CHANGELOG.md, server/pyproject.toml, server/src/weaverbird/backends/pandas_executor/steps/rollup.py, server/tests/backends/fixtures/rollup/no_aggs_single_label.yaml
=> fix(server/pandas): fix rollup step in case there is a single hierarchy level [TCTC-8093]

server/CHANGELOG.md, server/src/weaverbird/backends/pandas_executor/steps/evolution.py, server/tests/backends/fixtures/evolution/abs_nogroups_multirow_lag.yaml
=> fix(server/pandas): prevent DataFrame index shift in evolution step (cherry-picked from #2079)

server/src/weaverbird/backends/mongo_translator/steps/formula.py, server/src/weaverbird/pipeline/formula_ast/eval.py, server/src/weaverbird/pipeline/formula_ast/types.py, server/tests/backends/fixtures/formula/text_quotes.json
Single quotes were not handled properly in ast parser, resulting in formula and conditional steps not working properly.
=> fix(formula): handle single quotes in formula and conditional steps [TCTC-8504]

ui/CHANGELOG.md, ui/src/main.ts
Will be used for pipeline component migration
=> feat(pipeline): export step labeller function

server/CHANGELOG.md, server/pyproject.toml, server/src/weaverbird/backends/pandas_executor/steps/evolution.py, server/tests/backends/fixtures/evolution/multiple_evolutions_with_groups.yaml
=> fix(pandas/evolution): fix _prev_date columns regression [TCTC-8685] (#2125)

ui/src/store/actions.ts, ui/src/store/state.ts, ui/tests/unit/store.spec.ts
The other should be discarded (race condition)
=> fix(ui): only result of the last request should be used TCTC-8992

ui/src/components/stepforms/AddTotalRowsStepForm.vue, ui/stories/AddTotalRowsStepForm.stories.ts, ui/tests/unit/totals-step-form.spec.ts
Instead of setting an invalid default aggregation, let's not add one to start with.
=> fix(ui): add total step rows does not require any aggregation TCTC-9199

ui/CHANGELOG.md, ui/package.json, ui/sonar-project.properties, ui/src/components/stepforms/AggregateStepForm.vue
Updates the wording for this label
=> fix(ui/AggregateStepForm): better wording for countNulls label
